import crypto from 'node:crypto';
import { id, now } from '../shared/util.js';
import { query, execSql, esc, migrate } from '../task-engine/db.js';
import { NODE_ENV, TRUST_PROXY } from '../shared/config.js';

migrate();
const HOUR = 60 * 60 * 1000;
export function createSession({ userId='admin', ip='', userAgent='', ttlMs=8*HOUR }={}){ cleanupSessions(500); const sid=id('sess'); const csrf=crypto.randomBytes(16).toString('hex'); const exp=new Date(Date.now()+ttlMs).toISOString(); execSql(`INSERT INTO sessions VALUES (${esc(sid)},${esc(userId)},${esc(csrf)},${esc(ip)},${esc(userAgent)},${esc(exp)},NULL,${esc(now())},NULL);`); return {id:sid,csrfToken:csrf,expiresAt:exp,userId}; }
export function lookupSession(sessionId){ if(!sessionId)return null; const s=query(`SELECT * FROM sessions WHERE id=${esc(sessionId)};`)[0]; if(!s||s.revoked_at||new Date(s.expires_at)<=new Date()) return null; const rb=query(`SELECT revoked_before FROM session_revocations WHERE user_id=${esc(s.user_id)};`)[0]?.revoked_before; if(rb && new Date(s.created_at)<=new Date(rb)) return null; return s; }
export function rotateSession(sessionId, meta={}){ const old=lookupSession(sessionId); if(!old)return null; revokeSession(sessionId); const s=createSession({userId:old.user_id,ip:meta.ip||old.ip,userAgent:meta.userAgent||old.user_agent}); execSql(`UPDATE sessions SET rotated_from=${esc(sessionId)} WHERE id=${esc(s.id)};`); return s; }
export function revokeSession(sessionId){ execSql(`UPDATE sessions SET revoked_at=${esc(now())} WHERE id=${esc(sessionId)} AND revoked_at IS NULL;`); }
export function revokeAll(userId='admin'){ const t=now(); execSql(`INSERT OR REPLACE INTO session_revocations VALUES (${esc(userId)},${esc(t)},${esc(t)}); UPDATE sessions SET revoked_at=${esc(t)} WHERE user_id=${esc(userId)} AND revoked_at IS NULL;`); }
export function cleanupSessions(limit=1000){ execSql(`DELETE FROM sessions WHERE id IN (SELECT id FROM sessions WHERE expires_at < ${esc(now())} OR revoked_at IS NOT NULL ORDER BY expires_at LIMIT ${Number(limit)});`); }
export function sessionCookies(session,{secure=NODE_ENV==='production'}={}){ const attrs=`Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${secure?'; Secure':''}`; const csrfAttrs=`Path=/; SameSite=Strict; Max-Age=28800${secure?'; Secure':''}`; return [`__Host-bsc_session=${session.id}; ${attrs}`,`bsc_csrf=${session.csrfToken}; ${csrfAttrs}`]; }
export function clearCookies({secure=NODE_ENV==='production'}={}){ const s=secure?'; Secure':''; return [`__Host-bsc_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${s}`,`bsc_csrf=; Path=/; SameSite=Strict; Max-Age=0${s}`]; }
export function parseCookies(header=''){ return Object.fromEntries(String(header).split(';').map(p=>p.trim()).filter(Boolean).map(p=>{const i=p.indexOf('=');return [p.slice(0,i),decodeURIComponent(p.slice(i+1))]})); }
export function requireCsrf(req, session){ if(['GET','HEAD','OPTIONS'].includes(req.method))return true; return Boolean(session && req.headers['x-csrf-token'] && req.headers['x-csrf-token']===session.csrf_token); }
export function clientIp(req, { trustProxy = TRUST_PROXY } = {}){ if(trustProxy && req.headers['x-forwarded-for']) return String(req.headers['x-forwarded-for']).split(',')[0].trim(); return req.socket?.remoteAddress || 'unknown'; }
export function assertProductionSafe(env=process.env){ const failures=[]; const prod=env.NODE_ENV==='production'; if(prod && (!env.COMMAND_ADMIN_TOKEN||env.COMMAND_ADMIN_TOKEN.length<24||env.COMMAND_ADMIN_TOKEN.includes('change-me'))) failures.push('weak admin token'); if(prod && (!env.SESSION_SECRET||env.SESSION_SECRET.length<32||env.SESSION_SECRET.includes('change-me'))) failures.push('weak session secret'); if(prod && String(env.PUBLIC_URL||'').startsWith('http://')) failures.push('HTTP public URL'); if(prod && env.SECURE_COOKIES==='false') failures.push('secure cookies disabled'); if(env.CORS_ORIGIN==='*') failures.push('wildcard CORS'); if(prod && env.DEBUG==='true') failures.push('debug mode'); if(prod && env.RATE_LIMIT_DISABLED==='true') failures.push('rate limiting disabled'); if(prod && env.TELEGRAM_MODE==='webhook'&&!env.TELEGRAM_WEBHOOK_SECRET) failures.push('missing Telegram webhook secret'); if(env.TRUST_PROXY==='true'&&!env.TRUSTED_PROXY_CONFIGURED) failures.push('missing trusted proxy configuration'); if(env.DB_DIR_WRITABLE==='false') failures.push('unwritable database directory'); if(env.ATTACHMENT_DIR_WRITABLE==='false') failures.push('unwritable temporary attachment directory'); if(Number(process.versions.node.split('.')[0])<20) failures.push('unsupported Node version'); if(env.GIT_WORKFLOW_ENABLED==='true' && env.GIT_AVAILABLE==='false') failures.push('missing Git'); return {ok:failures.length===0,failures}; }
