import fs from 'node:fs';
import path from 'node:path';
import { ATTACHMENT_TMP_DIR } from '../shared/config.js';
import { id, redact } from '../shared/util.js';
import { execSql, esc, migrate } from '../task-engine/db.js';
import { createTask } from '../task-engine/tasks.js';
const MIME = new Set(['text/plain', 'text/markdown', 'application/json']);
const MAX = 1024 * 1024;
migrate();
export async function getTelegramFile(token, fileId, fetcher = fetch) { const response = await fetcher(`https://api.telegram.org/bot${token}/getFile?file_id=${encodeURIComponent(fileId)}`); const json = await response.json(); if (!json.ok) throw new Error('getFile failed'); return json.result; }
export async function downloadTelegramFile(token, filePath, fetcher = fetch) { const response = await fetcher(`https://api.telegram.org/file/bot${token}/${filePath}`); return Buffer.from(await response.arrayBuffer()); }
export async function handleTelegramAttachment({ token = 'mock', fileId, taskId, workspaceId, mime = 'text/plain', size = 0, fetcher = fetch }) { if (size > MAX) throw new Error('attachment too large'); if (!MIME.has(mime)) throw new Error('mime not allowed'); fs.mkdirSync(ATTACHMENT_TMP_DIR, { recursive: true }); const meta = await getTelegramFile(token, fileId, fetcher); if (Number(meta.file_size || size) > MAX) throw new Error('attachment too large'); const buffer = await downloadTelegramFile(token, meta.file_path, fetcher); if (buffer.length > MAX) throw new Error('attachment too large after download'); const safe = `${id('att')}-${path.basename(meta.file_path).replace(/[^a-zA-Z0-9_.-]/g, '_')}`; const output = path.join(ATTACHMENT_TMP_DIR, safe); fs.writeFileSync(output, buffer); const content = redact(buffer.toString('utf8')); execSql(`INSERT INTO attachments VALUES (${esc(id('attachment'))},${esc(taskId)},${esc(workspaceId)},${esc(fileId)},${esc(output)},${esc(mime)},${buffer.length},'telegram_file',${esc(content)},datetime('now'));`); fs.rmSync(output, { force: true }); return { path: output, size: buffer.length, content, cleaned: !fs.existsSync(output) }; }
export async function handleVoiceNote({ token = 'mock', fileId, workspaceId, transcribe, fetcher = fetch }) { if (!transcribe) return { ok: false, error: 'transcription unavailable' }; const file = await handleTelegramAttachment({ token, fileId, workspaceId, mime: 'text/plain', fetcher }); try { const transcript = await transcribe(file.content); if (!transcript) return { ok: false, error: 'empty transcript' }; const task = createTask({ workspaceId, request: transcript, idempotencyKey: id('voice') }); return { ok: true, task, transcript }; } catch (error) { return { ok: false, error: error.message }; } }
export async function sendTelegramDocument({ token, chatId, filename, content, fetcher = fetch }) { const form = new FormData(); form.set('chat_id', String(chatId)); form.set('document', new Blob([content]), filename); const response = await fetcher(`https://api.telegram.org/bot${token}/sendDocument`, { method: 'POST', body: form }); return response.json(); }
