"use client";
import { useEffect, useState } from "react";

type R1={hypothesis:string;validation_start:string;days_recorded:number;events:number;wins:number;success_pct:number|null;wilson95:[number|null,number|null];gate_status:string;events_remaining:number;ledger_tip_sha256?:string;updated_at_utc?:string;status?:string};
type V2={hypothesis:string;validation_start:string;days_recorded:number;trades:number;wins:number;expectancy_r:number|null;mean_r_lower95:number|null;profit_factor:number|null;net_pnl:number;gate_status:string;trades_remaining:number;ledger_tip_sha256?:string;updated_at_utc?:string;status?:string};
type Payload={r1:R1;v2:V2;live_trading:boolean;broker_execution_authorized:boolean};
const f=(v:number|null|undefined,d=2)=>v==null?"—":v.toFixed(d);
const Card=({label,value}:{label:string;value:string})=><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>;
export default function HelixTradeCommandPage(){
 const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true; const load=async()=>{try{const r=await fetch('/api/helix-trade/research-status',{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(`HTTP ${r.status}`);if(active){setData(b);setError(null)}}catch(e){if(active)setError(e instanceof Error?e.message:'Unavailable')}};load();const id=setInterval(load,60000);return()=>{active=false;clearInterval(id)}},[]);
 const r1=data?.r1,v2=data?.v2;
 return <main className="min-h-screen bg-black px-4 py-10 text-white lg:px-10"><div className="mx-auto max-w-6xl space-y-8">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-teal-300">Zola · Helix Trade Command</p><h1 className="mt-2 text-3xl font-black">Prospective Research</h1><p className="mt-2 max-w-3xl text-sm text-zinc-400">Two frozen research tracks running in parallel. Read-only telemetry; no order placement, halt clearing, or broker authorization.</p></div><div className="rounded-full border border-amber-400/30 bg-amber-400/10 px-4 py-2 text-xs font-bold text-amber-200">LIVE TRADING DISABLED</div></div>
  {error&&<div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">Status unavailable: {error}</div>}
  <section className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-cyan-300">R1-H1 · directional premise</p><h2 className="mt-1 text-xl font-black">NY confirmation after London sweep</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Events" value={r1?`${r1.events} / 30`:'—'}/><Card label="Wins" value={r1?String(r1.wins):'—'}/><Card label="Success" value={r1?`${f(r1.success_pct,1)}%`:'—'}/><Card label="Gate" value={r1?.gate_status??'—'}/></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 text-sm text-zinc-400">Gate: n≥30, success ≥55%, Wilson lower bound &gt;50%. Wilson: <b className="text-white">[{r1?f(r1.wilson95?.[0],1):'—'}%, {r1?f(r1.wilson95?.[1],1):'—'}%]</b>. Events remaining: <b className="text-white">{r1?.events_remaining??'—'}</b>.</div></section>
  <section className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[0.24em] text-violet-300">London V2 · execution premise</p><h2 className="mt-1 text-xl font-black">Sweep → reclaim → MSS → displacement/FVG retrace</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="Trades" value={v2?`${v2.trades} / 30`:'—'}/><Card label="Expectancy" value={v2?`${f(v2.expectancy_r)}R`:'—'}/><Card label="Profit factor" value={v2?f(v2.profit_factor):'—'}/><Card label="Gate" value={v2?.gate_status??'—'}/></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 text-sm text-zinc-400">Gate: ≥30 executed M6E trades, post-cost expectancy &gt;+0.10R, 95% lower bound on mean R &gt;0, PF ≥1.25. Lower bound: <b className="text-white">{v2?f(v2.mean_r_lower95):'—'}R</b>. Net research P&amp;L: <b className="text-white">${v2?f(v2.net_pnl):'—'}</b>.</div></section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="font-bold">Evidence integrity</h2><p className="mt-3 break-all font-mono text-xs text-zinc-500">R1 tip: {r1?.ledger_tip_sha256??'—'}</p><p className="mt-2 break-all font-mono text-xs text-zinc-500">V2 tip: {v2?.ledger_tip_sha256??'—'}</p></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="font-bold">Boundaries</h2><p className="mt-3 text-sm text-zinc-400">Both prospective tracks start 2026-09-12. Passing either gate does not enable demo or live execution; it only permits a separately approved next research stage.</p></div></section>
 </div></main>;
}
