'use client';
import { useEffect, useState } from 'react';
import { analyzeDemoDeal, demoStages, type DemoState } from '@/lib/demo-sandbox';
import type { DemoSnapshot } from '@/lib/demo-access-server';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const input='mt-2 w-full rounded-xl border border-white/20 bg-zinc-950 p-3 text-white';
const button='rounded-xl bg-amber-300 px-4 py-3 font-semibold text-black disabled:opacity-40';
export function DemoSandboxWorkspace({snapshot,expires}:{snapshot:DemoSnapshot;expires:string}){
 const [data,setData]=useState<{state:DemoState;revision:number}|null>(null);
 const [tab,setTab]=useState('Properties');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/demo/workspace',{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.error);setData(b);}
 useEffect(()=>{let active=true;fetch('/api/demo/workspace',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);if(active)setData(b);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function act(body:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/demo/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,revision:data.revision})});const b=await r.json();if(!r.ok){if(r.status===409)await load();throw Error(b.error);}setData(b);}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 function exportRecords(){if(!data)return;const blob=new Blob([JSON.stringify({label:'Blackspire isolated demonstration records',...data.state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='blackspire-demo-records.json';a.click();URL.revokeObjectURL(url);}
 return <main className="min-h-screen bg-[#050505] px-4 py-8 text-white"><div className="mx-auto max-w-6xl space-y-7">
 <header className="rounded-3xl border border-amber-300/20 bg-gradient-to-br from-amber-300/10 to-transparent p-7"><p className="text-xs uppercase tracking-[.3em] text-amber-200">Blackspire · Private practice workspace</p><h1 className="mt-3 text-3xl font-bold">Explore your real-estate workflow</h1><p className="mt-4 max-w-3xl leading-7 text-zinc-300">Add a property, test your numbers, move it through the pipeline, and organize your next steps. Your edits are saved in this separate workspace. Practice records are fictional or entered by you; the live snapshot is labeled separately.</p><p className="mt-4 text-sm text-amber-200">Access expires {expires}. No outreach is sent and no paid services are called.</p><a className="mt-4 inline-block text-sm underline text-zinc-300" href="/demo/login">Sign in on another device</a></header>
 <nav aria-label="Demo tools" className="flex flex-wrap gap-2">{['Properties','Deals','Buyers','Follow-ups','Activity','Live snapshot'].map(t=><button key={t} onClick={()=>setTab(t)} aria-pressed={tab===t} className={tab===t?button:'rounded-xl border border-white/20 px-4 py-3 text-zinc-300'}>{t}</button>)}</nav>
 {error&&<p role="alert" className="rounded-xl border border-red-400/40 p-4 text-red-200">{error}</p>}
 {!data?<p>Opening your workspace…</p>:<>
 <div className="grid grid-cols-3 gap-3">{[['Properties',data.state.leads.length],['Active deals',data.state.leads.filter(x=>x.stage!=='Intake'&&x.stage!=='Closed').length],['Open follow-ups',data.state.tasks.filter(x=>!x.done).length]].map(([label,value])=><div className="rounded-2xl border border-white/10 p-4" key={label}><p className="text-2xl font-bold text-amber-200">{value}</p><p className="mt-2 text-xs text-zinc-400">{label}</p></div>)}</div>
 {tab==='Properties'&&<section className="space-y-6"><h2 className="text-xl font-bold">Capture a property</h2><form className="grid gap-4 rounded-2xl border border-white/10 p-5 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const values=Object.fromEntries(new FormData(f));await act({action:'addLead',...values});}}>{[['name','Property label','text'],['city','City','text'],['asking','Asking price','number'],['arv','Estimated after-repair value','number'],['repairs','Estimated repairs','number']].map(([name,label,type])=><label key={name} className="text-sm text-zinc-300">{label}<input className={input} name={name} type={type} required min={type==='number'?0:undefined} maxLength={type==='text'?200:undefined}/></label>)}<button disabled={busy} className={button}>Add to workspace</button></form>{data.state.leads.map(l=><article key={l.id} className="rounded-2xl border border-white/10 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">{l.name}</h3><p className="mt-1 text-sm text-zinc-400">{l.city} · {l.stage} · Asking {money(l.asking)}</p></div><button disabled={busy} className={button} onClick={()=>act({action:'runPipeline',id:l.id})}>Run practice pipeline</button></div><p className="mt-3 text-sm text-zinc-400">Calculates a 70% offer ceiling, selects the next stage, and creates a follow-up in this workspace.</p></article>)}</section>}
 {tab==='Deals'&&<section className="space-y-5"><h2 className="text-xl font-bold">Analyze and update deals</h2><p className="text-sm text-zinc-400">Illustrative 70% rule: after-repair value × 70% − repairs. This is a practice calculation, not a valuation or profit guarantee.</p>{data.state.leads.map(l=><form key={l.id+'-'+data.revision} className="space-y-4 rounded-2xl border border-white/10 p-5" onSubmit={e=>{e.preventDefault();act({action:'updateLead',id:l.id,...Object.fromEntries(new FormData(e.currentTarget))});}}><h3 className="text-lg font-bold">{l.name}</h3><div className="grid gap-4 sm:grid-cols-3">{[['asking','Asking price',l.asking],['arv','After-repair value',l.arv],['repairs','Repairs',l.repairs]].map(([name,label,value])=><label className="text-sm text-zinc-300" key={name}>{label}<input className={input} name={String(name)} defaultValue={value} type="number" required min="0"/></label>)}</div><p className="text-amber-200">Offer ceiling {money(analyzeDemoDeal(l).mao)} · Difference from asking {money(analyzeDemoDeal(l).spread)}</p><label className="block text-sm">Stage<select className={input} name="stage" defaultValue={l.stage}>{demoStages.map(s=><option key={s}>{s}</option>)}</select></label><label className="block text-sm">Notes<textarea className={input} name="note" defaultValue={l.note} maxLength={2000}/></label><div className="flex gap-3"><button className={button} disabled={busy}>Save deal</button><button type="button" className="rounded-xl border border-red-300/30 px-4 text-red-200" disabled={busy} onClick={()=>{if(confirm('Remove this practice record?'))act({action:'deleteLead',id:l.id});}}>Remove</button></div></form>)}</section>}
 {tab==='Buyers'&&<section className="space-y-5"><h2 className="text-xl font-bold">Buyer activity reference</h2><p className="text-sm leading-6 text-zinc-400">These are real activity records from the protected live snapshot, captured {new Date(snapshot.capturedAt).toLocaleString()}. Ranking reflects recorded activity, not a confirmed fit or offer for your property. Contact details are excluded.</p>{snapshot.buyers.length?snapshot.buyers.map((b,i)=><article key={i} className="rounded-2xl border border-white/10 p-5"><h3 className="font-bold">{b.name}</h3><p className="mt-2 text-sm text-zinc-400">{b.purchases} recorded purchases · Score {b.score} · {b.cash?'Cash signal':'No cash signal'}</p><button disabled={busy} className="mt-4 rounded-xl border border-amber-200/30 px-4 py-2 text-amber-200" onClick={()=>act({action:'addTask',text:'Review buyer activity for '+b.name})}>Add review follow-up</button></article>):<p>No buyer sample is currently available.</p>}</section>}
 {tab==='Follow-ups'&&<section className="space-y-5"><h2 className="text-xl font-bold">Keep track of next steps</h2><form className="flex gap-3" onSubmit={e=>{e.preventDefault();act({action:'addTask',text:new FormData(e.currentTarget).get('text')});}}><input aria-label="Follow-up text" name="text" required maxLength={500} className={input} placeholder="What needs to happen next?"/><button className={button} disabled={busy}>Add</button></form>{data.state.tasks.map(t=><label key={t.id} className="flex gap-4 rounded-xl border border-white/10 p-5"><input type="checkbox" checked={t.done} disabled={busy} onChange={()=>act({action:'toggleTask',id:t.id})}/><span className={t.done?'line-through text-zinc-500':''}>{t.text}</span></label>)}</section>}
 {tab==='Activity'&&<section className="space-y-3"><h2 className="text-xl font-bold">Your workspace activity</h2>{data.state.activity.map((a,i)=><p key={i} className="rounded-xl border border-white/10 p-4 text-sm text-zinc-300">{a}</p>)}</section>}
 {tab==='Live snapshot'&&<section><h2 className="text-xl font-bold">Live system · read-only reference</h2><p className="mt-3 text-sm text-zinc-400">Separate from your practice records. These counts are retrieved from the live system. Your demo edits do not affect them.</p><div className="mt-5 grid gap-4 sm:grid-cols-3">{Object.entries(snapshot.metrics).map(([k,v])=><div key={k} className="rounded-xl border border-white/10 p-5"><p className="text-3xl text-amber-200">{v}</p><p className="mt-3 text-sm">{k.replace(/([A-Z])/g,' $1')}</p></div>)}</div></section>}
 <footer className="flex flex-wrap gap-3 border-t border-white/10 pt-6"><button className="rounded-xl border border-white/20 px-4 py-3" onClick={exportRecords}>Download my demo records</button><button disabled={busy} className="rounded-xl border border-white/20 px-4 py-3" onClick={()=>{if(confirm('Reset only your demo records to the sample data?'))act({action:'reset'});}}>Reset my workspace</button></footer>
 </>}
 </div></main>;
}
