import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; process.env.BLACKSPIRE_DB_PATH='.blackspire-command/test.sqlite';
import {createTask,getTask,transition,setFlag,getFlag} from '../packages/task-engine/tasks.js'; import {decide,isAllowedPath} from '../packages/policy/policy.js'; import {getWorkspace} from '../packages/workspace-registry/workspaces.js'; import {selectProvider} from '../packages/providers/providers.js'; import {runAllowed} from '../packages/execution/runner.js';
test('task lifecycle supports queued, running, completed, cancelled',()=>{const t=createTask({workspaceId:'blackspire-command',request:'write docs',idempotencyKey:'life-'+Date.now()}); assert.equal(t.status,'queued'); assert.equal(transition(t.id,'running').status,'running'); assert.equal(transition(t.id,'completed').status,'completed'); assert.equal(transition(t.id,'cancelled').status,'cancelled');});
test('policy requires approval for high impact and allows low risk',()=>{assert.equal(decide('production_deploy').requiresApproval,true); assert.equal(decide('read_files').allowed,true);});
test('workspace isolation blocks path traversal',()=>{assert.equal(isAllowedPath('../.env',['docs']),false); assert.equal(isAllowedPath('docs/readme.md',['docs']),true);});
test('provider routing falls back to manual/codex mode safely',()=>{const p=selectProvider({preferred:['openai','manual']}); assert.ok(['openai','manual'].includes(p.provider));});
test('command allowlist blocks bypass',async()=>{const r=await runAllowed('rm -rf /',{allowedCommands:['npm test']}); assert.equal(r.ok,false);});
test('workspace record has required fields',()=>{const w=getWorkspace('blackspire-command'); assert.equal(w.id,'blackspire-command'); assert.ok(Array.isArray(w.allowed_paths)); assert.ok(w.github_repository);});
test('emergency stop flag persists',()=>{setFlag('emergency_stop','active'); assert.equal(getFlag('emergency_stop'),'active'); setFlag('emergency_stop','inactive');});
