import test from 'node:test';
import assert from 'node:assert/strict';
import { MemoryHealthTransitionStore } from '../packages/health-transitions/store.js';
import { HealthTransitionEngine } from '../packages/health-transitions/engine.js';
import { collectHealthObservations } from '../packages/health-transitions/sources.js';
import { readOperatorDiagnostics } from '../packages/health-transitions/diagnostics.js';
import { formatOperatorStatus } from '../packages/health-transitions/formatter.js';

const commit = 'a'.repeat(40); let tick = 0;
const observation = (overrides = {}) => ({ component: 'api_liveness', environment: 'disposable-staging', workspaceId: 'workspace-a', state: 'healthy', timestamp: new Date(Date.UTC(2026,7,5,0,0,tick++)).toISOString(), reasonCode: 'check_passed', reason: 'Fixture health observation', correlationId: `corr-${tick}`, commit, buildFingerprint: 'build-1', dependency: null, source: 'operator_fixture', metadata: {}, ...overrides });
const setup = () => { const store = new MemoryHealthTransitionStore(); return { store, engine: new HealthTransitionEngine(store) }; };

test('healthy startup records deterministic transitions and summaries', () => { const { store, engine } = setup(); engine.observe(observation({ component: 'startup', state: 'starting', reasonCode: 'startup_pending' })); engine.observe(observation({ component: 'startup', state: 'ready', reasonCode: 'startup_complete' })); assert.equal(store.events('disposable-staging','workspace-a').length, 2); assert.equal(engine.summary('disposable-staging','workspace-a').state, 'healthy'); });
test('startup failure recommends rollback without taking action', () => { const { engine } = setup(); const result = engine.observe(observation({ component: 'api_readiness', state: 'unavailable', reasonCode: 'check_failed' })); assert.equal(result.event.rollbackRecommendation, 'rollback_recommended'); assert.equal(result.event.automaticActionTaken, false); });
test('healthy to degraded to healthy records recovery history', () => { const { store, engine } = setup(); engine.observe(observation()); engine.observe(observation({ state: 'degraded', reasonCode: 'check_failed' })); engine.observe(observation({ state: 'healthy' })); assert.deepEqual(store.events('disposable-staging','workspace-a').map((event) => event.newState), ['healthy','degraded','healthy']); });
test('database and queue dependency failures are rollback recommendations', () => { for (const component of ['database','queue']) { const { engine } = setup(); assert.equal(engine.observe(observation({ component, state: 'unavailable', reasonCode: 'dependency_unavailable', dependency: component })).event.rollbackRecommendation, 'rollback_recommended'); } });
test('worker stale and recovery are retained', () => { const { store, engine } = setup(); engine.observe(observation({ component: 'worker', state: 'stale', reasonCode: 'heartbeat_stale' })); engine.observe(observation({ component: 'worker', state: 'healthy', reasonCode: 'heartbeat_recovered' })); assert.equal(store.events('disposable-staging','workspace-a').length, 2); });
test('migration mismatch requires operator intervention', () => { const { engine } = setup(); const event = engine.observe(observation({ component: 'migration', state: 'migration_mismatch', reasonCode: 'version_mismatch' })).event; assert.equal(event.rollbackRecommendation, 'operator_intervention_required'); assert.equal(event.operatorActionRequired, true); });
test('kill switch is visible but does not trigger automatic action', () => { const { engine } = setup(); const event = engine.observe(observation({ component: 'kill_switch', state: 'halted', reasonCode: 'kill_switch_active' })).event; assert.equal(event.rollbackRecommendation, 'investigate'); assert.equal(event.automaticActionTaken, false); });
test('exact duplicates are suppressed and stale or conflicting observations rejected', () => { const { store, engine } = setup(); const first = observation(); assert.equal(engine.observe(first).disposition, 'transition_recorded'); assert.equal(engine.observe(first).disposition, 'duplicate_suppressed'); assert.equal(engine.observe({ ...first, timestamp: new Date(Date.parse(first.timestamp)-1000).toISOString() }).disposition, 'stale_rejected'); assert.equal(engine.observe({ ...first, state: 'degraded' }).disposition, 'timestamp_conflict_rejected'); assert.equal(store.events('disposable-staging','workspace-a').length, 1); });
test('same-state newer observation refreshes latest without flooding history', () => { const { store, engine } = setup(); engine.observe(observation()); assert.equal(engine.observe(observation()).disposition, 'snapshot_refreshed'); assert.equal(store.events('disposable-staging','workspace-a').length, 1); });
test('rapid state flapping is detected', () => { const { engine } = setup(); let result; for (const state of ['healthy','degraded','healthy','degraded']) result = engine.observe(observation({ state, reasonCode: state === 'healthy' ? 'check_passed' : 'check_failed' })); assert.equal(result.event.flapping, true); assert.deepEqual(engine.summary('disposable-staging','workspace-a').flappingComponents, ['api_liveness']); });
test('validated snapshots preserve restart history and latest state', () => { const { store, engine } = setup(); engine.observe(observation()); const recoveredStore = new MemoryHealthTransitionStore(store.snapshot()); const recovered = new HealthTransitionEngine(recoveredStore); assert.equal(recovered.summary('disposable-staging','workspace-a').components[0].state, 'healthy'); assert.equal(recoveredStore.events('disposable-staging','workspace-a').length, 1); });
test('environment and workspace keys remain isolated', () => { const { store, engine } = setup(); engine.observe(observation()); engine.observe(observation({ environment: 'staging', workspaceId: 'workspace-b', state: 'degraded', reasonCode: 'check_failed' })); assert.equal(store.events('disposable-staging','workspace-a').length, 1); assert.equal(store.events('staging','workspace-b').length, 1); assert.equal(store.events('staging','workspace-a').length, 0); });
test('bounded vocabulary, labels, reasons, and secret metadata fail closed or redact', () => { const { engine } = setup(); assert.throws(() => engine.observe(observation({ component: 'customer-123' })), /invalid component/); assert.throws(() => engine.observe(observation({ reason: 'token=secret-value' })), /bounded and redacted/); const event = engine.observe(observation({ metadata: { mode: 'api-token-value', uncontrolled: 'customer payload' } })).event; assert.deepEqual(event.metadata, { mode: '[REDACTED]' }); });
test('existing health sources represent disabled providers, sandbox Telegram, and unsupported scheduler', () => { const items = collectHealthObservations(observation({}), { apiLiveness: true, apiReadiness: true, database: true, queue: true, worker: { ok: true, state: 'idle' }, scheduler: { ok: true, state: 'disabled' }, migrationMatch: true, killSwitch: false, providersDisabled: true, telegramMode: 'sandbox', fingerprintMatch: true }); const by = Object.fromEntries(items.map((item) => [item.component,item])); assert.equal(by.providers.state, 'disabled'); assert.equal(by.telegram.state, 'disabled'); assert.equal(by.scheduler.state, 'disabled'); assert.equal(by.scheduler.reasonCode, 'unsupported'); });

test('diagnostics authorization fails closed and preserves workspace scope', () => { const { store, engine } = setup(); engine.observe(observation()); const denied = readOperatorDiagnostics({ principal: {}, environment: 'disposable-staging', workspaceId: 'workspace-a', store, engine, authorize: () => ({ allowed: false }) }); assert.equal(denied.status, 403); const cross = readOperatorDiagnostics({ principal: {}, environment: 'disposable-staging', workspaceId: 'workspace-b', store, engine, authorize: (_p,w) => ({ allowed: w === 'workspace-a' }) }); assert.equal(cross.status, 403); });
test('diagnostics resolves deployment identity only after authorization', () => { const {store,engine}=setup();let reads=0;const identityProvider={get(){reads++;return {state:'VERIFIED',environment:{state:'VERIFIED',value:'disposable-staging',source:'state_owner'},build:{state:'VERIFIED',value:commit,source:'commit_manifest'},version:'0.1.0',verificationSource:['state_owner','commit_manifest']};}};const denied=readOperatorDiagnostics({principal:{},environment:'disposable-staging',workspaceId:'workspace-a',store,engine,identityProvider,authorize:()=>({allowed:false})});assert.equal(denied.status,403);assert.equal(reads,0);const allowed=readOperatorDiagnostics({principal:{},environment:'disposable-staging',workspaceId:'workspace-a',store,engine,identityProvider,authorize:()=>({allowed:true})});assert.equal(allowed.body.deployment.identity.state,'VERIFIED');assert.equal(reads,1); });
test('diagnostics pagination is deterministic, bounded, and rejects cursor tampering', () => { const { store, engine } = setup(); for (const component of ['api_liveness','database','queue']) engine.observe(observation({ component })); const request = { principal: {}, environment: 'disposable-staging', workspaceId: 'workspace-a', store, engine, authorize: () => ({ allowed: true }), limit: 2 }; const first = readOperatorDiagnostics(request); assert.equal(first.status, 200); assert.equal(first.body.history.length, 2); assert.ok(first.body.nextCursor); assert.equal(readOperatorDiagnostics({ ...request, cursor: `${first.body.nextCursor}x` }).status, 400); assert.equal(readOperatorDiagnostics({ ...request, limit: 101 }).status, 400); const second = readOperatorDiagnostics({ ...request, cursor: first.body.nextCursor }); assert.equal(second.body.history.length, 1); });
test('mobile formatter is transport-neutral and chunks within bounds', () => { const { store, engine } = setup(); for (const component of ['api_liveness','database','queue','worker','scheduler','kill_switch','build']) engine.observe(observation({ component, state: component === 'scheduler' ? 'disabled' : 'healthy', reasonCode: component === 'scheduler' ? 'unsupported' : 'check_passed' })); const diagnostics = readOperatorDiagnostics({ principal:{}, environment:'disposable-staging', workspaceId:'workspace-a', store, engine, authorize:()=>({allowed:true}) }).body; const chunks = formatOperatorStatus(diagnostics, { maxChunkLength: 200 }); assert.ok(chunks.length >= 1); assert.ok(chunks.every((chunk) => chunk.length <= 200)); assert.match(chunks.join('\n'), /Scheduler: disabled/); });
