import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {prepareOwnedSuccessorGatewayUnit as prepare,installOwnedSuccessorGatewayUnit as install,observeOwnedSuccessorGatewayUnit as observe,readOwnedSuccessorGatewayUnitReceipt as receipt,captureOwnedSuccessorRuntimePhase as phase} from '../packages/buyer-writer/owned-successor-gateway-unit.js';
import {encodeGatewayPreparedState,renderGatewayUnit,GATEWAY_SERVICE} from '../packages/buyer-writer/gateway-installation.js';
import {PARTIAL_RELEASE as P} from '../packages/zola-release/partial-retirement-history.js';
import {hash as journalHash} from '../packages/zola-release/commander-journal.js';
import {publishOwnedConfigurationBytes} from '../packages/zola-release/owned-buyer-configuration-host.js';
const hash=v=>createHash('sha256').update(v).digest('hex'),json=v=>JSON.stringify(v)+'\n';
const template=fs.readFileSync(new URL('../ops/runtime-ownership/blackspire-buyer-writer-gateway.service',import.meta.url),'utf8');
import {createOwnedSuccessorGatewayUnitFixture as fixture} from './owned-successor-gateway-unit-fixture.js';
test('real protected predecessor to successor unit, no old receipt edits; running observer does no effects',async()=>{const f=fixture();try{const before=fs.readFileSync(f.paths.oldState),plan=await prepare(f.input,f.deps);assert.equal(fs.readFileSync(f.paths.unit,'utf8'),f.old);const result=await install(plan);assert.equal(result.status,'OWNED_SUCCESSOR_GATEWAY_UNIT_VERIFIED');assert.equal(fs.readFileSync(f.paths.unit,'utf8'),f.next);assert.deepEqual(fs.readFileSync(f.paths.oldState),before);f.setRunning();assert.deepEqual(await observe(f.input,f.deps),result);assert.deepEqual(f.counts(),{renames:1,reloads:1});await assert.rejects(()=>prepare(f.input,f.deps));}finally{f.close();}});
test('lost rename acknowledgement and reload acknowledgement reconstruct exact retained plan without second rename',async()=>{const f=fixture();try{const publish=f.deps.publish;let once=true;f.deps.publish=(...a)=>{publish(...a);if(once){once=false;throw Error('lost rename ACK');}};const plan=await prepare(f.input,f.deps);await assert.rejects(()=>install(plan));assert.equal(fs.readFileSync(f.paths.unit,'utf8'),f.next);f.setReloadFailure();await assert.rejects(()=>install(plan));const resumed=await prepare(f.input,f.deps);await install(resumed);assert.deepEqual(f.counts(),{renames:1,reloads:1});}finally{f.close();}});
test('foreign live unit or retirement/profile drift rejects without writes or reload',async()=>{for(const kind of ['unit','retirement','profile']){const f=fixture();try{const plan=await prepare(f.input,f.deps);if(kind==='unit')f.put(f.paths.unit,'foreign\n',0o644);if(kind==='retirement')f.put(f.paths.retirement,'{}\n');if(kind==='profile')f.driftProfile();await assert.rejects(()=>install(plan));assert.deepEqual(f.counts(),{renames:0,reloads:0});}finally{f.close();}}});
test('wrong old HELD run, foreign profile, nonstopped host and missing retirement reject preparation',async()=>{for(const kind of ['run','profile','running','retirement']){const f=fixture();try{if(kind==='run')f.deps.held=()=>({version:1,mode:'held',releaseSha:P.releaseSha,runId:f.input.attemptId,apiGeneration:null,workerGeneration:null});if(kind==='profile')f.deps.profileDigest=()=> '0'.repeat(64);if(kind==='running')f.setStopped(false);if(kind==='retirement')f.deps.verifyRetirement=async()=>({});await assert.rejects(()=>prepare(f.input,f.deps));assert.deepEqual(f.counts(),{renames:0,reloads:0});}finally{f.close();}}});

test('postmerge receipt selects completed successor authority and retains all predecessor dependencies',async()=>{const f=fixture();try{const p=await prepare(f.input,f.deps);await install(p);const request={releaseSha:f.input.releaseSha,operationId:f.input.operationId,artifactDigest:'c'.repeat(64)},proof=receipt(request,{paths:f.paths});assert.equal(proof.status,'OWNED_SUCCESSOR_GATEWAY_UNIT_RECEIPT_VERIFIED');assert.equal(proof.installedUnitSha256,hash(f.next));assert.equal(proof.dependencies.length,5);assert.throws(()=>receipt({...request,artifactDigest:'d'.repeat(64)},{paths:f.paths}));const filename=f.paths.root+'/'+f.input.operationId+'/result.json';const value=JSON.parse(fs.readFileSync(filename));value.attemptId=P.attemptId;f.put(filename,json(value));assert.throws(()=>receipt(request,{paths:f.paths}));}finally{f.close();}});
test('unexpected loaded fragment or dropins refuse before unit replacement/reload',async()=>{for(const key of ['FragmentPath','DropInPaths']){const f=fixture();try{const run=f.deps.run;f.deps.run=args=>run(args).replace(key+'='+(key==='FragmentPath'?f.paths.unit:''),key+'=/foreign');const plan=await prepare(f.input,f.deps);await assert.rejects(()=>install(plan));assert.deepEqual(f.counts(),{renames:0,reloads:0});}finally{f.close();}}});

test('completed observation requires stopped sealed phase before pointer switch, then deployed proof only',async()=>{const f=fixture();try{let deployed=false,sealedReads=0,deployedReads=0;f.deps.inspectSealed=async({releaseSha})=>{assert.equal(deployed,false);sealedReads++;return{releaseSha,artifactDigest:'c'.repeat(64),environment:'production',status:'SEALED_ARTIFACT_VERIFIED',deployed:false,productionAccepted:false};};f.deps.inspectDeployed=async({releaseSha})=>{if(releaseSha===f.input.releaseSha){deployedReads++;if(!deployed)throw Error('deployment absent');}return{releaseSha,artifactDigest:'c'.repeat(64),environment:'production'};};const p=await prepare(f.input,f.deps);await install(p);const before=sealedReads;await observe(f.input,f.deps);assert.equal(sealedReads,before+1);assert.equal(deployedReads,0);f.setStopped(false);await assert.rejects(()=>observe(f.input,f.deps));f.setRunning();await assert.rejects(()=>observe(f.input,f.deps));assert.equal(sealedReads,before+1);deployed=true;await observe(f.input,f.deps);assert.equal(sealedReads,before+1);assert.equal(deployedReads,2);assert.deepEqual(f.counts(),{renames:1,reloads:1});}finally{f.close();}});

test('shared classifier accepts exact rollover and deployed-before-pointer interruption without effects',async()=>{const f=fixture();try{const plan=await prepare(f.input,f.deps);await install(plan);assert.equal(phase(f.input,f.deps).sealed,true);f.newHeld();assert.equal(phase(f.input,f.deps).candidate.plan,null);await observe(f.input,f.deps);f.beginCandidate();await observe(f.input,f.deps);f.addRecord();const pending=phase(f.input,f.deps);assert.equal(pending.sealed,false);assert.equal(pending.requiresStopped,true);assert.equal(pending.candidate.pending,'pointer');await observe(f.input,f.deps);f.setRunning();const current=phase(f.input,f.deps);assert.equal(current.sealed,false);assert.equal(current.requiresStopped,false);await observe(f.input,f.deps);assert.deepEqual(f.counts(),{renames:1,reloads:1});}finally{f.close();}});
test('classifier rejects impossible deployment and journal combinations',async()=>{for(const kind of ['old-held-record','new-pointer-no-record','record-no-intent','wrong-plan','unproved-held']){const f=fixture();try{if(kind==='old-held-record')f.addRecord();if(kind==='new-pointer-no-record'){f.beginCandidate();f.switchPointer();}if(kind==='record-no-intent'){f.newHeld();f.addRecord();}if(kind==='wrong-plan'){f.beginCandidate();f.addRecord();f.events[0].profileDigest='d'.repeat(64);}if(kind==='unproved-held'){f.newHeld();f.deps.verifySuccessorHeld=()=>false;}assert.throws(()=>phase(f.input,f.deps));assert.deepEqual(f.counts(),{renames:0,reloads:0});}finally{f.close();}}});
test('observation fences deployment record creation during awaited evidence',async()=>{const f=fixture();try{const plan=await prepare(f.input,f.deps);await install(plan);f.beginCandidate();const inspect=f.deps.inspectSealed;f.deps.inspectSealed=async args=>{f.addRecord();return inspect(args);};await assert.rejects(()=>observe(f.input,f.deps));assert.deepEqual(f.counts(),{renames:1,reloads:1});}finally{f.close();}});
