import test from 'node:test';import assert from 'node:assert/strict';import {createHash,generateKeyPairSync} from 'node:crypto';
import {OWNED_POSTGRES_TARGET,ownedPostgresProfileDigest} from '../packages/buyer-writer/owned-postgres.js';
import {inputFixture} from './helpers/buyer-writer-gateway-v4-preparation.js';
import {buildOwnedSuccessorWriter,buildInheritedOwnedFrontend,createOwnedSuccessorConfiguration,OWNED_CONFIG_PREDECESSOR as previousReleaseSha} from '../packages/zola-release/owned-successor-configuration.js';
const secret=n=>Buffer.alloc(32,n).toString('base64url'),sha='b'.repeat(40),operationId='11111111-1111-4111-8111-111111111111',attemptId='22222222-2222-4222-8222-222222222222';
function fixture(){const source=inputFixture().sourceConfiguration,ca=source.runtime.ca,profile={version:1,...OWNED_POSTGRES_TARGET,creatorOid:source.creatorOid,systemIdentifier:'7000000000000000001',caSha256:createHash('sha256').update(ca).digest('hex')},profileDigest=ownedPostgresProfileDigest(profile);for(const k of ['runtime','issuer'])source[k]={...source[k],host:'127.0.0.1',port:55432,backendProfile:'owned-postgres-v1',profileDigest};
 const authority={releaseSha:previousReleaseSha,operationId:'33333333-3333-4333-8333-333333333333',attemptId:'44444444-4444-4444-8444-444444444444',workspace:source.workspace,gatewayIdentity:'blackspire-writer'},verification={version:2,keys:[{keyId:'retained',publicKeyPem:generateKeyPairSync('ed25519').publicKey.export({type:'spki',format:'pem'}),lifecycle:'current',verifyNotBefore:0,verifyNotAfter:null}]};
 const gateway={...source,version:4,authority,gatewayCapability:secret(8),admissionCredential:secret(9),operationPermitConfiguration:JSON.stringify({issuer:'issuer',audience:'audience',subject:operationId,keyId:'retained',origin:'https://blackspirehelix.com',releaseSha:previousReleaseSha,operationId:authority.operationId,attemptId:authority.attemptId,workspace:source.workspace}),operationPermitVerificationConfiguration:verification,operationPermitSignerConfiguration:{version:1,activeKeyId:'retained',activePrivateKeyPath:'/etc/blackspire/retained.pem',verification}};
 const credentialSource={...source,version:3,authority,gatewayCapability:gateway.gatewayCapability};return{previousReleaseSha,releaseSha:sha,operationId,attemptId,profile,profileDigest,credentialSource,source,gateway,frontendOrigin:'https://successor.vercel.app'};}
test('successor changes authority only while preserving every existing credential and source configuration',()=>{const f=fixture(),next=buildOwnedSuccessorWriter(f);assert.deepEqual(next.source,f.source);for(const k of ['writerCredential','issuerCredential','gatewayCapability','admissionCredential','runtime','issuer','operationPermitSignerConfiguration','operationPermitVerificationConfiguration'])assert.deepEqual(next.gateway[k],f.gateway[k]);assert.equal(next.gateway.authority.releaseSha,sha);assert.equal(JSON.parse(next.gateway.operationPermitConfiguration).operationId,operationId);for(const patch of [{previousReleaseSha:'a'.repeat(40)},{profileDigest:'f'.repeat(64),profile:{...f.profile,creatorOid:99}},{credentialSource:{...f.credentialSource,gatewayCapability:secret(20)}}])assert.throws(()=>buildOwnedSuccessorWriter({...f,...patch}));});
test('partial publication reconciles exact credentials and store plan; rollback never changes data',async()=>{const f=fixture(),input={previousReleaseSha,releaseSha:sha,operationId,attemptId,profileDigest:f.profileDigest,frontendOrigin:f.frontendOrigin};let plan=null,current=f.credentialSource,gateway=null,storePublished=false,interrupt=true;const records=new Map();const evidence={retirement:{previousReleaseSha,releaseSha:sha,digest:'a'.repeat(64)},lineage:{status:'OWNED_MIGRATION_SUCCESSOR_VERIFIED',releaseSha:sha,operationId,profileDigest:f.profileDigest,predecessorReleaseSha:previousReleaseSha,sourceWritesDenied:true,targetBrowserSecurityVerified:true,dataCopied:false,hardeningReapplied:false,lineageDigest:'b'.repeat(64)},previousArtifactDigest:'c'.repeat(64),artifactDigest:'d'.repeat(64)};
 const host={assertStoppedHeld:async()=>{},verifyEvidence:async()=>evidence,readPlan:()=>plan,retainPlan:p=>{if(plan)assert.deepEqual(plan,p);plan=p;},readWriterInputs:()=>({profile:f.profile,source:f.source,credentialSource:f.credentialSource,gateway:f.gateway}),assertSourceUnchanged:v=>assert.deepEqual(v,f.source),publishLiveWriter:()=>{},restoreLiveWriter:()=>{},installWriter:async()=>({status:'INSTALLED_RELOAD_REQUIRED',releaseSha:sha}),record:(p,k,v)=>{if(records.has(k))assert.deepEqual(records.get(k),v);records.set(k,v);},publishCredentialSource:(before,after)=>{assert.ok(JSON.stringify(current)===JSON.stringify(before)||JSON.stringify(current)===JSON.stringify(after));current=after;},publishGatewayCandidate:(s,v)=>{gateway=v;if(interrupt){interrupt=false;throw Error('lost ACK');}}};
 const storePlan={version:1,releaseSha:sha,previousSha:previousReleaseSha,origin:f.frontendOrigin,backendProfile:'owned-postgres-v1',profileDigest:f.profileDigest,retainedDigest:'e'.repeat(64)},store={prepare:async()=>storePlan,publish:async()=>{storePublished=true;},restore:async()=>{storePublished=false;}};
 const helper=createOwnedSuccessorConfiguration({host,store}),p=await helper.prepare(input);await assert.rejects(helper.publish(p));assert.equal(current.authority.releaseSha,sha);assert.equal((await helper.publish(await helper.prepare(input))).status,'OWNED_SUCCESSOR_CONFIGURATION_PREPARED');assert.ok(storePublished);assert.deepEqual(gateway,plan.candidate.gateway);assert.equal((await helper.restore(p)).dataRestored,false);assert.deepEqual(current,f.credentialSource);assert.equal(storePublished,false);
});

test('frontend inheritance preserves prior metadata binding and refuses edited values metadata',()=>{const frontendPlan={releaseSha:previousReleaseSha,synthetic:true},digest=createHash('sha256').update(JSON.stringify(frontendPlan)).digest('hex'),rows=[],results={};for(const scope of ['preview','production'])for(const key of ['BLACKSPIRE_BUYER_STORE_MODE','BLACKSPIRE_BUYER_STORE_URL','BLACKSPIRE_BUYER_DEAL_CONTEXT_KEY']){const name=scope+'-'+key.toLowerCase(),row={id:name,key,target:[scope],type:key.endsWith('_KEY')?'sensitive':'plain',gitBranch:scope==='preview'?'release/zola-production-live':null,comment:'zola-owned-buyer:'+digest+':'+name,updatedAt:1};rows.push(row);results[name]={version:1,planDigest:digest,row};}const input={previousReleaseSha,releaseSha:sha,frontendPlan,rows,results},proof=buildInheritedOwnedFrontend(input);assert.equal(proof.settingsUnchanged,true);assert.equal(proof.frontendPlanDigest,digest);assert.equal(Object.hasOwn(proof,'dealKey'),false);assert.throws(()=>buildInheritedOwnedFrontend({...input,rows:rows.map((r,i)=>i? r:{...r,updatedAt:2})}));assert.throws(()=>buildInheritedOwnedFrontend({...input,frontendPlan:{...frontendPlan,releaseSha:sha}}));});
