import {establishCandidateHeld} from '../packages/zola-release/production-held-operations.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {hash} from '../packages/zola-release/commander-journal.js';
import {PARTIAL_RELEASE as P} from '../packages/zola-release/partial-retirement-history.js';
import {RELEASE_STAGES,runReleaseSequence} from '../packages/zola-release/commander-sequence.js';
import {RELEASE_ADMISSION_LOCK} from '../packages/shared/release-admission.js';
import {rolloverOwnedSuccessorHeld,createOwnedSuccessorHeldHost} from '../packages/zola-release/owned-successor-held.js';
import {publishOwnedConfigurationBytes} from '../packages/zola-release/owned-buyer-configuration-host.js';
const original=JSON.parse(fs.readFileSync(new URL('./fixtures/zola-release/retired-release-2636.json',import.meta.url))),releaseSha='a'.repeat(40),operationId='11111111-1111-4111-8111-111111111111',newRun='22222222-2222-4222-8222-222222222222';
const request={releaseSha,operationId,profileDigest:P.profileDigest,successorLineageFile:`/var/lib/blackspire-operator/owned-migration-successors/${operationId}/plan.json`};
async function fixture(fault){const proof={version:1,runId:P.runId,currentSha:P.releaseSha,hostStopped:true,bindingAbsent:true,retainedEffects:true,n8nJournalDigest:P.n8nJournalDigest,stopPlanDigest:'a'.repeat(64),stopResultDigest:'b'.repeat(64),lineageDigest:'c'.repeat(64)},retired={schema:5,type:'sequence_retired',operationId:P.operationId,releaseSha:P.releaseSha,attemptId:P.attemptId,ordinal:5,stage:'admission_lease',prefixDigest:P.prefixDigest,segmentDigest:P.segmentDigest,successorReleaseSha:releaseSha,successorOperationId:operationId,backendProfile:'owned-postgres-v1',profileDigest:P.profileDigest,proof,proofDigest:hash(proof)},events=[...structuredClone(original),retired],journal={stream:()=>({events:()=>structuredClone(events),append:e=>events.push(structuredClone(e))})};
 const seq={releaseSha,previousMainSha:original[69].previousMainSha,recoverySha:original[69].recoverySha,protectedInputDigest:'d'.repeat(64),workspace:'zola-production',principal:'blackspire-release-root'};seq.inputDigest=hash(seq);const pass=()=>({status:'PASS',evidence:{modeled:true}}),adapters=Object.fromEntries(RELEASE_STAGES.map(s=>[s,{check:pass,observe:pass,reconcile:pass,execute:()=>{if(s==='admission_lease')throw Error('pause before hold');}}]));await runReleaseSequence({input:seq,journal,adapters,requestedOperationId:operationId});
 const root=fs.mkdtempSync('/root/zola-successor-held-test-'),old={version:1,mode:'held',releaseSha:P.releaseSha,runId:P.runId,apiGeneration:null,workerGeneration:null},mark={schema:1,releaseSha:P.releaseSha,runId:P.runId,stateDigest:hash(old)};
 for(const[name,value,mode]of [['state.json',JSON.stringify(old)+'\n',0o640],['pending.json',JSON.stringify(mark)+'\n',0o600],['runtime.env',`BLACKSPIRE_RELEASE_RUN_ID=${P.runId}\n`,0o640],['admission.lock',RELEASE_ADMISSION_LOCK,0o640]])fs.writeFileSync(root+'/'+name,value,{mode});
 const lineage={status:'OWNED_MIGRATION_SUCCESSOR_VERIFIED',releaseSha,operationId,profileDigest:P.profileDigest,predecessorReleaseSha:P.releaseSha,predecessorOperationId:P.operationId,sourceWritesDenied:true,targetBrowserSecurityVerified:true,lineageDigest:'c'.repeat(64)};let stopped=true;
 const host=createOwnedSuccessorHeldHost(request,journal,{root,recordsRoot:root+'/records',verifySource:s=>assert.equal(s,releaseSha),observeLineage:async()=>lineage,current:()=>`/opt/blackspire-command/releases/${P.releaseSha}`,stopped:()=>{if(!stopped)throw Error('service active');},publishBytes:(...args)=>{publishOwnedConfigurationBytes(...args);fault?.(args[0]);}});
 return{root,events,journal,host,lineage,setStopped:v=>stopped=v,run:()=>rolloverOwnedSuccessorHeld({...request,journal},{host,random:()=>newRun}),cleanup:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('actual protected HELD handoff retains prior state and runtime, publishes exact native contract',{skip:process.getuid()!==0},async()=>{const f=await fixture();try{const result=await f.run();assert.equal(result.status,'OWNED_SUCCESSOR_HELD');const state=JSON.parse(fs.readFileSync(f.root+'/state.json')),marker=JSON.parse(fs.readFileSync(f.root+'/pending.json'));assert.equal(state.runId,newRun);assert.equal(marker.stateDigest,hash(state));assert.equal(fs.readFileSync(f.root+'/runtime.env','utf8'),`BLACKSPIRE_RELEASE_RUN_ID=${P.runId}\n`);assert.deepEqual(f.events.slice(0,116),original);const plan=JSON.parse(fs.readFileSync(f.root+'/records/'+operationId+'/plan.json'));assert.equal(JSON.parse(plan.previousState).releaseSha,P.releaseSha);assert.equal((await f.run()).runId,newRun);assert.equal(f.events.filter(e=>e.type==='release_hold_intent'&&e.releaseSha===releaseSha).length,1);}finally{f.cleanup();}});
test('actual interruptions after marker or state rename resume same run without duplicate hold intent',{skip:process.getuid()!==0},async()=>{for(const name of ['pending.json','state.json']){let once=true;const f=await fixture(file=>{if(file.endsWith('/'+name)&&once){once=false;throw Error('lost fsync acknowledgment');}});try{await assert.rejects(f.run());assert.equal(f.events.filter(e=>e.type==='release_hold_result'&&e.releaseSha===releaseSha).length,0);assert.equal((await f.run()).runId,newRun);assert.equal(f.events.filter(e=>e.type==='release_hold_intent'&&e.releaseSha===releaseSha).length,1);}finally{f.cleanup();}}});
test('active service, lineage drift and foreign state refuse without changing protected admission files',{skip:process.getuid()!==0},async()=>{for(const change of [f=>f.setStopped(false),f=>f.lineage.lineageDigest='d'.repeat(64),f=>fs.writeFileSync(f.root+'/state.json',JSON.stringify({version:1,mode:'held',releaseSha:'b'.repeat(40),runId:P.runId,apiGeneration:null,workerGeneration:null})+'\n')]){const f=await fixture();try{change(f);const before=fs.readFileSync(f.root+'/state.json');await assert.rejects(f.run());assert.deepEqual(fs.readFileSync(f.root+'/state.json'),before);assert.equal(f.events.filter(e=>e.type==='release_hold_intent'&&e.releaseSha===releaseSha).length,0);}finally{f.cleanup();}}});

test('schema3 establish composes protected rollover before candidate and new lifecycle manifest',{skip:process.getuid()!==0},async()=>{const f=await fixture();try{const calls=[],context={journal:f.journal,input:{releaseSha,recoverySha:original[69].recoverySha,backendProfile:'owned-postgres-v1',profileDigest:P.profileDigest},release:{schema:3,...request,backendProfile:'owned-postgres-v1'}},proof={api:{generation:'1'.repeat(32)},worker:{generation:'2'.repeat(32)}};const deps={root:f.root,groupId:0,engage:()=>assert.fail('legacy engage forbidden'),reconcile:()=>assert.fail('legacy reconcile forbidden'),successorHold:async()=>{calls.push('hold');return f.run();},prepare:async input=>{calls.push('candidate');assert.equal(input.releaseSha,releaseSha);assert.equal(JSON.parse(fs.readFileSync(f.root+'/state.json')).runId,newRun);},lifecycle:async()=>{calls.push('lifecycle');return{status:'HELD_LIFECYCLE_OBSERVED',releaseSha,runId:newRun,proof};},ownedStore:async()=>({publishManifest:async binding=>{calls.push('manifest');assert.equal(binding.runId,newRun);assert.equal(binding.apiGeneration,proof.api.generation);},start:async()=>calls.push('store')})};assert.equal((await establishCandidateHeld(context,deps)).runId,newRun);assert.deepEqual(calls,['hold','candidate','lifecycle','manifest','store']);calls.length=0;await establishCandidateHeld(context,deps);assert.deepEqual(calls,['candidate','lifecycle','manifest','store']);}finally{f.cleanup();}});
test('actual retained plan survives lost acknowledgment before hold intent',{skip:process.getuid()!==0},async()=>{const f=await fixture();try{const retain=f.host.retainPlan;let once=true;f.host.retainPlan=p=>{retain(p);if(once){once=false;throw Error('plan sync acknowledgment lost');}};await assert.rejects(f.run());assert.equal(f.events.filter(e=>e.type==='release_hold_intent'&&e.releaseSha===releaseSha).length,0);const retained=JSON.parse(fs.readFileSync(f.root+'/records/'+operationId+'/plan.json'));assert.equal((await f.run()).runId,retained.runId);}finally{f.cleanup();}});
