import test from 'node:test';import assert from 'node:assert/strict';
import {expired5Fixture} from './helpers/owned-n8n-cloud-expired5-fixture.js';
import {validateExpired5OwnedN8nAttempt,validateExpired5OwnedN8nRetirement,retireExpired5OwnedN8nAttempt} from '../packages/zola-release/owned-n8n-cloud-expired5.js';
test('exact expired READY records classify without positive possession',()=>{const f=expired5Fixture(),before=JSON.stringify(f.records),r=validateExpired5OwnedN8nAttempt(f.records);assert.equal(r.classification,'EXPIRED_WITH_ZERO_EXECUTIONS');assert.equal(r.positiveProof,false);assert.equal(JSON.stringify(f.records),before);});
test('zero-execution retirement retains original records and deletes exact inactive workflow once',async()=>{const f=expired5Fixture(),before=JSON.stringify(f.records),r=await retireExpired5OwnedN8nAttempt(f.records,f);assert.equal(r.classification,'EXPIRED_WITH_ZERO_EXECUTIONS');assert.equal(r.zeroExecutions,true);assert.equal(r.positiveProof,false);assert.equal(r.originalOutcome,'UNKNOWN');assert.equal(r.administrativeReassertionStatus,405);assert.equal(JSON.stringify(f.records),before);assert.deepEqual(validateExpired5OwnedN8nRetirement(f.records,{observation:f.rows.get('observation'),intent:f.rows.get('intent'),result:r}),r);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('lost DELETE acknowledgment reconciles only404 and zero executions without redispatch',async()=>{const f=expired5Fixture();f.setUnknownDelete();await assert.rejects(retireExpired5OwnedN8nAttempt(f.records,f));const count=f.calls.length;await retireExpired5OwnedN8nAttempt(f.records,f);assert.deepEqual(f.calls.slice(count).map(c=>c.method),['GET','GET']);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('missing READY, either receipt, missing cleanup, changed invocation or graph refuses before effects',async()=>{for(const mutate of [f=>f.records['server-ready']=null,f=>f.records['server-receipt']={},f=>f.records['server-rejection']={},f=>f.records['cleanup-result']=null,f=>f.records['proxy-result']=null,f=>f.records['supervisor-result'].supervisor.invocationId='0'.repeat(32),f=>f.records['workflow-created'].workflow.nodes[1].parameters.url='https://foreign.invalid']){const f=expired5Fixture();mutate(f);await assert.rejects(retireExpired5OwnedN8nAttempt(f.records,f));assert.equal(f.calls.length,0);}});
test('pagination, executions, listeners and exit outside window deny deletion',async()=>{for(const mutate of [f=>f.executionInventory.body.data=[{id:'unexpected'}],f=>f.executionInventory.body.nextCursor='more',f=>f.local.listenerAbsent=false,f=>f.local.temporaryAbsent=false,f=>f.local.proxy+='changed',f=>f.local.supervisorExitedAt='2026-09-22T13:05:00.000Z']){const f=expired5Fixture();mutate(f);await assert.rejects(retireExpired5OwnedN8nAttempt(f.records,f));assert.equal(f.calls.some(c=>c.method==='DELETE'),false);}});
test('retained observation drift denies completion without another deletion',async()=>{const f=expired5Fixture();await retireExpired5OwnedN8nAttempt(f.records,f);f.rows.get('observation').executionInventory.data.push({id:'extra'});await assert.rejects(retireExpired5OwnedN8nAttempt(f.records,f));assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
