import {verifyOwnedSuccessorWriterPublication} from '../packages/zola-release/owned-successor-configuration-host.js';
import test from 'node:test';import assert from 'node:assert/strict';import {createHash,generateKeyPairSync} from 'node:crypto';
import {OWNED_POSTGRES_TARGET,ownedPostgresProfileDigest} from '../packages/buyer-writer/owned-postgres.js';
import {inputFixture} from './helpers/buyer-writer-gateway-v4-preparation.js';
import {buildOwnedSuccessorWriter,buildInheritedOwnedFrontend,createOwnedSuccessorConfiguration,OWNED_CONFIG_PREDECESSOR as previousReleaseSha} from '../packages/zola-release/owned-successor-configuration.js';
const secret=n=>Buffer.alloc(32,n).toString('base64url'),sha='b'.repeat(40),operationId='11111111-1111-4111-8111-111111111111',attemptId='22222222-2222-4222-8222-222222222222';
function fixture(){const source=inputFixture().sourceConfiguration,ca=source.runtime.ca,profile={version:1,...OWNED_POSTGRES_TARGET,creatorOid:source.creatorOid,systemIdentifier:'7000000000000000001',caSha256:createHash('sha256').update(ca).digest('hex')},profileDigest=ownedPostgresProfileDigest(profile);for(const k of ['runtime','issuer'])source[k]={...source[k],host:'127.0.0.1',port:55432,backendProfile:'owned-postgres-v1',profileDigest};
 const authority={releaseSha:previousReleaseSha,operationId:'33333333-3333-4333-8333-333333333333',attemptId:'44444444-4444-4444-8444-444444444444',workspace:source.workspace,gatewayIdentity:'blackspire-writer'},verification={version:2,keys:[{keyId:'retained',publicKeyPem:generateKeyPairSync('ed25519').publicKey.export({type:'spki',format:'pem'}),lifecycle:'current',verifyNotBefore:0,verifyNotAfter:null}]};
 const gateway={...source,version:4,authority,gatewayCapability:secret(8),admissionCredential:secret(9),operationPermitConfiguration:JSON.stringify({issuer:'issuer',audience:'audience',subject:operationId,keyId:'retained',origin:'https://blackspirehelix.com',releaseSha:previousReleaseSha,operationId:authority.operationId,attemptId:authority.attemptId,workspace:source.workspace}),operationPermitVerificationConfiguration:verification,operationPermitSignerConfiguration:{version:1,activeKeyId:'retained',activePrivateKeyPath:'/etc/blackspire/retained.pem',verification}};
 const credentialSource={...source,version:3,authority,gatewayCapability:gateway.gatewayCapability};return{previousReleaseSha,releaseSha:sha,operationId,attemptId,profile,profileDigest,credentialSource,source,gateway,frontendOrigin:'https://successor.vercel.app'};}
test('successor changes authority only while preserving every existing credential and source configuration',()=>{const f=fixture(),next=buildOwnedSuccessorWriter(f);assert.deepEqual(next.source,f.source);for(const k of ['writerCredential','issuerCredential','gatewayCapability','admissionCredential','runtime','issuer','operationPermitSignerConfiguration','operationPermitVerificationConfiguration'])assert.deepEqual(next.gateway[k],f.gateway[k]);assert.equal(next.gateway.authority.releaseSha,sha);assert.equal(JSON.parse(next.gateway.operationPermitConfiguration).operationId,operationId);for(const patch of [{previousReleaseSha:'a'.repeat(40)},{profileDigest:'f'.repeat(64),profile:{...f.profile,creatorOid:99}},{credentialSource:{...f.credentialSource,gatewayCapability:secret(20)}}])assert.throws(()=>buildOwnedSuccessorWriter({...f,...patch}));});
test('partial publication reconciles exact credentials and store plan; rollback never changes data',async()=>{const f=fixture(),input={previousReleaseSha,releaseSha:sha,operationId,attemptId,profileDigest:f.profileDigest,frontendOrigin:f.frontendOrigin};let plan=null,current=f.credentialSource,gateway=null,storePublished=false,interrupt=true;const records=new Map();const evidence={retirement:{previousReleaseSha,releaseSha:sha,digest:'a'.repeat(64)},lineage:{status:'OWNED_MIGRATION_SUCCESSOR_VERIFIED',releaseSha:sha,operationId,profileDigest:f.profileDigest,predecessorReleaseSha:previousReleaseSha,sourceWritesDenied:true,targetBrowserSecurityVerified:true,dataCopied:false,hardeningReapplied:false,lineageDigest:'b'.repeat(64)},previousArtifactDigest:'c'.repeat(64),artifactDigest:'d'.repeat(64)};
 const host={assertStoppedHeld:async()=>{},verifyEvidence:async()=>evidence,readPlan:()=>plan,readFinalPlan:()=>plan,readRecord:(s,k)=>records.get(k)??null,observeWriter:()=>{assert.equal(current.authority.releaseSha,sha);},retainPlan:p=>{if(plan)assert.deepEqual(plan,p);plan=p;},readWriterInputs:()=>({profile:f.profile,source:f.source,credentialSource:f.credentialSource,gateway:f.gateway}),assertSourceUnchanged:v=>assert.deepEqual(v,f.source),publishLiveWriter:()=>{},restoreLiveWriter:()=>{},installWriter:async()=>({status:'INSTALLED_RELOAD_REQUIRED',releaseSha:sha}),record:(p,k,v)=>{if(records.has(k))assert.deepEqual(records.get(k),v);records.set(k,v);},publishCredentialSource:(before,after)=>{assert.ok(JSON.stringify(current)===JSON.stringify(before)||JSON.stringify(current)===JSON.stringify(after));current=after;},publishGatewayCandidate:(s,v)=>{gateway=v;if(interrupt){interrupt=false;throw Error('lost ACK');}}};
 const storePlan={version:1,releaseSha:sha,previousSha:previousReleaseSha,origin:f.frontendOrigin,backendProfile:'owned-postgres-v1',profileDigest:f.profileDigest,retainedDigest:'e'.repeat(64)},store={prepare:async()=>storePlan,publish:async()=>{storePublished=true;},observe:()=>storePublished,restore:async()=>{storePublished=false;}};
 const helper=createOwnedSuccessorConfiguration({host,store}),p=await helper.prepare(input);await assert.rejects(helper.restore(p));await assert.rejects(helper.observe(p));await assert.rejects(helper.publish(p));assert.equal(current.authority.releaseSha,sha);assert.equal((await helper.publish(await helper.prepare(input))).status,'OWNED_SUCCESSOR_CONFIGURATION_PREPARED');assert.ok(storePublished);assert.deepEqual(gateway,plan.candidate.gateway);const stopped=host.assertStoppedHeld;host.assertStoppedHeld=()=>{throw Error('running');};assert.equal((await helper.observe(p)).status,'OWNED_SUCCESSOR_CONFIGURATION_PREPARED');current=f.credentialSource;await assert.rejects(helper.observe(p));current=plan.candidate.credentialSource;host.assertStoppedHeld=stopped;const restore=store.restore;store.restore=async()=>{throw Error('restore interrupted');};await assert.rejects(helper.restore(p));const retained=JSON.stringify([...records]);await assert.rejects(helper.prepare(input));await assert.rejects(helper.publish(p));await assert.rejects(helper.observe(p));assert.equal(JSON.stringify([...records]),retained);assert.equal(current.authority.releaseSha,sha);store.restore=restore;assert.equal((await helper.restore(p)).dataRestored,false);assert.deepEqual(current,f.credentialSource);assert.equal(storePublished,false);await assert.rejects(helper.prepare(input));await assert.rejects(helper.publish(p));await assert.rejects(helper.observe(p));assert.equal((await helper.restore(p)).dataRestored,false);
});

test('frontend inheritance preserves prior metadata binding and refuses edited values metadata',()=>{const frontendPlan={releaseSha:previousReleaseSha,synthetic:true},digest=createHash('sha256').update(JSON.stringify(frontendPlan)).digest('hex'),rows=[],results={};for(const scope of ['preview','production'])for(const key of ['BLACKSPIRE_BUYER_STORE_MODE','BLACKSPIRE_BUYER_STORE_URL','BLACKSPIRE_BUYER_DEAL_CONTEXT_KEY']){const name=scope+'-'+key.toLowerCase(),row={id:name,key,target:[scope],type:key.endsWith('_KEY')?'sensitive':'plain',gitBranch:scope==='preview'?'release/zola-production-live':null,comment:'zola-owned-buyer:'+digest+':'+name,updatedAt:1};rows.push(row);results[name]={version:1,planDigest:digest,row};}const input={previousReleaseSha,releaseSha:sha,frontendPlan,rows,results},proof=buildInheritedOwnedFrontend(input);assert.equal(proof.settingsUnchanged,true);assert.equal(proof.frontendPlanDigest,digest);assert.equal(Object.hasOwn(proof,'dealKey'),false);assert.throws(()=>buildInheritedOwnedFrontend({...input,rows:rows.map((r,i)=>i? r:{...r,updatedAt:2})}));assert.throws(()=>buildInheritedOwnedFrontend({...input,frontendPlan:{...frontendPlan,releaseSha:sha}}));});

test('running publication observer binds every installed byte and protected mode without writes',()=>{
 const f=fixture(),candidate=buildOwnedSuccessorWriter(f),plan={input:f,before:{source:f.source,live:{gatewayGid:982}},candidate,evidence:{artifactDigest:'d'.repeat(64)}};
 const files=new Map(),encode=v=>JSON.stringify(v)+'\n',digest=v=>createHash('sha256').update(v).digest('hex'),put=(p,v,o={})=>files.set(p,{value:v,options:o});
 const prep='/var/lib/blackspire-operator/preparation';put(prep+'/owned-source-v1.json',encode(f.source));put(prep+'/owned-gateway-provisioning.json',encode(candidate.credentialSource));put(prep+'/owned-buyer-writer-v4-'+sha+'.json',encode(candidate.gateway));
 const manifest={schema:1,kind:'zola_installed_buyer_writer',releaseSha:sha,artifactDigest:plan.evidence.artifactDigest,workspace:'blackspire-command'},paths={};
 for(const kind of ['client','ingress','signer']){const value=encode(candidate.rendered[kind+'Config']),p='/etc/blackspire/buyer-writer-'+kind+'-'+digest(value)+'.json';put(p,value,{gid:984,mode:0o640});paths[kind]=p;manifest[kind+'Config']={path:p,digest:digest(value)};}
 const gateway=encode(candidate.rendered.gatewayConfig),gp='/etc/blackspire-buyer-writer-gateway/gateway.json',dp='/etc/systemd/system/blackspire-command.service.d/40-zola-writer.conf',dropin='[Service]\nEnvironment=BUYER_WRITER_MODE=scoped\nEnvironment=BUYER_WRITER_WORKSPACE_ID=blackspire-command\nEnvironment=BLACKSPIRE_BUYER_WRITER_CLIENT_CONFIG='+paths.client+'\nEnvironment=BLACKSPIRE_BUYER_WRITER_INGRESS_CONFIG='+paths.ingress+'\nEnvironment=BLACKSPIRE_BUYER_WRITER_SIGNER_CONFIG='+paths.signer+'\n';
 put(gp,gateway,{gid:982,mode:0o640});put(dp,dropin,{mode:0o644});manifest.gatewayConfig={path:gp,digest:digest(gateway)};manifest.serviceDropin={path:dp,digest:digest(dropin)};
 const mp='/etc/blackspire/zola-installed-'+sha+'.json';put(mp,encode(manifest));put('/var/lib/blackspire-operator/owned-successor-configuration/'+sha+'.json.configuration_install_verified.json',encode({event:'configuration_install_verified',releaseSha:sha,manifestPath:mp,manifestDigest:digest(encode(manifest))}));
 const read=(p,o={})=>{const row=files.get(p);assert.deepEqual(o,row.options);return row.value;};assert.equal(verifyOwnedSuccessorWriterPublication(plan,{credentialGroupId:984,read}),true);
 for(const [p,row] of files){files.set(p,{...row,value:row.value+' '});assert.throws(()=>verifyOwnedSuccessorWriterPublication(plan,{credentialGroupId:984,read}));files.set(p,row);}
});

test('mixed successor preserves credentials while binding only the repaired current-runtime pair',async()=>{
 const {MIXED_RETIREMENT:P}=await import('../packages/zola-release/mixed-retirement-history.js');
 const f=fixture();f.previousReleaseSha=P.releaseSha;f.releaseSha=P.successorReleaseSha;f.operationId=P.successorOperationId;
 for(const v of [f.credentialSource,f.gateway])v.authority={...v.authority,releaseSha:P.releaseSha,operationId:P.operationId};
 f.gateway.operationPermitConfiguration=JSON.stringify({...JSON.parse(f.gateway.operationPermitConfiguration),releaseSha:P.releaseSha,operationId:P.operationId});
 const next=buildOwnedSuccessorWriter(f);
 assert.deepEqual(next.source,f.source);
 for(const k of ['writerCredential','issuerCredential','gatewayCapability','admissionCredential','runtime','issuer','operationPermitSignerConfiguration','operationPermitVerificationConfiguration'])assert.deepEqual(next.gateway[k],f.gateway[k]);
 assert.equal(next.gateway.authority.releaseSha,P.successorReleaseSha);
 assert.equal(next.gateway.authority.operationId,P.successorOperationId);
 for(const patch of [{previousReleaseSha},{releaseSha:'c'.repeat(40)},{gateway:{...f.gateway,authority:{...f.gateway.authority,releaseSha:previousReleaseSha}}}])assert.throws(()=>buildOwnedSuccessorWriter({...f,...patch}));
});
