import test from 'node:test';import assert from 'node:assert/strict';import {ORIGINAL_N8N_OPERATOR_SHA,assertOwnedN8nRecoveryAuthority,createOwnedN8nRecoveryContinuation} from '../packages/zola-release/owned-n8n-recovery-authority.js';
const expected={version:1,operatorSha:'a'.repeat(40),releaseSha:'a8e05ef40e44b6695df5b30356af0e411fe36f1a',operationId:'c8b00904-7017-434a-918e-8aaadbae82fd',stageAttemptId:'f163d812-3711-471b-863a-038e85d59137',sourceDigest:'b'.repeat(64),held:{exact:true}},original={...expected,operatorSha:ORIGINAL_N8N_OPERATOR_SHA};
test('old authority retained while current code is independently pinned',()=>{assert.equal(assertOwnedN8nRecoveryAuthority({original,expected,currentOperatorSha:expected.operatorSha}),original);assert.equal(original.operatorSha,ORIGINAL_N8N_OPERATOR_SHA)});
test('changed source, operation, held evidence or relabeled original authority refuses',()=>{for(const value of [{...original,sourceDigest:'c'.repeat(64)},{...original,operationId:'0'.repeat(36)},{...original,held:{exact:false}},{...original,operatorSha:expected.operatorSha}])assert.throws(()=>assertOwnedN8nRecoveryAuthority({original:value,expected,currentOperatorSha:expected.operatorSha}));});

test('both continuation callbacks require separate proof and observe metadata without mutation',async()=>{let checks=0,reads=0;const proof={after:{id:'fixed',updatedAt:'same'}},c=createOwnedN8nRecoveryContinuation({withFence:async(b,fn)=>fn(async()=>{checks++}),proof:()=>proof,metadata:async()=>{reads++;return proof.after}});await c.synchronize({});await c.assertConfigured({});assert.equal(checks,2);assert.equal(reads,2);});
test('unknown original intent alone and changed metadata refuse continuation',async()=>{for(const proof of [()=>{throw Error('no separate proof')},()=>({after:{id:'expected'}})]){const c=createOwnedN8nRecoveryContinuation({withFence:async(b,fn)=>fn(async()=>{}),proof,metadata:async()=>({id:'changed'})});await assert.rejects(c.synchronize({}));await assert.rejects(c.assertConfigured({}));}});

test('received status survives interrupted or malformed body without claiming acknowledgment',async()=>{const {retainOwnedN8nResponse}=await import('../packages/zola-release/owned-n8n-response-receipt.js');const records=new Map(),store={record:(k,v)=>records.set(k,v)};const response={status:200,body:{async *[Symbol.asyncIterator](){yield Buffer.from('{');throw Error('timeout')}}};await assert.rejects(retainOwnedN8nResponse(response,{store,bodyDigest:'a'.repeat(64),operatorSha:'b'.repeat(40)}));assert.equal(records.get('transport-headers').status,200);assert.equal(records.get('transport-body').complete,false);assert.equal(records.has('http-ack'),false);});
