import {buildOwnedN8nCloudWorkflow,cloudProofDigest} from '../packages/zola-release/owned-n8n-cloud-workflow.js';
import {createOwnedN8nRequestGate} from '../packages/zola-release/owned-n8n-request-gate.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {validateOwnedN8nCloudHistory,createOwnedN8nCloudContinuation,assertOwnedN8nCloudContinuationOperator} from '../packages/zola-release/owned-n8n-cloud-continuation.js';
import {n8nReassertionDigest as hash,ownedN8nReassertionBody} from '../packages/zola-release/owned-n8n-credential-reassertion.js';
function fixture(){
 const fixed={releaseSha:'a8e05ef40e44b6695df5b30356af0e411fe36f1a',operationId:'c8b00904-7017-434a-918e-8aaadbae82fd',stageAttemptId:'f163d812-3711-471b-863a-038e85d59137'},authority={...fixed,operatorSha:'5c7cc20350025db8339d8210a496a78cb51f6af4',sourceDigest:'a'.repeat(64),profileDigest:'b'.repeat(64),namespace:'fixed'},source={authority:fixed,writerCredential:'z'.repeat(43)},originalIntent={binding:{releaseSha:fixed.releaseSha,sourceDigest:authority.sourceDigest,profileDigest:authority.profileDigest,namespace:authority.namespace,credentialId:'RzOyDmXYmx58yZHi'},before:{id:'RzOyDmXYmx58yZHi'}};
 const binding={version:1,...fixed,credentialId:'RzOyDmXYmx58yZHi',operatorSha:'567b7acbdf16b4e784d235e97709e4fec2adb157',authorityDigest:hash(authority),originalIntentDigest:hash(originalIntent),sourceDigest:authority.sourceDigest,bodyDigest:hash(ownedN8nReassertionBody(source))};
 const intent={version:1,kind:'owned-n8n-credential-reassertion-intent',binding,before:originalIntent.before,closure:{digest:'c'.repeat(64)}},httpAck={version:1,bindingDigest:hash(binding),status:405,responseDigest:hash({message:'Method Not Allowed'}),after:null},headers={version:1,status:405,method:'PATCH',credentialId:binding.credentialId,bodyDigest:binding.bodyDigest,operatorSha:binding.operatorSha},body={version:1,status:405,complete:true,bytes:32,rawDigest:'d'.repeat(64),responseDigest:httpAck.responseDigest};
 const plan={...fixed,authorityDigest:hash(authority),originalIntentDigest:hash(originalIntent),reassertionIntentDigest:hash(intent),reassertionAckDigest:hash(httpAck),reassertionHeadersDigest:hash(headers),reassertionBodyDigest:hash(body),sourceDigest:authority.sourceDigest,profileDigest:authority.profileDigest};
 return {authority,source,originalIntent,originalResult:null,reassertion:{intent,httpAck,result:null,headers,body},plan};
}
test('cloud history preserves original UNKNOWN and separate authenticated405 without writes',()=>{const f=fixture(),before=JSON.stringify(f),proof=validateOwnedN8nCloudHistory(f);assert.equal(proof.originalOutcome,'UNKNOWN');assert.equal(proof.administrativeReassertionStatus,405);assert.equal(JSON.stringify(f),before);assert.equal(JSON.stringify(proof).includes(f.source.writerCredential),false);});
test('foreign source, authority, incomplete405, fabricated results and plan drift refuse',()=>{for(const mutate of [f=>f.originalResult={},f=>f.reassertion.result={},f=>f.reassertion.httpAck.status=200,f=>f.reassertion.body.complete=false,f=>f.reassertion.body.responseDigest='e'.repeat(64),f=>f.authority.stageAttemptId='bad',f=>f.plan.sourceDigest='e'.repeat(64),f=>f.plan.reassertionHeadersDigest='e'.repeat(64),f=>f.plan.reassertionBodyDigest='e'.repeat(64),f=>f.source.writerCredential='q'.repeat(43),f=>f.reassertion.headers.operatorSha='e'.repeat(40)]){const f=fixture();mutate(f);assert.throws(()=>validateOwnedN8nCloudHistory(f));}});
function continuation(){const value={after:{id:'credential',updatedAt:'fixed'},initialClosure:{digest:'baseline'},receiptDigest:'a'.repeat(64)};let snapshot=value,metadata=value.after,closure={status:'VERIFIED',digest:'c'.repeat(64)},fences=0,reads=0;const deps={withFence:async(b,fn)=>fn(async()=>{fences++;}),proof:async()=>{reads++;return structuredClone(snapshot);},metadata:async()=>structuredClone(metadata),closure:async()=>structuredClone(closure)};return {deps,value,setProof:v=>snapshot=v,setMetadata:v=>metadata=v,setClosure:v=>closure=v,fences:()=>fences,reads:()=>reads};}
test('both callbacks require finalized proof and fresh metadata/closure under continuous fence',async()=>{const f=continuation(),adapter=createOwnedN8nCloudContinuation(f.deps);await adapter.synchronize({});await adapter.assertConfigured({});assert.equal(f.reads(),4);assert.equal(f.fences(),8);});
test('missing cleanup proof, metadata drift and changing retained receipt deny continuation',async()=>{for(const mode of ['cleanup','metadata','receipt','closure']){const f=continuation();if(mode==='cleanup')f.deps.proof=async()=>{throw Error('cleanup incomplete');};if(mode==='metadata')f.setMetadata({id:'credential',updatedAt:'changed'});if(mode==='receipt'){let n=0;f.deps.proof=async()=>({...f.value,receiptDigest:++n===1?'a'.repeat(64):'b'.repeat(64)});}if(mode==='closure'){let n=0;f.deps.closure=async()=>({digest:String(++n)});}await assert.rejects(createOwnedN8nCloudContinuation(f.deps).synchronize({}));}});

test('actual workflow gate cannot forward update without completed possession cleanup',async()=>{const f=continuation(),binding={namespace:'fixed',releaseSha:'a8e05ef40e44b6695df5b30356af0e411fe36f1a',operationId:'c8b00904-7017-434a-918e-8aaadbae82fd',stageAttemptId:'f163d812-3711-471b-863a-038e85d59137'},events=[{...binding,type:'confirmed',operation:'deactivate',state:{kind:'BASELINE',active:false}}],calls=[];let complete=false;f.deps.proof=async()=>{if(!complete)throw Error('cleanup missing');return f.value;};const callbacks=createOwnedN8nCloudContinuation(f.deps),gate=createOwnedN8nRequestGate({...callbacks,binding:()=>binding,events:()=>events,workflowId:'VvMHSIbycYCx4CZN',request:async method=>{calls.push(method);return {};}});await assert.rejects(gate('GET','/api/v1/workflows/VvMHSIbycYCx4CZN'));assert.deepEqual(calls,[]);complete=true;await gate('GET','/api/v1/workflows/VvMHSIbycYCx4CZN');events.push({...binding,type:'intent',operation:'update'});await gate('PUT','/api/v1/workflows/VvMHSIbycYCx4CZN',{});assert.deepEqual(calls,['GET','PUT']);complete=false;await assert.rejects(gate('POST','/api/v1/workflows/VvMHSIbycYCx4CZN/activate'));assert.deepEqual(calls,['GET','PUT']);});

function adoptionFixture(){const plan={...fixture().plan,version:1,kind:'owned-n8n-cloud-proof-plan',operatorSha:'4a1a329a35e10691af2eadbf4088c8bb306d505f',credentialId:'RzOyDmXYmx58yZHi',challenge:'c'.repeat(64),receiptId:'11111111-1111-4111-8111-111111111111',origin:'https://jarvis.blackspirehelix.com',path:'/__zola_credential_proof/'+'c'.repeat(64),createdAt:'2026-09-21T20:00:00.000Z',expiresAt:'2026-09-21T20:15:00.000Z',ingressDigest:'d'.repeat(64),proxyBeforeDigest:'d'.repeat(64),proxyCandidateDigest:'d'.repeat(64)},currentOperatorSha='e'.repeat(40),workflow={id:'JjlvgzqIgFQSWOM7',versionId:'observed-version',...buildOwnedN8nCloudWorkflow(plan),active:false},workflowCreated={version:1,planDigest:cloudProofDigest(plan),workflow},adoption={version:1,kind:'owned-n8n-cloud-workflow-adoption',planDigest:cloudProofDigest(plan),originOperatorSha:plan.operatorSha,repairOperatorSha:currentOperatorSha,workflowDigest:cloudProofDigest(workflow),workflowId:workflow.id,workflowVersionId:workflow.versionId,creationOutcome:'OBSERVED_EXISTING',postRepeated:false};return {plan,currentOperatorSha,workflowCreated,adoption};}
test('exact GET-adoption provenance permits repaired reader while original plan remains immutable',()=>{const f=adoptionFixture(),before=JSON.stringify(f);assert.equal(assertOwnedN8nCloudContinuationOperator(f),true);assert.equal(JSON.stringify(f),before);});
test('missing adoption, foreign operator/workflow/plan and claimed repeated creation reject',()=>{for(const mutate of [f=>f.adoption=null,f=>f.currentOperatorSha='f'.repeat(40),f=>f.plan.operatorSha='f'.repeat(40),f=>f.workflowCreated.workflow.id='Foreign',f=>f.adoption.planDigest='f'.repeat(64),f=>f.adoption.postRepeated=true,f=>f.adoption.creationOutcome='CREATED']){const f=adoptionFixture();mutate(f);assert.throws(()=>assertOwnedN8nCloudContinuationOperator(f));}});
