import test from 'node:test';import assert from 'node:assert/strict';
import {prepareOwnedSuccessorFinalInputs} from '../packages/zola-release/owned-successor-final-inputs.js';
const sha='a'.repeat(40),op='11111111-1111-4111-8111-111111111111';
function fixture(){const records=new Map(),effects=[],snapshot={profile:'fixed',held:'original',artifact:'new'};let generated=0;const host={snapshot:async()=>structuredClone(snapshot),read:n=>records.get(n)??null,publish(n,v){if(records.has(n))assert.deepEqual(records.get(n),v);records.set(n,structuredClone(v));},async execute(stage,plan,results){effects.push(stage);assert.equal(plan.operationId,op);if(stage==='input')return {productionInputFile:'/fixed/new-input.json',successorLineageFile:'/fixed/'+op+'/plan.json'};return{stage};},async verify(stage,plan,results,value){if(stage!=='input')assert.equal(value.stage,stage);}};return{host,records,effects,snapshot,generateOperationId:()=>{generated++;return op;},generated:()=>generated};}
test('one retained operation spans preparation and read-only preflight without lineage or preview dependency',async()=>{const f=fixture();const r=await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);assert.equal(r.operationId,op);assert.equal(r.lineageRequired,true);assert.equal(r.activationReady,false);assert.deepEqual(f.effects,['workflow','bundle','backup','input']);const writes=f.host.publish;f.host.publish=()=>assert.fail('inspect wrote');assert.equal((await prepareOwnedSuccessorFinalInputs({releaseSha:sha,inspect:true},f)).status,'OWNED_SUCCESSOR_FINAL_INPUTS_VERIFIED');f.host.publish=writes;await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);assert.equal(f.generated(),1);assert.equal(f.effects.length,4);});
test('unknown backup result preserves intent and refuses a second online capture',async()=>{const f=fixture(),execute=f.host.execute;f.host.execute=async(...args)=>{const v=await execute(...args);if(args[0]==='backup')throw Error('lost backup ACK');return v;};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));f.host.execute=execute;await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));assert.equal(f.effects.filter(x=>x==='backup').length,1);assert.equal(f.generated(),1);});
test('profile, source or HELD witness drift refuses resumed effects',async()=>{const f=fixture();await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);f.snapshot.held='changed';await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));assert.equal(f.effects.length,4);});
test('missing predecessor/new operation and contradictory result bindings refuse',async()=>{let f=fixture();await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha,inspect:true},f));assert.equal(f.generated(),0);await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:'2636a1e75cd0f422aff036dfee8a93a81cd5008b'},f));f=fixture();await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},{...f,generateOperationId:()=> '95a11ea1-289f-46a9-b5cd-cc7805497242'}));assert.equal(f.records.size,0);f=fixture();await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);f.records.get('backup.result.json').planDigest='bad';await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));});
test('snapshot drift after an effect leaves its intent and prevents later effects',async()=>{const f=fixture(),execute=f.host.execute;f.host.execute=async(...args)=>{const v=await execute(...args);f.snapshot.profile='drift';return v;};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));assert.deepEqual(f.effects,['workflow']);assert.equal(f.records.has('workflow.result.json'),false);});
test('failed retained artifact/backup observation cannot pass preflight',async()=>{const f=fixture();await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);f.host.verify=async stage=>{if(stage==='backup')throw Error('invalid backup');};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha,inspect:true},f));assert.equal(f.effects.length,4);});

test('lost bundle/input acknowledgment adopts only verified known outputs without repeating effects',async()=>{for(const lost of ['bundle','input']){const f=fixture(),execute=f.host.execute;let retained;f.host.execute=async(...args)=>{const value=await execute(...args);if(args[0]===lost){retained=value;throw Error('lost result');}return value;};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));f.host.execute=execute;let observations=0;f.host.reconcile=async stage=>{assert.equal(stage,lost);observations++;return retained;};await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);assert.equal(observations,1);assert.equal(f.effects.filter(s=>s===lost).length,1);assert.equal(f.generated(),1);}});
test('partial deterministic output remains blocked without redispatch',async()=>{const f=fixture(),execute=f.host.execute;f.host.execute=async(...args)=>{const value=await execute(...args);if(args[0]==='bundle')throw Error('partial');return value;};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));f.host.reconcile=async()=>{throw Error('missing file');};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));assert.equal(f.effects.filter(s=>s==='bundle').length,1);});

test('actual deterministic output files synchronize without rewriting and reject partial/foreign files',async()=>{const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path');const {synchronizeKnownSuccessorOutputs}=await import('../packages/zola-release/owned-successor-final-inputs-host.js');const root=fs.mkdtempSync(path.join(os.tmpdir(),'successor-output-adoption-'));try{const files=[path.join(root,'input.json'),path.join(root,'disk.json')];for(const p of files)fs.writeFileSync(p,'exact\n',{mode:0o600});const inodes=files.map(p=>fs.statSync(p).ino);let observations=0;const verify=()=>{observations++;for(const p of files)assert.equal(fs.readFileSync(p,'utf8'),'exact\n');};await synchronizeKnownSuccessorOutputs(files,verify);assert.equal(observations,2);assert.deepEqual(files.map(p=>fs.statSync(p).ino),inodes);fs.unlinkSync(files[1]);await assert.rejects(synchronizeKnownSuccessorOutputs(files,verify));fs.writeFileSync(files[1],'foreign\n');await assert.rejects(synchronizeKnownSuccessorOutputs(files,verify));assert.equal(fs.readFileSync(files[1],'utf8'),'foreign\n');}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('reconciled outputs promote staged prerequisite intent before result',async()=>{const f=fixture(),execute=f.host.execute;let retained;f.host.execute=async(...args)=>{const value=await execute(...args);if(args[0]==='bundle'){retained=value;throw Error('lost ACK');}return value;};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));const staged=f.records.get('bundle.intent.json');f.records.delete('bundle.intent.json');const read=f.host.read,publish=f.host.publish;let promoted=false;f.host.read=n=>n==='bundle.intent.json'&&!promoted?staged:read(n);f.host.publish=(n,v)=>{if(n==='bundle.intent.json'){assert.deepEqual(v,staged);promoted=true;}if(n==='bundle.result.json')assert.equal(promoted,true);publish(n,v);};f.host.reconcile=async()=>retained;f.host.execute=execute;await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);assert.equal(promoted,true);assert.equal(f.effects.filter(s=>s==='bundle').length,1);});
