import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {buildInheritedOwnedFrontend,OWNED_CONFIG_PREDECESSOR} from '../packages/zola-release/owned-successor-configuration.js';
import {prepareOwnedSuccessorPreview} from '../packages/zola-release/owned-successor-preview.js';
const sha='a'.repeat(40),hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
function fixture(){const records=new Map(),plan={releaseSha:OWNED_CONFIG_PREDECESSOR,synthetic:true},rows=[];records.set('frontend-plan.json',plan);
 for(const scope of ['preview','production'])for(const key of ['BLACKSPIRE_BUYER_STORE_MODE','BLACKSPIRE_BUYER_STORE_URL','BLACKSPIRE_BUYER_DEAL_CONTEXT_KEY']){const row={id:scope+key,key,target:[scope],type:key.endsWith('KEY')?'sensitive':'plain',gitBranch:scope==='preview'?'release/zola-production-live':null,comment:'zola-owned-buyer:'+hash(plan)+':'+scope+'-'+key.toLowerCase(),updatedAt:1};rows.push(row);records.set(scope+'-'+key.toLowerCase()+'.result.json',{version:1,planDigest:hash(plan),row});}
 let receiver=JSON.stringify({schema:1,releaseSha:OWNED_CONFIG_PREDECESSOR,frontendOrigin:'https://old.vercel.app',deploymentId:'dpl_old'})+'\n',creates=0;
 const response={id:'dpl_new',projectId:'prj_a9x4Tuzgzq6XrvtdtYNxONwL8Fou',target:null,url:'new.vercel.app',readyState:'READY',gitSource:{sha,ref:'release/zola-production-live'}};
 const results={};for(const [name,value] of records)if(name.endsWith('.result.json'))results[name.slice(0,-12)]=value;const inherited=buildInheritedOwnedFrontend({previousReleaseSha:OWNED_CONFIG_PREDECESSOR,releaseSha:sha,frontendPlan:plan,rows,results});
 const host={readPredecessor:n=>records.get(n),readInheritance:()=>inherited,assertStopped:async()=>{},read:n=>records.get(n)??null,publish(n,v){if(records.has(n))assert.deepEqual(records.get(n),v);records.set(n,structuredClone(v));},readReceiver:()=>receiver,publishReceiver(before,after){assert.ok(receiver===before||receiver===after);receiver=after;}};
 const transport={project:async()=>null,restoreIgnore:async()=>assert.fail('unexpected restore'),settings:async()=>rows,create:async body=>{creates++;assert.equal(body.target,undefined);assert.equal(body.gitSource.sha,sha);assert.equal(body.projectSettings.commandForIgnoringBuildStep,'exit 1');return response;},get:async()=>response};
 return {records,host,transport,response,rows,verifyReceiver:async()=>{},creates:()=>creates};}
test('fresh preview binds final source/settings, publishes receiver and replays without redeploy',async()=>{const f=fixture();assert.equal((await prepareOwnedSuccessorPreview({releaseSha:sha},f)).status,'OWNED_SUCCESSOR_PREVIEW_READY');assert.equal((await prepareOwnedSuccessorPreview({releaseSha:sha},f)).status,'OWNED_SUCCESSOR_PREVIEW_READY');assert.equal(f.creates(),1);assert.equal(JSON.parse(f.host.readReceiver()).releaseSha,sha);});
test('unknown create never retries and preserves prior receiver',async()=>{const f=fixture(),before=f.host.readReceiver();let calls=0;f.transport.create=async()=>{calls++;throw Error();};await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));assert.equal(calls,1);assert.equal(f.host.readReceiver(),before);});
test('durable ID resumes building then READY; wrong branch/source/status never publishes',async()=>{const f=fixture();f.response.readyState='BUILDING';assert.equal((await prepareOwnedSuccessorPreview({releaseSha:sha},f)).status,'OWNED_SUCCESSOR_PREVIEW_BUILDING');f.response.readyState='READY';f.response.gitSource.sha='b'.repeat(40);await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));f.response.gitSource.sha=sha;f.response.gitSource.ref='main';await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));f.response.gitSource.ref='release/zola-production-live';assert.equal((await prepareOwnedSuccessorPreview({releaseSha:sha},f)).status,'OWNED_SUCCESSOR_PREVIEW_READY');assert.equal(f.creates(),1);});
test('environment metadata drift and receiver foreign replacement refuse',async()=>{const f=fixture();f.rows[0]={...f.rows[0],updatedAt:2};await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));assert.equal(f.creates(),0);const g=fixture();g.response.readyState='BUILDING';await prepareOwnedSuccessorPreview({releaseSha:sha},g);g.host.readReceiver=()=>'{"foreign":true}\n';g.response.readyState='READY';await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},g));});

test('staged plan and created records promote before GET and receiver publication',async()=>{const f=fixture();f.response.readyState='BUILDING';await prepareOwnedSuccessorPreview({releaseSha:sha},f);const staged=new Map();for(const n of ['preview-plan.json','preview.intent.json','preview.created.json']){staged.set(n,f.records.get(n));f.records.delete(n);}const read=f.host.read,publish=f.host.publish;f.host.read=n=>staged.get(n)??read(n);f.host.publish=(n,v)=>{if(staged.has(n)){assert.deepEqual(staged.get(n),v);staged.delete(n);}publish(n,v);};const get=f.transport.get;f.transport.get=async id=>{assert.equal(staged.size,0);return get(id);};f.response.readyState='READY';await prepareOwnedSuccessorPreview({releaseSha:sha},f);assert.equal(f.creates(),1);});
test('persistent provider ignore override restores exact prior value; unknown PATCH reconciles by GET',async()=>{const f=fixture();let setting='prior',patches=0;f.transport.project=async()=>setting;const create=f.transport.create;f.transport.create=async body=>{setting='exit 1';return create(body);};f.transport.restoreIgnore=async value=>{patches++;assert.equal(value,'prior');setting=value;throw Error('lost ACK');};await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));assert.ok(f.records.has('preview.ignore-restore-intent.json'));assert.equal((await prepareOwnedSuccessorPreview({releaseSha:sha},f)).status,'OWNED_SUCCESSOR_PREVIEW_READY');assert.equal(patches,1);assert.equal(f.creates(),1);});
test('foreign ignore setting refuses restoration',async()=>{const f=fixture();let setting=null;f.transport.project=async()=>setting;const create=f.transport.create;f.transport.create=async body=>{setting='foreign';return create(body);};await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));assert.equal(f.creates(),1);assert.ok(!f.records.has('preview.result.json'));});

test('unknown create can restore persisted ignore override without retrying deployment',async()=>{const f=fixture();let setting='prior',calls=0;f.transport.project=async()=>setting;f.transport.restoreIgnore=async value=>{setting=value;};f.transport.create=async()=>{calls++;setting='exit 1';throw Error('unknown');};await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));assert.equal(setting,'prior');assert.equal(calls,1);});

test('inherited proof substitution or missing proof refuses before deployment',async()=>{const f=fixture();f.host.readInheritance=()=>null;await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));assert.equal(f.creates(),0);const g=fixture();const old=g.host.readInheritance();g.host.readInheritance=()=>({...old,releaseSha:'c'.repeat(40)});await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},g));assert.equal(g.creates(),0);});

test('post-publication inherited metadata drift prevents completion without a new deployment',async()=>{const f=fixture();let calls=0;f.verifyReceiver=async()=>{calls++;if(calls===2)f.rows[0].updatedAt++;};await assert.rejects(prepareOwnedSuccessorPreview({releaseSha:sha},f));assert.equal(f.creates(),1);assert.equal(f.records.has('preview.result.json'),false);});
