import test from 'node:test';import assert from 'node:assert/strict';
import {OwnedCloudSettledReadError,runOwnedCloudStartupFence} from '../packages/zola-release/owned-n8n-cloud-startup-fence.js';
import {boundedOwnedN8nCloudFence} from '../packages/zola-release/owned-n8n-cloud-verifier.js';
test('startup accepts a settled success beyond10seconds within25seconds without weakening identity',async()=>{let clock=0,checks=0;const phases=[];await runOwnedCloudStartupFence({now:()=>clock,stable:()=>checks++,record:(...v)=>phases.push(v),fence:()=>boundedOwnedN8nCloudFence(async()=>{clock=18000;},{timeoutMs:25000,now:()=>clock})});assert.equal(checks,2);assert.equal(phases.at(-1)[0],'POST_PROXY_FENCE_VERIFIED');});
test('only settled transport failure retries, and drift or semantic failure is terminal',async()=>{for(const mode of ['transport','semantic','drift']){let active=0,max=0,calls=0,checks=0;const f={stable:()=>{if(mode==='drift'&&++checks>1)throw Error('identity drift');},record:()=>{},pause:async()=>{},fence:async()=>{active++;max=Math.max(max,active);calls++;await Promise.resolve();active--;if(calls===1)throw mode==='semantic'?Error('invariant'):new OwnedCloudSettledReadError();}};if(mode==='transport')await runOwnedCloudStartupFence(f);else await assert.rejects(runOwnedCloudStartupFence(f));assert.equal(max,1);assert.equal(calls,mode==='transport'?2:1);}});
test('hard timeout never launches another fence while prior work is unsettled',async()=>{let calls=0,finish;const pending=new Promise(r=>finish=r);await assert.rejects(runOwnedCloudStartupFence({stable:()=>{},record:()=>{},fence:()=>{calls++;return boundedOwnedN8nCloudFence(()=>pending,{timeoutMs:5});}}),/timeout/);assert.equal(calls,1);finish();await pending;assert.equal(calls,1);});

import {notReadyFixture} from './helpers/owned-n8n-cloud-not-ready-fixture.js';
import {buildOwnedN8nCloudWorkflow} from '../packages/zola-release/owned-n8n-cloud-workflow.js';
import {renderOwnedN8nCloudProxy} from '../packages/zola-release/owned-n8n-cloud-verifier.js';
test('fifth aggregate admits completed 18s checks but refuses completed over-budget work without replay',async()=>{for(const elapsed of [18000,26000]){let clock=0,calls=0;const task=()=>boundedOwnedN8nCloudFence(async()=>{calls++;clock=elapsed;},{timeoutMs:25000,now:()=>clock});if(elapsed<25000)await task();else await assert.rejects(task(),/elapsed deadline/);assert.equal(calls,1);}});
test('fifth transport encloses two aggregate fences while prior workflow and proxy remain unchanged',()=>{const f=notReadyFixture(),old=f.records.plan,newPlan={...old,attempt:5,predecessorNotReadyDigest:'e'.repeat(64)};const before=f.records['proxy-bytes'].before;const prior=buildOwnedN8nCloudWorkflow(old),next=buildOwnedN8nCloudWorkflow(newPlan);assert.equal(prior.nodes[1].parameters.options.timeout,40000);assert.equal(prior.settings.executionTimeout,60);assert.equal(renderOwnedN8nCloudProxy(before,old),f.records['proxy-bytes'].candidate);assert.match(renderOwnedN8nCloudProxy(before,old),/proxy_read_timeout 30s;/);assert.equal(next.nodes[1].parameters.options.timeout,70000);assert.equal(next.settings.executionTimeout,90);assert.match(renderOwnedN8nCloudProxy(before,newPlan),/proxy_read_timeout 60s;/);assert.equal(next.nodes[1].retryOnFail,false);});

test('sixth transport preserves fifth serialized workflow and proxy and requires separate fifth expiry digest',()=>{const f=notReadyFixture(),fifth={...f.records.plan,attempt:5,predecessorNotReadyDigest:'e'.repeat(64)},sixth={...fifth,attempt:6,predecessorFifthExpiryDigest:'f'.repeat(64)};const before=f.records['proxy-bytes'].before;const expected=buildOwnedN8nCloudWorkflow(fifth),actual=buildOwnedN8nCloudWorkflow(sixth);assert.equal(actual.name,'Zola credential proof attempt6 '+sixth.challenge);assert.deepEqual({...actual,name:expected.name},expected);assert.equal(renderOwnedN8nCloudProxy(before,sixth),renderOwnedN8nCloudProxy(before,fifth));assert.throws(()=>buildOwnedN8nCloudWorkflow({...sixth,predecessorFifthExpiryDigest:undefined}));assert.throws(()=>buildOwnedN8nCloudWorkflow({...fifth,predecessorFifthExpiryDigest:'f'.repeat(64)}));});
