import test from 'node:test';import assert from 'node:assert/strict';
import {failed7Fixture} from './helpers/owned-n8n-cloud-failed7-fixture.js';
import {validateFailed7OwnedN8nAttempt,validateFailed7OwnedN8nRetirement,retireFailed7OwnedN8nAttempt} from '../packages/zola-release/owned-n8n-cloud-failed7.js';
import {validateOwnedN8nCredentialSave8,SAVED8_UPDATED_AT} from '../packages/zola-release/owned-n8n-credential-save8.js';
test('exact seventh rejection/failed graph retires once preserving original records and only safe execution projection',async()=>{
 const f=failed7Fixture(),before=JSON.stringify(f.records);f.execution.data.resultData.error.request={syntheticSensitiveDetail:'must-not-retain'};
 assert.equal(validateFailed7OwnedN8nAttempt(f.records).classification,'AUTH_LENGTH_MISMATCH');
 const result=await retireFailed7OwnedN8nAttempt(f.records,f),observation=f.rows.get('observation');
 assert.equal(result.positiveProof,false);assert.equal(result.originalOutcome,'UNKNOWN');assert.equal(result.administrativeReassertionStatus,405);assert.equal(result.classification,'AUTH_LENGTH_MISMATCH_AND_CLEANED');
 assert.equal(JSON.stringify(f.records),before);assert.equal(JSON.stringify(observation).includes('must-not-retain'),false);assert.equal(observation.execution.id,'3');assert.match(observation.execution.rawDigest,/^[a-f0-9]{64}$/);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);
 assert.deepEqual(validateFailed7OwnedN8nRetirement(f.records,{observation,intent:f.rows.get('intent'),result}),result);
});
test('unknown deletion adopts only authenticated absence without repeat or dependence on cascaded execution',async()=>{const f=failed7Fixture();f.setUnknownDelete();await assert.rejects(retireFailed7OwnedN8nAttempt(f.records,f));const count=f.calls.length;await retireFailed7OwnedN8nAttempt(f.records,f);assert.deepEqual(f.calls.slice(count).map(c=>c.method),['GET']);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('foreign identity/rejection/proof/supervisor/execution/graph/inventory/local state refuse retirement',async()=>{
 for(const mutate of [f=>f.records['server-rejection']=null,f=>f.records['server-rejection'].code='AUTH_VALUE_MISMATCH',f=>f.records['server-rejection'].receivedAt=f.records.plan.expiresAt,f=>f.records['server-receipt']={},f=>f.records['supervisor-result'].supervisor.invocationId='a'.repeat(32),f=>f.records['cleanup-result']=null,f=>f.execution.id='4',f=>f.execution.status='success',f=>f.execution.usedPrivateCredentials=true,f=>f.execution.data.resultData.error.httpCode='401',f=>f.execution.data.resultData.runData['Verify stored credential'][0].data={},f=>f.execution.workflowData.nodes[1].parameters.sendHeaders=true,f=>f.executionInventory.body.data.push(f.executionInventory.body.data[0]),f=>f.executionInventory.body.nextCursor='more',f=>f.local.listenerAbsent=false,f=>f.local.supervisorExitedAt=f.records.plan.expiresAt]){const f=failed7Fixture();mutate(f);await assert.rejects(retireFailed7OwnedN8nAttempt(f.records,f));assert.equal(f.calls.some(c=>c.method==='DELETE'),false);}
});
test('retained projection drift refuses reconciliation without redispatch',async()=>{const f=failed7Fixture();await retireFailed7OwnedN8nAttempt(f.records,f);f.rows.get('observation').execution.rawDigest='0'.repeat(64);await assert.rejects(retireFailed7OwnedN8nAttempt(f.records,f));assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('manual save accepts only exact7-to8 public metadata transition and never implies possession',()=>{
 const before=failed7Fixture().records.plan.credentialMetadata,after={...before,updatedAt:SAVED8_UPDATED_AT},original=JSON.stringify(before);assert.equal(validateOwnedN8nCredentialSave8(before,after).positiveProof,false);assert.equal(JSON.stringify(before),original);
 for(const mutate of [v=>v.updatedAt=before.updatedAt,v=>v.updatedAt='2026-09-22T23:16:49.972Z',v=>v.id='foreign',v=>v.name='foreign',v=>v.type='other',v=>v.isGlobal=true,v=>v.data={}]){const changed=structuredClone(after);mutate(changed);assert.throws(()=>validateOwnedN8nCredentialSave8(before,changed));}
 assert.throws(()=>validateOwnedN8nCredentialSave8(after,before));assert.throws(()=>validateOwnedN8nCredentialSave8({...before,updatedAt:'2026-09-21T22:55:51.255Z'},after));
});
test('raw response drift between observation and delete refuses even when safe status projection matches',async()=>{const f=failed7Fixture(),request=f.request;let executions=0;f.request=async(method,path)=>{if(path==='/api/v1/executions/3?includeData=true'&&++executions===2)f.execution.data.resultData.error.message='changed-provider-detail';return request(method,path);};await assert.rejects(retireFailed7OwnedN8nAttempt(f.records,f));assert.equal(f.calls.some(c=>c.method==='DELETE'),false);assert.equal(f.rows.has('result'),false);});
