import {interruptedFixture} from './helpers/owned-n8n-cloud-interrupted.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {INTERRUPTED_NAMES,INTERRUPTED_OPERATOR,INTERRUPTED_WORKFLOW,validateInterruptedOwnedN8nAttempt,validateInterruptedOwnedN8nAbandonment,abandonInterruptedOwnedN8nAttempt} from '../packages/zola-release/owned-n8n-cloud-interrupted.js';
import {cloudProofDigest as hash,buildOwnedN8nCloudWorkflow,validateOwnedN8nCloudPlan} from '../packages/zola-release/owned-n8n-cloud-workflow.js';
import {cloudProofHash,renderOwnedN8nCloudProxy} from '../packages/zola-release/owned-n8n-cloud-verifier.js';
import {ownedN8nAttempt3SupervisorArguments,validateOwnedN8nAttempt3Supervisor} from '../packages/zola-release/owned-n8n-cloud-supervisor.js';
test('exact interrupted-before-ready cleanup preserves attempt2 and retains separate deletion proof',async()=>{const f=interruptedFixture(),original=JSON.stringify(f.records);const r=await abandonInterruptedOwnedN8nAttempt(f.records,f);assert.equal(r.binding.classification,'INTERRUPTED_BEFORE_READY');assert.equal(r.positiveProof,false);assert.equal(r.workflowDeleted,true);assert.equal(JSON.stringify(f.records),original);assert.equal(f.calls.filter(c=>c[0]==='DELETE').length,1);validateInterruptedOwnedN8nAbandonment(f.records,{observation:f.retained.get('observation'),intent:f.retained.get('intent'),result:r});await abandonInterruptedOwnedN8nAttempt(f.records,f);assert.equal(f.calls.filter(c=>c[0]==='DELETE').length,1);});
test('every ready/proxy/execution/negative receipt and contradictory cleanup refuses before calls',async()=>{for(const name of INTERRUPTED_NAMES.slice(6).filter(n=>!['cleanup-intent','cleanup-result'].includes(n))){const f=interruptedFixture();f.records[name]={present:true};await assert.rejects(abandonInterruptedOwnedN8nAttempt(f.records,f));assert.equal(f.calls.length,0);}for(const change of [f=>f.records['cleanup-result']=null,f=>f.records['cleanup-intent']=null,f=>f.records['cleanup-result'].proxyRestored=false,f=>f.records.plan.operatorSha='a'.repeat(40),f=>f.records['workflow-create-ack'].responseDigest='a'.repeat(64),f=>f.records['proxy-bytes'].before+='foreign']){const f=interruptedFixture();change(f);await assert.rejects(abandonInterruptedOwnedN8nAttempt(f.records,f));assert.equal(f.calls.length,0);}});
test('listener,temp,proxy drift, executions and edited remote workflow never delete',async()=>{for(const change of [f=>f.setLocal({listenerAbsent:false}),f=>f.setLocal({temporaryAbsent:false}),f=>f.setLocal({proxy:'foreign'}),f=>f.setInventory([{id:'one'}]),f=>f.setWorkflow({...f.records['workflow-created'].workflow,versionId:'edited'}),f=>f.setWorkflow({...f.records['workflow-created'].workflow,active:true})]){const f=interruptedFixture();change(f);await assert.rejects(abandonInterruptedOwnedN8nAttempt(f.records,f));assert.equal(f.calls.some(c=>c[0]==='DELETE'),false);}});
test('lost delete acknowledgment reconciles absence without repeating DELETE',async()=>{const f=interruptedFixture();f.setLost();await assert.rejects(abandonInterruptedOwnedN8nAttempt(f.records,f));assert.ok(f.retained.has('intent'));assert.equal(f.retained.has('result'),false);const r=await abandonInterruptedOwnedN8nAttempt(f.records,f);assert.equal(r.workflowDeleted,true);assert.equal(f.calls.filter(c=>c[0]==='DELETE').length,1);});
test('staged retained intent is promoted before result and foreign retained result refuses',async()=>{const f=interruptedFixture();f.setLost();await assert.rejects(abandonInterruptedOwnedN8nAttempt(f.records,f));const record=f.store.record,order=[];f.store.record=(n,v)=>{order.push(n);record(n,v);};await abandonInterruptedOwnedN8nAttempt(f.records,f);assert.ok(order.indexOf('intent')<order.indexOf('result'));f.retained.get('result').positiveProof=true;await assert.rejects(abandonInterruptedOwnedN8nAttempt(f.records,f));});
test('attempt3 plan requires distinct interruption lineage and explicit workflow name',()=>{const f=interruptedFixture(),p={...f.records.plan,attempt:3,predecessorInterruptionDigest:'f'.repeat(64)};assert.equal(validateOwnedN8nCloudPlan(p),p);assert.ok(buildOwnedN8nCloudWorkflow(p).name.startsWith('Zola credential proof attempt3 '));assert.throws(()=>validateOwnedN8nCloudPlan({...p,predecessorInterruptionDigest:undefined}));assert.throws(()=>validateOwnedN8nCloudPlan({...p,attempt:2}));});
test('supervisor command is detached bounded nonrestarting and fixed to attempt3 with private logs',()=>{const input={operatorRoot:'/mnt/blackspire-builds/development-cache/0/workspaces/zola-owned-cloud-attempt3-20260921',root:'/var/lib/blackspire-operator/preparation/owned-n8n-cloud-proof/a8e05ef40e44b6695df5b30356af0e411fe36f1a-c8b00904-7017-434a-918e-8aaadbae82fd-attempt3'},args=ownedN8nAttempt3SupervisorArguments(input);for(const a of ['--property=Type=exec','--property=RuntimeMaxSec=17min','--property=Restart=no','--property=KillMode=control-group','--property=RemainAfterExit=yes','--property=UMask=0077'])assert.ok(args.includes(a));assert.equal(args.at(-1),'--serve');assert.equal(args.some(a=>a.includes('ExecStopPost')||a==='--wait'),false);assert.throws(()=>ownedN8nAttempt3SupervisorArguments({...input,root:input.root.replace('attempt3','attempt2')}));});

test('READY and completion bind exact supervisor intent, unit, PID start and invocation',()=>{
 const f=interruptedFixture(),plan={...f.records.plan,attempt:3,predecessorInterruptionDigest:'f'.repeat(64)},operatorRoot='/mnt/blackspire-builds/development-cache/0/workspaces/zola-owned-cloud-attempt3-20260921',root='/var/lib/blackspire-operator/preparation/owned-n8n-cloud-proof/a8e05ef40e44b6695df5b30356af0e411fe36f1a-c8b00904-7017-434a-918e-8aaadbae82fd-attempt3';
 const command=['/opt/nodejs/node-v22.23.1-linux-x64/bin/node',operatorRoot+'/scripts/zola-n8n-cloud-proof-attempt3.js','--serve'];
 const properties={Type:'exec',User:'root',Group:'root',UMask:'0077',RuntimeMaxUSec:'17min',TimeoutStopUSec:'40s',Restart:'no',KillMode:'control-group',RemainAfterExit:'yes',NoNewPrivileges:'yes',ActiveState:'active',SubState:'running',MainPID:'1234',InvocationID:'a'.repeat(32),Result:'success',ExecMainStatus:'0',ExecStart:'{ path='+command[0]+' ; argv[]='+command.join(' ')+' ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=1234 ; code=(null) ; status=0/0 }'};
 const intent={version:1,planDigest:hash(plan),unit:'zola-n8n-cloud-proof-attempt3.service',argumentsDigest:hash(ownedN8nAttempt3SupervisorArguments({operatorRoot,root}))},process={pid:1234,uid:0,startTime:'987654',command},input={plan,operatorRoot,root,intent,properties,process,phase:'launch'};
 const supervisor=validateOwnedN8nAttempt3Supervisor(input),result={version:1,planDigest:hash(plan),unit:intent.unit,started:true,supervisor};assert.deepEqual(validateOwnedN8nAttempt3Supervisor({...input,result,phase:'ready'}),supervisor);
 for(const key of Object.keys(properties).filter(k=>!['Result','ExecMainStatus'].includes(k)))assert.throws(()=>validateOwnedN8nAttempt3Supervisor({...input,result,phase:'ready',properties:{...properties,[key]:'foreign'}}));
 for(const patch of [{intent:null},{result:null},{process:{...process,startTime:'999'}},{process:{...process,command:['foreign']}}])assert.throws(()=>validateOwnedN8nAttempt3Supervisor({...input,result,phase:'ready',...patch}));
 const complete={...input,result,phase:'complete',properties:{...properties,MainPID:'0',SubState:'exited'}};assert.deepEqual(validateOwnedN8nAttempt3Supervisor(complete),supervisor);assert.throws(()=>validateOwnedN8nAttempt3Supervisor({...complete,properties:{...complete.properties,ExecMainStatus:'1'}}));
});
