import test from 'node:test';import assert from 'node:assert/strict';
import {expiredFixture} from './helpers/owned-n8n-cloud-expired-fixture.js';
import {validateExpiredOwnedN8nAttempt,validateExpiredOwnedN8nRetirement,retireExpiredOwnedN8nAttempt} from '../packages/zola-release/owned-n8n-cloud-expired.js';
test('expired ready attempt classification preserves all original record bytes',()=>{const f=expiredFixture(),before=JSON.stringify(f.records),r=validateExpiredOwnedN8nAttempt(f.records);assert.equal(r.classification,'EXPIRED_BEFORE_REQUEST');assert.equal(r.positiveProof,false);assert.equal(JSON.stringify(f.records),before);});
test('late401 retirement retains full bounded raw execution and never claims credential mismatch or proof',async()=>{const f=expiredFixture(),before=JSON.stringify(f.records),r=await retireExpiredOwnedN8nAttempt(f.records,f);assert.equal(r.classification,'EXPIRED_AND_CLEANED_BEFORE_LATE_EXECUTION');assert.equal(r.positiveProof,false);assert.equal(r.originalOutcome,'UNKNOWN');assert.equal(r.administrativeReassertionStatus,405);assert.deepEqual(f.rows.get('observation').execution,f.execution);assert.equal(JSON.stringify(f.records),before);assert.equal(validateExpiredOwnedN8nRetirement(f.records,{observation:f.rows.get('observation'),intent:f.rows.get('intent'),result:r}).executionDigest,r.executionDigest);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('unknown DELETE adopts only404 and never repeats DELETE even after execution cascade',async()=>{const f=expiredFixture();f.setUnknownDelete();await assert.rejects(retireExpiredOwnedN8nAttempt(f.records,f));assert.equal(f.rows.has('result'),false);const count=f.calls.length;await retireExpiredOwnedN8nAttempt(f.records,f);assert.deepEqual(f.calls.slice(count).map(c=>c.method),['GET']);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('missing cleanup, positive or negative verifier receipt, altered supervisor and foreign graph refuse',async()=>{for(const mutate of [f=>f.records['cleanup-result']=null,f=>f.records['server-receipt']={},f=>f.records['server-rejection']={},f=>f.records['supervisor-intent'].argumentsDigest='0'.repeat(64),f=>f.records['workflow-created'].workflow.nodes[1].parameters.url='https://foreign.invalid']){const f=expiredFixture();mutate(f);await assert.rejects(retireExpiredOwnedN8nAttempt(f.records,f));assert.equal(f.calls.length,0);}});
test('late execution exactidentity/error/projection, inventory closure and historical exit order are mandatory',async()=>{for(const mutate of [f=>f.execution.id='3',f=>f.execution.startedAt=f.records.plan.expiresAt,f=>f.execution.status='success',f=>f.execution.usedPrivateCredentials=true,f=>f.execution.data.resultData.error.httpCode='403',f=>f.execution.data.resultData.runData['Verify stored credential'][0].error.httpCode='200',f=>f.execution.workflowData.nodes[1].parameters.sendHeaders=true,f=>f.executionInventory.body.data.push(f.executionInventory.body.data[0]),f=>f.executionInventory.body.nextCursor='more',f=>f.local.supervisorExitedAt='2026-09-22T00:33:00.000Z',f=>f.local.listenerAbsent=false]){const f=expiredFixture();mutate(f);await assert.rejects(retireExpiredOwnedN8nAttempt(f.records,f));assert.equal(f.calls.some(c=>c.method==='DELETE'),false);}});
test('retained observation tamper refuses reconciliation without another deletion',async()=>{const f=expiredFixture();await retireExpiredOwnedN8nAttempt(f.records,f);f.rows.get('observation').execution.data.resultData.error.httpCode='200';await assert.rejects(retireExpiredOwnedN8nAttempt(f.records,f));assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
