import {createProviderAclCheckOperation} from '../packages/zola-release/production-acl-writer.js';
import {databaseProfileDigest} from '../packages/buyer-writer/database-profile.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {observeOwnedAclScoped,createOwnedAclObserverPool,verifyOwnedOperatorAclResult} from '../packages/zola-release/owned-acl-operator-observer.js';
import {OWNED_POSTGRES_TARGET} from '../packages/buyer-writer/owned-postgres.js';
import {OWNED_DATABASE_ACL_SQL,OWNED_DATABASE_BOUNDARY_SQL,ownedDatabaseAclParameters,verifyOwnedDatabaseAclResult} from '../packages/buyer-writer/owned-database-evidence.js';
import {BUYER_WRITER_PRODUCTION_VERIFY_SQL} from '../packages/buyer-writer/production-verifier.js';
import {writerEvidenceFixture} from './helpers/owned-writer-evidence-fixture.js';
const profile={version:1,...OWNED_POSTGRES_TARGET,creatorOid:16388,systemIdentifier:'1234567890123456789',caSha256:'a'.repeat(64)};
function fixture(){let actor='postgres';const calls=[],boundary={database:'postgres',actor:'postgres',sessionActor:'postgres',creatorOid:'16388',databaseOwnerOid:'16388',systemIdentifier:profile.systemIdentifier,serverVersion:170006,recovery:false,readOnly:true,managementSuperuser:false,extensions:['plpgsql'],netSchemas:0,networkRoutines:0,foreignDataWrappers:0,foreignServers:0,foreignTables:0,userMappings:0},writer=writerEvidenceFixture();writer.pgNet=writer.pgNet.map(v=>({...v,signature:null,owner:null,publicExecute:false,ownerExecute:false,runtimeExecute:false,issuerExecute:false,admissionExecute:false}));
 const client={async query(sql){calls.push(sql);if(sql.startsWith('select session_user'))return{rows:[{session_actor:'postgres',current_actor:actor}]};if(sql===OWNED_DATABASE_BOUNDARY_SQL){assert.equal(actor,'postgres');return{rows:[{boundary}]};}if(sql==='set role buyer_writer_owner'){actor='buyer_writer_owner';return{};}if(sql==='reset role'){actor='postgres';return{};}if(sql===BUYER_WRITER_PRODUCTION_VERIFY_SQL){assert.equal(actor,'buyer_writer_owner');return{rows:[{evidence:writer}]};}return{rows:[]};},release(){calls.push('release');}};return{client,calls,boundary,actor:()=>actor};}
test('split observer preserves canonical evidence and resets exact actor',async()=>{const f=fixture();const result=await observeOwnedAclScoped(f.client,profile,ownedDatabaseAclParameters(profile));assert.equal(verifyOwnedDatabaseAclResult(result,profile).writerIsolationVerified,true);assert.equal(f.actor(),'postgres');assert.ok(f.calls.indexOf(OWNED_DATABASE_BOUNDARY_SQL)<f.calls.indexOf('set role buyer_writer_owner'));});
test('foreign boundary refuses before role switch; failed catalog restores actor',async()=>{const f=fixture();f.boundary.systemIdentifier='999';await assert.rejects(observeOwnedAclScoped(f.client,profile,ownedDatabaseAclParameters(profile)));assert.equal(f.calls.includes('set role buyer_writer_owner'),false);const g=fixture(),query=g.client.query;g.client.query=sql=>sql===BUYER_WRITER_PRODUCTION_VERIFY_SQL?Promise.reject(Error('query failure')):query(sql);await assert.rejects(observeOwnedAclScoped(g.client,profile,ownedDatabaseAclParameters(profile)));assert.equal(g.actor(),'postgres');});
test('reset failure is fatal and Pool adapter only intercepts exact ACL statement',async()=>{const f=fixture(),query=f.client.query;f.client.query=sql=>sql==='reset role'?Promise.reject(Error('reset failure')):query(sql);await assert.rejects(observeOwnedAclScoped(f.client,profile,ownedDatabaseAclParameters(profile)),/reset failure/);const g=fixture();class Pool{async connect(){return g.client;}async end(){g.calls.push('end');}}const pool=new (createOwnedAclObserverPool(Pool,profile))({}),client=await pool.connect();await client.query('begin read only');await client.query(OWNED_DATABASE_ACL_SQL,ownedDatabaseAclParameters(profile));await client.query('rollback');client.release(true);await pool.end();assert.ok(g.calls.includes('begin read only'));assert.deepEqual(g.calls.slice(-3),['rollback','release','end']);});

test('final owned provider stage validates truthful seven edges without legacy six fallback',async()=>{
 const f=fixture(),raw=await observeOwnedAclScoped(f.client,profile,ownedDatabaseAclParameters(profile)),writer=raw.rows[0].writer;
 writer.memberships.push({role:'buyer_writer_admission_login',roleOid:'16394',member:'postgres',memberOid:'16388',grantor:'blackspire_cluster_admin',grantorOid:'10',memberLogin:true,grantorSuperuser:true,admin:true,inherit:false,set:false});
 // Canonical creator edges bind the actual owned bootstrap grantor too.
 for(const edge of writer.memberships)if(edge.grantor==='fixture_admin')edge.grantor='blackspire_cluster_admin';
 const evidence=verifyOwnedOperatorAclResult(raw,profile);assert.equal(writer.memberships.length,7);assert.throws(()=>verifyOwnedDatabaseAclResult(raw,profile));
 const profileDigest=databaseProfileDigest(profile),query=async()=>({backendProfile:'owned-postgres-v1',profile,profileDigest,observation:raw,evidence});
 const isolation={pgNetIsolationVerified:true,applicationDbCredentialsAbsent:true,gatewayTransportVerified:true,arbitrarySqlDenied:true,arbitraryFunctionDenied:true,arbitraryUrlDenied:true,applicationPgNetCallSitesZero:true,applicationDbPgNetReferenceCount:0,applicationDbPgNetReferencesZero:true,applicationPgNetCallSiteCount:0,sourceScanDigest:'a'.repeat(64),functionBodyDigest:'b'.repeat(64)};
 const op=createProviderAclCheckOperation({query,isolationProof:async()=>({status:'PASS',evidence:isolation}),backendProfile:'owned-postgres-v1',profileDigest,verifyAcl:verifyOwnedOperatorAclResult});
 const input={releaseSha:'c'.repeat(40),workspace:'blackspire-command',principal:'blackspire-release-root',backendProfile:'owned-postgres-v1',profileDigest},args={input,state:{context:{...input,operationId:'11111111-1111-4111-8111-111111111111'}}};
 assert.equal((await op.check(args)).status,'PASS');assert.equal((await op.observe(args)).status,'PASS');
 writer.memberships[6].set=true;assert.equal((await op.check(args)).status,'BLOCKED_EXTERNAL');
});
