import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {runOwnedSourceSecurity,createOwnedSourceSecurityFiles,OWNED_SOURCE_IDENTITY_SQL,OWNED_SOURCE_EFFECTIVE_SQL,OWNED_SOURCE_SCHEMA_EFFECTIVE_SQL} from '../packages/buyer-writer/owned-source-security-host.js';
import {EXTENSION_ACL_CATALOG_SQL} from '../packages/buyer-writer/extension-acl-catalog.js';
import {OWNED_SOURCE_FREEZE_CHECK_SQL} from '../packages/buyer-writer/owned-source-security.js';
import {openReleaseJournal} from '../packages/zola-release/commander-journal.js';
import {providerFixture} from './helpers/owned-provider-fixture.js';
const releaseSha='a'.repeat(40),operationId='11111111-1111-4111-8111-111111111111';
function fixture(){const root=fs.mkdtempSync('/run/source-security-host-');fs.chmodSync(root,0o700);fs.mkdirSync(root+'/global',{mode:0o700});const fixture=providerFixture();fixture.inventory.database='postgres';fixture.inventory.columns=fixture.columns.columns;let credential={value:{host:'fixed-original',password:'synthetic test only',ca:'synthetic test certificate'},identity:{revision:1}},lost=false,row=null,bodyCalls=0,stopped=true,ends=0;
 const queries=[],profile={systemIdentifier:'9000000000000000000'},identity={systemIdentifier:'1234567890123456789',creatorOid:16388,database:'postgres',actor:'postgres',session:'postgres',databaseOwnerOid:16388,superuser:false,bypassRls:true,recovery:false};
 const deps={root:root+'/operations',openGlobal:()=>openReleaseJournal({root:root+'/global'}),verifySource:s=>assert.equal(s,releaseSha),stopped:()=>{if(!stopped)throw new Error('not quiescent');},readSnapshot:()=>structuredClone(credential),now:()=>new Date('2026-09-21T18:00:00Z'),database:{LEGACY_DATABASE_MANAGEMENT:'/fixed-original',readOwnedDatabaseProfile:()=>profile,databaseProfileDigest:()=> 'b'.repeat(64),validateManagementCredential:(v,o)=>{assert.deepEqual(o,{pinLegacyCa:true});assert.deepEqual(v,credential.value);return{...v,user:'postgres',database:'postgres',port:5432};},databaseTlsOptions:()=>({rejectUnauthorized:true,ca:credential.value.ca})},
 connect:async(config,ssl)=>{assert.equal(config.host,'fixed-original');assert.equal(ssl.rejectUnauthorized,true);return{end:async()=>{ends++;},query:async(sql,values=[])=>{queries.push(sql);
 if(sql===OWNED_SOURCE_IDENTITY_SQL)return{rows:[identity]};if(sql===EXTENSION_ACL_CATALOG_SQL)return{rows:[{metadata:fixture.inventory}]};if(sql===OWNED_SOURCE_EFFECTIVE_SQL)return{rows:[{effective:fixture.effective.effective}]};if(sql===OWNED_SOURCE_SCHEMA_EFFECTIVE_SQL)return{rows:[{schemaEffective:fixture.effective.schemaEffective}]};
 if(sql.startsWith('SELECT EXISTS'))return{rows:[{present:false}]};if(sql.includes('pg_try_advisory'))return{rows:[{acquired:true}]};if(sql.startsWith('SELECT version,name'))return{rows:row?[row]:[]};
 if(sql.startsWith('INSERT INTO supabase_migrations')){row={version:values[0],name:values[1],statements:values[2],idempotency_key:values[3]};return{rowCount:1};}
 if(sql===OWNED_SOURCE_FREEZE_CHECK_SQL)return{rows:[{evidence:{transactionReadOnly:true,sourceWritesDenied:true,browserDenied:true,anonymousJobsDenied:true,ownReadPreserved:true}}]};
 if(sql.includes('Source identity or writer authority changed')&&sql.includes('Source effective writes remain'))bodyCalls++;
 if(sql==='COMMIT'&&lost)throw new Error('lost commit acknowledgement');return{rows:[]};}};}};
 return{root,deps,queries,identity,config:root+'/operations/'+operationId+'/configuration.json',run:mode=>runOwnedSourceSecurity({releaseSha,operationId,mode},deps),set lost(v){lost=v;},set stopped(v){stopped=v;},drift:()=>{credential.identity.revision++;},get bodyCalls(){return bodyCalls;},get row(){return row;},get ends(){return ends;},cleanup:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('real protected preparation is read only and retains exact package/version across replay',{skip:process.getuid()!==0},async()=>{const f=fixture();try{const first=await f.run('prepare');assert.equal(first.status,'OWNED_SOURCE_SECURITY_PREPARED');assert.equal(first.migrationVersion,'20260921180000');assert.ok(f.queries.includes('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY'));assert.ok(!f.queries.includes('COMMIT'));assert.equal(f.bodyCalls,0);const bytes=fs.readFileSync(f.config);assert.equal(fs.statSync(f.config).mode&0o7777,0o600);await f.run('prepare');assert.deepEqual(fs.readFileSync(f.config),bytes);assert.equal(f.queries.filter(s=>s===EXTENSION_ACL_CATALOG_SQL).length,1);assert.equal(f.ends,2);assert.equal(fs.existsSync(f.root+'/global/commander.lock'),false);}finally{f.cleanup();}});
test('actual dedicated hash journal retains unknown commit and native executor reconciles without redispatch',{skip:process.getuid()!==0},async()=>{const f=fixture();try{await f.run('prepare');f.lost=true;await assert.rejects(f.run('apply'));assert.equal(f.bodyCalls,1);assert.equal(f.row.version,'20260921180000');await assert.rejects(f.run('apply'));assert.equal(f.bodyCalls,1);f.lost=false;assert.equal((await f.run('reconcile')).status,'OWNED_SOURCE_SECURITY_VERIFIED');assert.equal((await f.run('reconcile')).status,'OWNED_SOURCE_SECURITY_VERIFIED');assert.equal(f.bodyCalls,1);const lines=fs.readFileSync(f.config.replace('configuration.json','release.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(lines[0].event.type,'owned_source_security_intent');assert.equal(lines.at(-1).event.status,'VERIFIED');assert.ok(lines.every(v=>/^[a-f0-9]{64}$/.test(v.digest)));}finally{f.cleanup();}});
test('global exclusion and configuration/credential/quiescence drift block effects',{skip:process.getuid()!==0},async()=>{const f=fixture();try{const lock=openReleaseJournal({root:f.root+'/global'});await assert.rejects(f.run('prepare'));assert.equal(f.queries.length,0);lock.close();await f.run('prepare');f.stopped=false;await assert.rejects(f.run('apply'));f.stopped=true;const connect=f.deps.connect;f.deps.connect=async(...args)=>{const c=await connect(...args);f.drift();return c;};await assert.rejects(f.run('apply'));assert.equal(f.bodyCalls,0);}finally{f.cleanup();}});
test('same source/target identity refuses preparation',{skip:process.getuid()!==0},async()=>{const f=fixture();try{f.identity.systemIdentifier='9000000000000000000';await assert.rejects(f.run('prepare'));assert.equal(fs.existsSync(f.config),false);}finally{f.cleanup();}});
test('durable configuration stage recovers atomic rename loss and never overwrites foreign contents',{skip:process.getuid()!==0},()=>{const root=fs.mkdtempSync('/run/source-security-file-');fs.chmodSync(root,0o700);const file=root+'/configuration.json';let once=true;const io=new Proxy(fs,{get(t,k){if(k==='renameSync')return(...args)=>{if(once){once=false;throw new Error('interrupted before rename');}return fs.renameSync(...args);};return t[k];}});const files=createOwnedSourceSecurityFiles({io});try{assert.throws(()=>files.publish(file,{version:1,value:'fixture'}));assert.equal(fs.existsSync(file),false);files.publish(file,{version:1,value:'fixture'});assert.equal(fs.existsSync(file+'.pending'),false);assert.deepEqual(files.read(file),{version:1,value:'fixture'});assert.throws(()=>files.publish(file,{version:1,value:'foreign'}));fs.chmodSync(file,0o644);assert.throws(()=>files.read(file));}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('metadata records above credential ceiling remain protected and bounded',{skip:process.getuid()!==0},()=>{const root=fs.mkdtempSync('/run/source-security-large-');fs.chmodSync(root,0o700);const file=root+'/configuration.json',files=createOwnedSourceSecurityFiles(),value={metadata:'x'.repeat(70*1024)};try{files.publish(file,value);assert.deepEqual(files.read(file),value);assert.throws(()=>files.publish(root+'/oversized.json',{metadata:'x'.repeat(2*1024*1024)}));assert.equal(fs.existsSync(root+'/oversized.json'),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('replay repairs inode and parent synchronization after successful rename with lost directory sync',{skip:process.getuid()!==0},()=>{const root=fs.mkdtempSync('/run/source-security-sync-');fs.chmodSync(root,0o700);const file=root+'/configuration.json';let renamed=false,failOnce=true,syncs=0;const io=new Proxy(fs,{get(t,k){if(k==='renameSync')return(...args)=>{const result=fs.renameSync(...args);renamed=true;return result;};if(k==='fsyncSync')return fd=>{syncs++;if(renamed&&failOnce){failOnce=false;throw new Error('lost directory sync');}return fs.fsyncSync(fd);};return t[k];}});const files=createOwnedSourceSecurityFiles({io});try{assert.throws(()=>files.publish(file,{value:'retained'}));assert.equal(fs.existsSync(file),true);const before=syncs;files.publish(file,{value:'retained'});assert.ok(syncs>=before+2);const beforeDirectory=syncs;files.directory(root);assert.ok(syncs>beforeDirectory);assert.deepEqual(files.read(file),{value:'retained'});}finally{fs.rmSync(root,{recursive:true,force:true});}});
