import {validateOwnedN8nCloudPlan} from '../packages/zola-release/owned-n8n-cloud-workflow.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {expired8Fixture} from './helpers/owned-n8n-cloud-expired8-fixture.js';
import {projectExpired8OwnedN8nExecution,validateExpired8OwnedN8nAttempt,validateExpired8OwnedN8nRetirement,retireExpired8OwnedN8nAttempt} from '../packages/zola-release/owned-n8n-cloud-expired8.js';
test('expired ready attempt classification preserves all original record bytes',()=>{const f=expired8Fixture(),before=JSON.stringify(f.records),r=validateExpired8OwnedN8nAttempt(f.records);assert.equal(r.classification,'EXPIRED8_BEFORE_REQUEST');assert.equal(r.positiveProof,false);assert.equal(JSON.stringify(f.records),before);});
test('late401 retirement retains safe projections and raw digests and never claims credential mismatch or proof',async()=>{const f=expired8Fixture(),before=JSON.stringify(f.records),r=await retireExpired8OwnedN8nAttempt(f.records,f);assert.equal(r.classification,'EXPIRED_AND_CLEANED_BEFORE_TWO_LATE_EXECUTIONS');assert.equal(r.positiveProof,false);assert.equal(r.originalOutcome,'UNKNOWN');assert.equal(r.administrativeReassertionStatus,405);assert.deepEqual(f.rows.get('observation').executions,f.executions.map(e=>projectExpired8OwnedN8nExecution(f.records,e)));assert.equal(JSON.stringify(f.records),before);assert.equal(validateExpired8OwnedN8nRetirement(f.records,{observation:f.rows.get('observation'),intent:f.rows.get('intent'),result:r}).executionsDigest,r.executionsDigest);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('unknown DELETE adopts only404 and never repeats DELETE even after execution cascade',async()=>{const f=expired8Fixture();f.setUnknownDelete();await assert.rejects(retireExpired8OwnedN8nAttempt(f.records,f));assert.equal(f.rows.has('result'),false);const count=f.calls.length;await retireExpired8OwnedN8nAttempt(f.records,f);assert.deepEqual(f.calls.slice(count).map(c=>c.method),['GET']);assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});
test('missing cleanup, positive or negative verifier receipt, altered supervisor and foreign graph refuse',async()=>{for(const mutate of [f=>f.records['cleanup-result']=null,f=>f.records['server-receipt']={},f=>f.records['server-rejection']={},f=>f.records['supervisor-intent'].argumentsDigest='0'.repeat(64),f=>f.records['workflow-created'].workflow.nodes[1].parameters.url='https://foreign.invalid']){const f=expired8Fixture();mutate(f);await assert.rejects(retireExpired8OwnedN8nAttempt(f.records,f));assert.equal(f.calls.length,0);}});
test('late execution exactidentity/error/projection, inventory closure and historical exit order are mandatory',async()=>{for(const mutate of [f=>f.execution.id='3',f=>f.executions[1].id='4',f=>f.executions[1].startedAt=f.records.plan.expiresAt,f=>f.executions[1].data.resultData.error.httpCode='403',f=>f.executionInventory.body.data.pop(),f=>f.execution.startedAt=f.records.plan.expiresAt,f=>f.execution.status='success',f=>f.execution.usedPrivateCredentials=true,f=>f.execution.data.resultData.error.httpCode='403',f=>f.execution.data.resultData.runData['Verify stored credential'][0].error.httpCode='200',f=>f.execution.workflowData.nodes[1].parameters.sendHeaders=true,f=>f.executionInventory.body.data.push(f.executionInventory.body.data[0]),f=>f.executionInventory.body.nextCursor='more',f=>f.local.supervisorExitedAt='2026-09-22T00:33:00.000Z',f=>f.local.listenerAbsent=false]){const f=expired8Fixture();mutate(f);await assert.rejects(retireExpired8OwnedN8nAttempt(f.records,f));assert.equal(f.calls.some(c=>c.method==='DELETE'),false);}});
test('retained observation tamper refuses reconciliation without another deletion',async()=>{const f=expired8Fixture();await retireExpired8OwnedN8nAttempt(f.records,f);f.rows.get('observation').executions[0].httpCode='200';await assert.rejects(retireExpired8OwnedN8nAttempt(f.records,f));assert.equal(f.calls.filter(c=>c.method==='DELETE').length,1);});

test('raw error detail never retained and drift before delete stops mutation',async()=>{
 const f=expired8Fixture();f.execution.data.resultData.error.request={syntheticSensitiveDetail:'must-not-retain'};
 await retireExpired8OwnedN8nAttempt(f.records,f);assert.equal(JSON.stringify(f.rows.get('observation')).includes('must-not-retain'),false);
 const g=expired8Fixture(),request=g.request;let n=0;g.request=async(method,path)=>{if(path==='/api/v1/executions/5?includeData=true'&&++n===2)g.executions[1].data.resultData.error.message='drift';return request(method,path);};
 await assert.rejects(retireExpired8OwnedN8nAttempt(g.records,g));assert.equal(g.calls.some(c=>c.method==='DELETE'),false);
});

test('ninth plan requires its own expiry lineage and older plans reject it',()=>{
 const p=expired8Fixture().records.plan;assert.throws(()=>validateOwnedN8nCloudPlan({...p,attempt:9}));
 assert.equal(validateOwnedN8nCloudPlan({...p,attempt:9,predecessorEighthExpiryDigest:'e'.repeat(64)}).attempt,9);
 assert.throws(()=>validateOwnedN8nCloudPlan({...p,predecessorEighthExpiryDigest:'e'.repeat(64)}));
});
