import test from 'node:test';import assert from 'node:assert/strict';
import {prepareOwnedSuccessorFinalInputs} from '../packages/zola-release/owned-successor-final-inputs.js';
const sha='a'.repeat(40),op='11111111-1111-4111-8111-111111111111';
function fixture(){const records=new Map(),effects=[],snapshot={profile:'fixed',held:'original',artifact:'new'};let generated=0;const host={snapshot:async()=>structuredClone(snapshot),read:n=>records.get(n)??null,publish(n,v){if(records.has(n))assert.deepEqual(records.get(n),v);records.set(n,structuredClone(v));},async execute(stage,plan,results){effects.push(stage);assert.equal(plan.operationId,op);if(stage==='input')return {productionInputFile:'/fixed/new-input.json',successorLineageFile:'/fixed/'+op+'/plan.json'};return{stage};},async verify(stage,plan,results,value){if(stage!=='input')assert.equal(value.stage,stage);}};return{host,records,effects,snapshot,generateOperationId:()=>{generated++;return op;},generated:()=>generated};}
test('one retained operation spans preparation and read-only preflight without lineage or preview dependency',async()=>{const f=fixture();const r=await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);assert.equal(r.operationId,op);assert.equal(r.lineageRequired,true);assert.equal(r.activationReady,false);assert.deepEqual(f.effects,['workflow','bundle','backup','input']);const writes=f.host.publish;f.host.publish=()=>assert.fail('inspect wrote');assert.equal((await prepareOwnedSuccessorFinalInputs({releaseSha:sha,inspect:true},f)).status,'OWNED_SUCCESSOR_FINAL_INPUTS_VERIFIED');f.host.publish=writes;await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);assert.equal(f.generated(),1);assert.equal(f.effects.length,4);});
test('unknown backup result preserves intent and refuses a second online capture',async()=>{const f=fixture(),execute=f.host.execute;f.host.execute=async(...args)=>{const v=await execute(...args);if(args[0]==='backup')throw Error('lost backup ACK');return v;};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));f.host.execute=execute;await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));assert.equal(f.effects.filter(x=>x==='backup').length,1);assert.equal(f.generated(),1);});
test('profile, source or HELD witness drift refuses resumed effects',async()=>{const f=fixture();await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);f.snapshot.held='changed';await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));assert.equal(f.effects.length,4);});
test('missing predecessor/new operation and contradictory result bindings refuse',async()=>{let f=fixture();await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha,inspect:true},f));assert.equal(f.generated(),0);await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:'2636a1e75cd0f422aff036dfee8a93a81cd5008b'},f));f=fixture();await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},{...f,generateOperationId:()=> '95a11ea1-289f-46a9-b5cd-cc7805497242'}));assert.equal(f.records.size,0);f=fixture();await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);f.records.get('backup.result.json').planDigest='bad';await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));});
test('snapshot drift after an effect leaves its intent and prevents later effects',async()=>{const f=fixture(),execute=f.host.execute;f.host.execute=async(...args)=>{const v=await execute(...args);f.snapshot.profile='drift';return v;};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha},f));assert.deepEqual(f.effects,['workflow']);assert.equal(f.records.has('workflow.result.json'),false);});
test('failed retained artifact/backup observation cannot pass preflight',async()=>{const f=fixture();await prepareOwnedSuccessorFinalInputs({releaseSha:sha},f);f.host.verify=async stage=>{if(stage==='backup')throw Error('invalid backup');};await assert.rejects(prepareOwnedSuccessorFinalInputs({releaseSha:sha,inspect:true},f));assert.equal(f.effects.length,4);});
