import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {prepareOwnedSuccessorGatewayUnit as prepare,installOwnedSuccessorGatewayUnit as install,observeOwnedSuccessorGatewayUnit as observe,readOwnedSuccessorGatewayUnitReceipt as receipt} from '../packages/buyer-writer/owned-successor-gateway-unit.js';
import {encodeGatewayPreparedState,renderGatewayUnit,GATEWAY_SERVICE} from '../packages/buyer-writer/gateway-installation.js';
import {PARTIAL_RELEASE as P} from '../packages/zola-release/partial-retirement-history.js';
import {hash as journalHash} from '../packages/zola-release/commander-journal.js';
import {publishOwnedConfigurationBytes} from '../packages/zola-release/owned-buyer-configuration-host.js';
const hash=v=>createHash('sha256').update(v).digest('hex'),json=v=>JSON.stringify(v)+'\n';
const template=fs.readFileSync(new URL('../ops/runtime-ownership/blackspire-buyer-writer-gateway.service',import.meta.url),'utf8');
function fixture(){
 const root=fs.mkdtempSync('/run/owned-unit-test-'),releaseSha='a'.repeat(40),operationId='11111111-1111-4111-8111-111111111111',attemptId='22222222-2222-4222-8222-222222222222',d='c'.repeat(64);
 const input={releaseSha,operationId,attemptId,profileDigest:P.profileDigest,successorLineageFile:`/var/lib/blackspire-operator/owned-migration-successors/${operationId}/plan.json`};
 const paths={current:root+'/current',root:root+'/receipts',releases:root+'/releases',unit:root+'/gateway.service',oldState:root+'/old-state.json',retirement:root+'/retirement.json'};
 const put=(p,bytes,mode=0o600)=>{fs.mkdirSync(path.dirname(p),{recursive:true,mode:0o700});fs.writeFileSync(p,bytes,{mode});};
 for(const sha of [P.releaseSha,releaseSha])put(paths.releases+'/'+sha+'/ops/runtime-ownership/'+GATEWAY_SERVICE,template,0o644);
 fs.symlinkSync(paths.releases+'/'+P.releaseSha,paths.current);
 const old=renderGatewayUnit(template,{sha:P.releaseSha}),next=renderGatewayUnit(template,{sha:releaseSha});put(paths.unit,old,0o644);
 put(paths.oldState,encodeGatewayPreparedState({sha:P.releaseSha,unitBackup:null,previousUnit:null,installedUnit:old,artifactDigest:d,configurationSha256:d}));
 const proof={version:1,runId:P.runId,currentSha:P.releaseSha,hostStopped:true,bindingAbsent:true,retainedEffects:true,n8nJournalDigest:P.n8nJournalDigest,stopPlanDigest:d,stopResultDigest:d,lineageDigest:d};
 const retirement={schema:5,type:'sequence_retired',operationId:P.operationId,releaseSha:P.releaseSha,attemptId:P.attemptId,ordinal:5,stage:'admission_lease',prefixDigest:P.prefixDigest,segmentDigest:P.segmentDigest,successorReleaseSha:releaseSha,successorOperationId:operationId,backendProfile:'owned-postgres-v1',profileDigest:P.profileDigest,proof,proofDigest:journalHash(proof)};put(paths.retirement,json(retirement));
 let stopped=true,reloaded=false,failReload=false,renames=0,reloads=0,profileVersion=1,state={version:1,mode:'held',releaseSha:P.releaseSha,runId:P.runId,apiGeneration:null,workerGeneration:null};
 const deps={paths,artifactGid:0,verifyRetirement:async()=>retirement,profileSnapshot:()=>({identity:{uid:0,gid:0,mode:0o600,ino:profileVersion},value:{}}),profileDigest:()=>P.profileDigest,
 held:()=>state,verifySuccessorHeld:(_i,s)=>s.runId===attemptId,stopped:async()=>{if(!stopped)throw Error('running');},
 observeLineage:async()=>({status:'OWNED_MIGRATION_SUCCESSOR_VERIFIED',releaseSha,operationId,profileDigest:P.profileDigest,lineageDigest:d,sourceWritesDenied:true,targetBrowserSecurityVerified:true,dataCopied:false,hardeningReapplied:false}),
 inspectDeployed:async({releaseSha})=>({releaseSha,artifactDigest:d,environment:'production'}),inspectSealed:async({releaseSha})=>({releaseSha,artifactDigest:d,environment:'production',status:'SEALED_ARTIFACT_VERIFIED',deployed:false,productionAccepted:false}),
 publish:(p,b,a,o)=>{if(fs.readFileSync(p,'utf8')!==a)renames++;publishOwnedConfigurationBytes(p,b,a,o);},run:args=>{if(args[0]==='daemon-reload'){reloads++;reloaded=true;if(failReload){failReload=false;throw Error('lost reload ACK');}return '';}
 assert.equal(args[0],'show');assert.equal(args[1],GATEWAY_SERVICE);return `LoadState=loaded\nFragmentPath=${paths.unit}\nDropInPaths=\nNeedDaemonReload=${reloaded?'no':'yes'}\nWorkingDirectory=/opt/blackspire-command/releases/${reloaded?releaseSha:P.releaseSha}`;}};
 return {root,input,paths,deps,old,next,put,setStopped:v=>stopped=v,setReloadFailure:()=>failReload=true,setRunning:()=>{fs.unlinkSync(paths.current);fs.symlinkSync(paths.releases+'/'+releaseSha,paths.current);stopped=false;state={...state,releaseSha,runId:attemptId};},driftProfile:()=>profileVersion++,counts:()=>({renames,reloads}),close:()=>fs.rmSync(root,{recursive:true,force:true})};
}
test('real protected predecessor to successor unit, no old receipt edits; running observer does no effects',async()=>{const f=fixture();try{const before=fs.readFileSync(f.paths.oldState),plan=await prepare(f.input,f.deps);assert.equal(fs.readFileSync(f.paths.unit,'utf8'),f.old);const result=await install(plan);assert.equal(result.status,'OWNED_SUCCESSOR_GATEWAY_UNIT_VERIFIED');assert.equal(fs.readFileSync(f.paths.unit,'utf8'),f.next);assert.deepEqual(fs.readFileSync(f.paths.oldState),before);f.setRunning();assert.deepEqual(await observe(f.input,f.deps),result);assert.deepEqual(f.counts(),{renames:1,reloads:1});await assert.rejects(()=>prepare(f.input,f.deps));}finally{f.close();}});
test('lost rename acknowledgement and reload acknowledgement reconstruct exact retained plan without second rename',async()=>{const f=fixture();try{const publish=f.deps.publish;let once=true;f.deps.publish=(...a)=>{publish(...a);if(once){once=false;throw Error('lost rename ACK');}};const plan=await prepare(f.input,f.deps);await assert.rejects(()=>install(plan));assert.equal(fs.readFileSync(f.paths.unit,'utf8'),f.next);f.setReloadFailure();await assert.rejects(()=>install(plan));const resumed=await prepare(f.input,f.deps);await install(resumed);assert.deepEqual(f.counts(),{renames:1,reloads:1});}finally{f.close();}});
test('foreign live unit or retirement/profile drift rejects without writes or reload',async()=>{for(const kind of ['unit','retirement','profile']){const f=fixture();try{const plan=await prepare(f.input,f.deps);if(kind==='unit')f.put(f.paths.unit,'foreign\n',0o644);if(kind==='retirement')f.put(f.paths.retirement,'{}\n');if(kind==='profile')f.driftProfile();await assert.rejects(()=>install(plan));assert.deepEqual(f.counts(),{renames:0,reloads:0});}finally{f.close();}}});
test('wrong old HELD run, foreign profile, nonstopped host and missing retirement reject preparation',async()=>{for(const kind of ['run','profile','running','retirement']){const f=fixture();try{if(kind==='run')f.deps.held=()=>({version:1,mode:'held',releaseSha:P.releaseSha,runId:f.input.attemptId,apiGeneration:null,workerGeneration:null});if(kind==='profile')f.deps.profileDigest=()=> '0'.repeat(64);if(kind==='running')f.setStopped(false);if(kind==='retirement')f.deps.verifyRetirement=async()=>({});await assert.rejects(()=>prepare(f.input,f.deps));assert.deepEqual(f.counts(),{renames:0,reloads:0});}finally{f.close();}}});

test('postmerge receipt selects completed successor authority and retains all predecessor dependencies',async()=>{const f=fixture();try{const p=await prepare(f.input,f.deps);await install(p);const request={releaseSha:f.input.releaseSha,operationId:f.input.operationId,artifactDigest:'c'.repeat(64)},proof=receipt(request,{paths:f.paths});assert.equal(proof.status,'OWNED_SUCCESSOR_GATEWAY_UNIT_RECEIPT_VERIFIED');assert.equal(proof.installedUnitSha256,hash(f.next));assert.equal(proof.dependencies.length,5);assert.throws(()=>receipt({...request,artifactDigest:'d'.repeat(64)},{paths:f.paths}));const filename=f.paths.root+'/'+f.input.operationId+'/result.json';const value=JSON.parse(fs.readFileSync(filename));value.attemptId=P.attemptId;f.put(filename,json(value));assert.throws(()=>receipt(request,{paths:f.paths}));}finally{f.close();}});
test('unexpected loaded fragment or dropins refuse before unit replacement/reload',async()=>{for(const key of ['FragmentPath','DropInPaths']){const f=fixture();try{const run=f.deps.run;f.deps.run=args=>run(args).replace(key+'='+(key==='FragmentPath'?f.paths.unit:''),key+'=/foreign');const plan=await prepare(f.input,f.deps);await assert.rejects(()=>install(plan));assert.deepEqual(f.counts(),{renames:0,reloads:0});}finally{f.close();}}});

test('completed observation requires stopped sealed phase before pointer switch, then deployed proof only',async()=>{const f=fixture();try{let deployed=false,sealedReads=0,deployedReads=0;f.deps.inspectSealed=async({releaseSha})=>{assert.equal(deployed,false);sealedReads++;return{releaseSha,artifactDigest:'c'.repeat(64),environment:'production',status:'SEALED_ARTIFACT_VERIFIED',deployed:false,productionAccepted:false};};f.deps.inspectDeployed=async({releaseSha})=>{if(releaseSha===f.input.releaseSha){deployedReads++;if(!deployed)throw Error('deployment absent');}return{releaseSha,artifactDigest:'c'.repeat(64),environment:'production'};};const p=await prepare(f.input,f.deps);await install(p);const before=sealedReads;await observe(f.input,f.deps);assert.equal(sealedReads,before+1);assert.equal(deployedReads,0);f.setStopped(false);await assert.rejects(()=>observe(f.input,f.deps));f.setRunning();await assert.rejects(()=>observe(f.input,f.deps));assert.equal(sealedReads,before+1);deployed=true;await observe(f.input,f.deps);assert.equal(sealedReads,before+1);assert.equal(deployedReads,2);assert.deepEqual(f.counts(),{renames:1,reloads:1});}finally{f.close();}});
