import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {once} from 'node:events';
import {createOwnedN8nCloudVerifier,renderOwnedN8nCloudProxy,cloudProofHash} from '../packages/zola-release/owned-n8n-cloud-verifier.js';
async function fixture(t){let clock=Date.parse('2026-09-21T20:00:00Z'),completed=0,fences=0;const records=[],key='z'.repeat(43),plan={challenge:'a'.repeat(64),path:'/__zola_credential_proof/'+'a'.repeat(64),receiptId:'11111111-1111-4111-8111-111111111111',expiresAt:new Date(clock+60000).toISOString()};let fence=async()=>{fences++;};const server=http.createServer(createOwnedN8nCloudVerifier({plan,key,record:r=>records.push(r),fence:()=>fence(),now:()=>clock,complete:()=>{completed++;}}));server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise(resolve=>server.close(resolve)));
 const request=({headers=['Host','jarvis.blackspirehelix.com','x-buyer-writer-key',key],method='GET',path=plan.path}={})=>new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:server.address().port,path,method,headers,agent:false},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString())}));});req.on('error',reject);req.end();});
 return {plan,key,records,request,completed:()=>completed,fences:()=>fences,setClock:v=>clock=v,setFence:v=>fence=v};
}
test('actual loopback verifier denies missing wrong duplicate headers and accepts exactly one correct request',async t=>{const f=await fixture(t);for(const headers of [['Host','jarvis.blackspirehelix.com'],['Host','jarvis.blackspirehelix.com','x-buyer-writer-key','q'.repeat(43)],['Host','jarvis.blackspirehelix.com','x-buyer-writer-key',f.key,'X-Buyer-Writer-Key',f.key]])assert.equal((await f.request({headers})).status,404);assert.equal(f.records.length,0);const r=await f.request();assert.equal(r.status,200);assert.deepEqual(r.body,{version:1,status:'CREDENTIAL_POSSESSION_VERIFIED',challenge:f.plan.challenge,receiptId:f.plan.receiptId});assert.equal(f.records.length,1);assert.equal(f.records[0].planDigest,cloudProofHash(f.plan));assert.equal(f.completed(),1);assert.equal(f.fences(),2);assert.equal((await f.request()).status,404);assert.equal(f.records.length,1);assert.equal(JSON.stringify([...f.records,r]).includes(f.key),false);});
test('actual loopback wrong host path method or request body refuses without receipt',async t=>{const f=await fixture(t);for(const options of [{headers:['Host','foreign.invalid','x-buyer-writer-key',f.key]},{path:f.plan.path+'?extra=1'},{method:'POST'},{headers:['Host','jarvis.blackspirehelix.com','x-buyer-writer-key',f.key,'Content-Length','1']}])assert.equal((await f.request(options)).status,404);assert.equal(f.records.length,0);});
test('expiry during awaited fence consumes challenge without success and invokes cleanup',async t=>{const f=await fixture(t);f.setFence(async()=>f.setClock(Date.parse(f.plan.expiresAt)));assert.equal((await f.request()).status,404);assert.equal(f.records.length,0);assert.equal(f.completed(),1);assert.equal((await f.request()).status,404);});
test('concurrent correct requests yield one durable receipt and one finish callback',async t=>{const f=await fixture(t);let unblock,entered;const wait=new Promise(resolve=>{unblock=resolve;}),started=new Promise(resolve=>{entered=resolve;});let calls=0;f.setFence(async()=>{if(++calls===1){entered();await wait;}});const a=f.request();await started;const b=await f.request();assert.equal(b.status,404);unblock();assert.equal((await a).status,200);assert.equal(f.records.length,1);assert.equal(f.completed(),1);});
test('proxy render binds exact retained bytes and exposes only fixed challenge location without request logs',()=>{const before='server {\n    location ~ /\\. { deny all; }\n}\n',plan={challenge:'a'.repeat(64),path:'/__zola_credential_proof/'+'a'.repeat(64),proxyBeforeDigest:cloudProofHash(before)};const result=renderOwnedN8nCloudProxy(before,plan);assert.ok(result.includes('location = '+plan.path));assert.ok(result.includes('access_log off;'));assert.ok(result.includes('proxy_pass http://127.0.0.1:18947;'));assert.throws(()=>renderOwnedN8nCloudProxy(before+' ',plan));assert.throws(()=>renderOwnedN8nCloudProxy(before,{...plan,path:'/arbitrary'}));});
