import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareOwnedMigrationSuccessor,observeOwnedMigrationSuccessor,observeOwnedMigrationPreparationHeld,verifyOwnedMigrationSuccessorSource,ownedMigrationSuccessorFile,OWNED_MIGRATION_PREDECESSOR as P,OWNED_MIGRATION_PREDECESSOR_RECORD_DIGESTS as D} from '../packages/buyer-writer/owned-migration-successor.js';
function fixture(){const request={releaseSha:'a'.repeat(40),operationId:'11111111-2222-4333-8444-555555555555',profileDigest:P.profileDigest},records=new Map(),calls=[];
 const original={status:'OWNED_MIGRATION_PREREQUISITES_VERIFIED',releaseSha:P.releaseSha,operationId:P.operationId,profileDigest:P.profileDigest,sourceSecurityManifestDigest:P.sourceSecurityManifestDigest,copyManifestDigest:P.copyManifestDigest,targetHardeningBodySha256:P.targetHardeningBodySha256,sourceWritesDenied:true,targetBrowserSecurityVerified:true,originalSourceMigrationsReapplied:false};
 const deps={uid:()=>0,openGlobal:()=>({close:()=>calls.push('close')}),observePreparationHeld:async()=>({fixedHeldProof:true}),verifySource:sha=>assert.equal(sha,request.releaseSha),readProfile:()=>({}),profileDigest:()=>P.profileDigest,captureRecords:()=>({...D}),files:{read:p=>records.get(p)??null,directory:()=>calls.push('directory'),publish:(p,v)=>{if(records.has(p))assert.deepEqual(records.get(p),v);records.set(p,structuredClone(v));calls.push('publish');}},observePredecessor:async(bound,{verifySource})=>{assert.equal(bound.releaseSha,P.releaseSha);assert.equal(bound.operationId,P.operationId);verifySource(P.releaseSha);calls.push('observe');return structuredClone(original);}};
 return{request,records,calls,original,deps};}
test('successor preserves original identities and receipts, observer is read-only and rechecks current security',async()=>{const f=fixture(),proof=await prepareOwnedMigrationSuccessor(f.request,f.deps);assert.equal(proof.status,'OWNED_MIGRATION_SUCCESSOR_VERIFIED');assert.equal(proof.predecessorReleaseSha,P.releaseSha);assert.equal(proof.dataCopied,false);assert.equal(proof.hardeningReapplied,false);assert.equal(f.records.size,2);const before=JSON.stringify([...f.records]),writes=f.calls.filter(v=>v==='publish').length;assert.deepEqual(await observeOwnedMigrationSuccessor(f.request,f.deps),proof);assert.equal(JSON.stringify([...f.records]),before);assert.equal(f.calls.filter(v=>v==='publish').length,writes);f.original.sourceWritesDenied=false;await assert.rejects(observeOwnedMigrationSuccessor(f.request,f.deps));});
test('wrong predecessor/profile/path and missing prepared lineage refuse',async()=>{for(const change of [{releaseSha:P.releaseSha},{operationId:P.operationId},{profileDigest:'b'.repeat(64)},{sourceSecurityConfigurationFile:'/other'},{successorLineageFile:'/other'}]){const f=fixture();await assert.rejects(prepareOwnedMigrationSuccessor({...f.request,...change},f.deps));assert.equal(f.records.size,0);}const f=fixture();await assert.rejects(observeOwnedMigrationSuccessor(f.request,f.deps));assert.equal(f.calls.includes('observe'),false);});
test('original record or native proof drift refuses before publication',async()=>{const f=fixture();f.deps.captureRecords=()=>({...D,hardeningPlanFile:'0'.repeat(64)});await assert.rejects(prepareOwnedMigrationSuccessor(f.request,f.deps));assert.equal(f.calls.includes('observe'),false);for(const change of [{copyManifestDigest:'0'.repeat(64)},{operationId:'11111111-1111-4111-8111-111111111111'},{targetBrowserSecurityVerified:false}]){const g=fixture();Object.assign(g.original,change);await assert.rejects(prepareOwnedMigrationSuccessor(g.request,g.deps));assert.equal(g.records.size,0);}});
test('lost publication acknowledgment resumes exact records without replaying migration',async()=>{const f=fixture(),publish=f.deps.files.publish;let once=true;f.deps.files.publish=(p,v)=>{publish(p,v);if(once){once=false;throw Error('sync interrupted');}};await assert.rejects(prepareOwnedMigrationSuccessor(f.request,f.deps));assert.equal(f.records.size,1);const result=await prepareOwnedMigrationSuccessor(f.request,f.deps);assert.equal(result.status,'OWNED_MIGRATION_SUCCESSOR_VERIFIED');assert.equal(f.calls.filter(v=>v==='observe').length,2);const file=ownedMigrationSuccessorFile(f.request.operationId);f.records.get(file).predecessor.operationId=f.request.operationId;await assert.rejects(observeOwnedMigrationSuccessor(f.request,f.deps));});
test('source provenance requires published clean successor and fixed predecessor ancestry',()=>{const calls=[];verifyOwnedMigrationSuccessorSource('a'.repeat(40),{root:'/fixture',verify:(...v)=>calls.push(v),run:(...v)=>calls.push(v)});assert.equal(calls[0][0],'a'.repeat(40));assert.ok(calls[2][1].includes('--is-ancestor'));assert.ok(calls[2][1].includes(P.releaseSha));assert.throws(()=>verifyOwnedMigrationSuccessorSource('a'.repeat(40),{verify(){throw Error('not published');}}));});

test('preparation refuses changed HELD proof before publication while observer never inspects old lifecycle',async()=>{const f=fixture();let n=0;f.deps.observePreparationHeld=async()=>({generation:++n});await assert.rejects(prepareOwnedMigrationSuccessor(f.request,f.deps));assert.equal(f.records.size,0);const g=fixture();await prepareOwnedMigrationSuccessor(g.request,g.deps);g.deps.observePreparationHeld=async()=>{throw Error('old services stopped');};assert.equal((await observeOwnedMigrationSuccessor(g.request,g.deps)).status,'OWNED_MIGRATION_SUCCESSOR_VERIFIED');});

test('native preparation HELD comparison pins epoch, marker and journal process generations',async()=>{const runId='3502c7e8-896e-49e3-bd58-618fe86d2b1c',state={version:1,mode:'held',releaseSha:P.releaseSha,runId,apiGeneration:null,workerGeneration:null},proof={releaseSha:P.releaseSha,runId,artifactDigest:'a'.repeat(64),api:{role:'api',generation:'a'.repeat(32),pid:101,startTime:'123'},worker:{role:'worker',generation:'b'.repeat(32),pid:102,startTime:'124'}},journal={stream:()=>({events:()=>[{type:'release_lifecycle_result',releaseSha:P.releaseSha,runId,proof}]})},deps={readState:()=>structuredClone(state),observe:async()=>structuredClone(proof)};assert.deepEqual(await observeOwnedMigrationPreparationHeld(journal,deps),proof);state.mode='open';await assert.rejects(observeOwnedMigrationPreparationHeld(journal,deps));state.mode='held';deps.observe=async()=>({...proof,api:{...proof.api,pid:103}});await assert.rejects(observeOwnedMigrationPreparationHeld(journal,deps));});
