import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {once} from 'node:events';
import {createOwnedN8nCloudVerifierAttempt2,createOwnedN8nCloudVerifierAttempt3,createOwnedN8nCloudVerifierAttempt4,createOwnedN8nCloudVerifierAttempt5,createOwnedN8nCloudVerifierAttempt6,createOwnedN8nCloudVerifierAttempt7,createOwnedN8nCloudVerifierAttempt8,cloudProofHash} from '../packages/zola-release/owned-n8n-cloud-verifier.js';
async function fixture(t,{typeFault=false,attempt=2}={}){let clock=Date.parse('2026-09-21T23:00:00Z'),completed=0;const records=[],rejections=[],key='z'.repeat(43),plan={attempt,challenge:'a'.repeat(64),path:'/__zola_credential_proof/'+'a'.repeat(64),receiptId:'11111111-1111-4111-8111-111111111111',expiresAt:new Date(clock+60000).toISOString()};let fence=async()=>{};const handler=(attempt===8?createOwnedN8nCloudVerifierAttempt8:attempt===7?createOwnedN8nCloudVerifierAttempt7:attempt===6?createOwnedN8nCloudVerifierAttempt6:attempt===5?createOwnedN8nCloudVerifierAttempt5:attempt===4?createOwnedN8nCloudVerifierAttempt4:attempt===3?createOwnedN8nCloudVerifierAttempt3:createOwnedN8nCloudVerifierAttempt2)({plan,key,record:r=>records.push(r),rejectRecord:r=>rejections.push(r),fence:()=>fence(),now:()=>clock,complete:()=>completed++}),server=http.createServer((req,res)=>{if(typeFault)req.headers['x-buyer-writer-key']=[key];return handler(req,res);});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise(resolve=>server.close(resolve)));
 const request=({headers=['Host','jarvis.blackspirehelix.com','x-buyer-writer-key',key],method='GET',path=plan.path}={})=>new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:server.address().port,path,method,headers,agent:false},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(Buffer.concat(chunks).toString())}));});req.on('error',reject);req.end();});return {plan,key,records,rejections,request,completed:()=>completed,setClock:v=>clock=v,setFence:v=>fence=v};}
function negative(f,code){assert.equal(f.rejections.length,1);assert.deepEqual(Object.keys(f.rejections[0]),['version','kind','attempt','planDigest','code','receivedAt']);assert.equal(f.rejections[0].code,code);assert.equal(f.rejections[0].planDigest,cloudProofHash(f.plan));assert.equal(f.completed(),1);assert.equal(JSON.stringify(f.rejections).includes(f.key),false);}
test('attempt2 real HTTP records only bounded rejection category and permanently consumes first request',async t=>{const cases=[['AUTH_HEADER_MISSING',f=>({headers:['Host','jarvis.blackspirehelix.com']})],['AUTH_HEADER_DUPLICATE',f=>({headers:['Host','jarvis.blackspirehelix.com','x-buyer-writer-key',f.key,'X-Buyer-Writer-Key',f.key]})],['AUTH_LENGTH_MISMATCH',()=>({headers:['Host','jarvis.blackspirehelix.com','x-buyer-writer-key','short']})],['AUTH_VALUE_MISMATCH',()=>({headers:['Host','jarvis.blackspirehelix.com','x-buyer-writer-key','q'.repeat(43)]})],['METHOD',()=>({method:'POST'})],['PATH',f=>({path:f.plan.path+'?extra=1'})],['HOST',f=>({headers:['Host','foreign.invalid','x-buyer-writer-key',f.key]})],['BODY',f=>({headers:['Host','jarvis.blackspirehelix.com','x-buyer-writer-key',f.key,'Content-Length','1']})]];for(const [code,options]of cases){const f=await fixture(t);assert.equal((await f.request(options(f))).status,404);negative(f,code);assert.equal(f.records.length,0);assert.equal((await f.request()).status,404);negative(f,code);}});
test('unsupported header type is categorized after real HTTP parsing without logging the value',async t=>{const f=await fixture(t,{typeFault:true});assert.equal((await f.request()).status,404);negative(f,'AUTH_HEADER_TYPE');});
test('attempt2 correct credential gives exactly one positive receipt and response finish cleanup',async t=>{const f=await fixture(t);const r=await f.request();assert.equal(r.status,200);assert.deepEqual(r.body,{version:1,status:'CREDENTIAL_POSSESSION_VERIFIED',challenge:f.plan.challenge,receiptId:f.plan.receiptId});assert.equal(f.records.length,1);assert.equal(f.records[0].authenticated,true);assert.equal(f.rejections.length,0);assert.equal(f.completed(),1);assert.equal((await f.request()).status,404);assert.equal(f.records.length,1);assert.equal(f.completed(),1);assert.equal(JSON.stringify([r,f.records]).includes(f.key),false);});
test('expiry before request and during either fence is classified and never returns success',async t=>{for(const at of [0,1,2]){const f=await fixture(t);let calls=0;if(at===0)f.setClock(Date.parse(f.plan.expiresAt));else f.setFence(async()=>{if(++calls===at)f.setClock(Date.parse(f.plan.expiresAt));});assert.equal((await f.request()).status,404);negative(f,'EXPIRED');assert.equal(f.records.length,at===2?1:0);assert.equal((await f.request()).status,404);negative(f,'EXPIRED');}});
test('fence failure records sanitized negative even after a retained positive observation',async t=>{for(const at of [1,2]){const f=await fixture(t);let calls=0;f.setFence(async()=>{if(++calls===at)throw Error('private diagnostic '+f.key);});assert.equal((await f.request()).status,404);negative(f,'FENCE_OR_RECEIPT_FAILURE');assert.equal(f.records.length,at===2?1:0);}});
test('attempt2 constructor cannot be used for another attempt',()=>{assert.throws(()=>createOwnedN8nCloudVerifierAttempt2({plan:{attempt:1},key:'z'.repeat(43),rejectRecord:()=>{}}));});

test('monotonic elapsed fence rejects synchronous work that delayed the timeout callback',async()=>{
 const {boundedOwnedN8nCloudFence}=await import('../packages/zola-release/owned-n8n-cloud-verifier.js');
 await assert.rejects(()=>boundedOwnedN8nCloudFence(()=>{const start=performance.now();while(performance.now()-start<20){}return true;},{timeoutMs:5}),/elapsed deadline/);
 assert.equal(await boundedOwnedN8nCloudFence(async()=>true),true);
});

test('attempt3 real HTTP keeps first-request-only proof and rejection bound to fresh attempt',async t=>{for(const valid of [true,false]){const f=await fixture(t,{attempt:3});const r=await f.request(valid?{}:{headers:['Host','jarvis.blackspirehelix.com']});assert.equal(r.status,valid?200:404);assert.equal(f.records.length,valid?1:0);if(!valid){negative(f,'AUTH_HEADER_MISSING');assert.equal(f.rejections[0].attempt,3);}assert.equal((await f.request()).status,404);}assert.throws(()=>createOwnedN8nCloudVerifierAttempt3({plan:{attempt:2},key:'z'.repeat(43),rejectRecord:()=>{}}));});

test('attempt4 real HTTP keeps first-request-only proof and rejection bound to fresh attempt',async t=>{for(const valid of [true,false]){const f=await fixture(t,{attempt:4});const r=await f.request(valid?{}:{headers:['Host','jarvis.blackspirehelix.com']});assert.equal(r.status,valid?200:404);assert.equal(f.records.length,valid?1:0);if(!valid){negative(f,'AUTH_HEADER_MISSING');assert.equal(f.rejections[0].attempt,4);}assert.equal((await f.request()).status,404);}assert.throws(()=>createOwnedN8nCloudVerifierAttempt4({plan:{attempt:2},key:'z'.repeat(43),rejectRecord:()=>{}}));});

test('attempt5 real HTTP keeps first-request-only proof and rejection bound to fresh attempt',async t=>{for(const valid of [true,false]){const f=await fixture(t,{attempt:5});const r=await f.request(valid?{}:{headers:['Host','jarvis.blackspirehelix.com']});assert.equal(r.status,valid?200:404);assert.equal(f.records.length,valid?1:0);if(!valid){negative(f,'AUTH_HEADER_MISSING');assert.equal(f.rejections[0].attempt,5);}assert.equal((await f.request()).status,404);}assert.throws(()=>createOwnedN8nCloudVerifierAttempt5({plan:{attempt:2},key:'z'.repeat(43),rejectRecord:()=>{}}));});

test('attempt6 real HTTP keeps first-request-only proof and rejection bound to fresh attempt',async t=>{for(const valid of [true,false]){const f=await fixture(t,{attempt:6});const r=await f.request(valid?{}:{headers:['Host','jarvis.blackspirehelix.com']});assert.equal(r.status,valid?200:404);assert.equal(f.records.length,valid?1:0);if(!valid){negative(f,'AUTH_HEADER_MISSING');assert.equal(f.rejections[0].attempt,6);}assert.equal((await f.request()).status,404);}assert.throws(()=>createOwnedN8nCloudVerifierAttempt6({plan:{attempt:2},key:'z'.repeat(43),rejectRecord:()=>{}}));});

test('attempt7 real HTTP keeps first-request-only proof and rejection bound to fresh attempt',async t=>{for(const valid of [true,false]){const f=await fixture(t,{attempt:7});const r=await f.request(valid?{}:{headers:['Host','jarvis.blackspirehelix.com']});assert.equal(r.status,valid?200:404);assert.equal(f.records.length,valid?1:0);if(!valid){negative(f,'AUTH_HEADER_MISSING');assert.equal(f.rejections[0].attempt,7);}assert.equal((await f.request()).status,404);}assert.throws(()=>createOwnedN8nCloudVerifierAttempt7({plan:{attempt:2},key:'z'.repeat(43),rejectRecord:()=>{}}));});

test('attempt8 real HTTP keeps first-request-only proof and rejection bound to fresh attempt',async t=>{for(const valid of [true,false]){const f=await fixture(t,{attempt:8});const r=await f.request(valid?{}:{headers:['Host','jarvis.blackspirehelix.com']});assert.equal(r.status,valid?200:404);assert.equal(f.records.length,valid?1:0);if(!valid){negative(f,'AUTH_HEADER_MISSING');assert.equal(f.rejections[0].attempt,8);}assert.equal((await f.request()).status,404);}assert.throws(()=>createOwnedN8nCloudVerifierAttempt8({plan:{attempt:2},key:'z'.repeat(43),rejectRecord:()=>{}}));});
