import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {spawnSync} from 'node:child_process';
import {SUCCESSOR as fixed,successorHash as hash,successorPrefixDigest,inspectSuccessorHistory} from '../packages/zola-six-reads/owned-collector-successor.js';
import {transformSuccessorSource,SOURCE_HASHES,load} from '../packages/zola-six-reads/owned-collector-successor-loader.js';
function fixture(){
 const oldClaims={permitId:'old',tokenDigest:'a'.repeat(64),issuedAt:1,expiresAt:900001,commanderRunId:fixed.operationId,candidateSha:fixed.releaseSha,expectedDeploymentSha:fixed.releaseSha,epochRunId:fixed.runId,workspace:'test',principal:'operator',apiGeneration:'api',workerGeneration:'worker',operations:['six_reads'],reads:[{idempotencyKey:'same'}]};
 const prefix=[{type:'original-fixture',binding:'immutable'}],policy={...fixed,originalReleasePrefixDigest:successorPrefixDigest(prefix)};
 const terminal={schema:2,type:'premerge_observation_failure',attemptId:fixed.attemptId,originalClaimsDigest:fixed.originalClaimsDigest,collectorDigest:fixed.collectorDigest,originalReleasePrefixDigest:policy.originalReleasePrefixDigest,terminalProofDigest:'b'.repeat(64),archiveProofDigest:'c'.repeat(64)};
 const original={intent:{claimsDigest:fixed.originalClaimsDigest,configDigest:fixed.configDigest,claims:oldClaims},active:true,result:null,retired:true};
 const state={pending:{stage:'six_reads',attemptId:fixed.attemptId,inputDigest:'d'.repeat(64),checkOutputDigest:'e'.repeat(64)},nextOrdinal:13,context:{releaseSha:fixed.releaseSha,operationId:fixed.operationId},outputs:{admission_lease:{epochRunId:fixed.runId}}};
 const claims={...oldClaims,permitId:'new',tokenDigest:'f'.repeat(64),issuedAt:900001,expiresAt:1800001};
 const intent={schema:2,type:'premerge_successor_reads_intent',attemptId:fixed.attemptId,inputDigest:state.pending.inputDigest,checkOutputDigest:state.pending.checkOutputDigest,configDigest:fixed.configDigest,claims,claimsDigest:hash(claims),terminalProofDigest:terminal.terminalProofDigest,archiveProofDigest:terminal.archiveProofDigest};
 const event=(type,extra={})=>({schema:2,type:'premerge_successor_reads_'+type,attemptId:fixed.attemptId,claimsDigest:intent.claimsDigest,...extra});
 const evidence={readCount:6,crossOwnerDenials:6,paidProviderCalls:0,mutationDelta:0,collectorDigest:'0'.repeat(64)};
 const events=[...prefix,terminal,intent,event('active'),event('result',{evidence,evidenceDigest:hash(evidence)}),event('retired',{outcome:'PASS'})];
 let originalCalls=[];const deps={inspectOriginal:rows=>{originalCalls.push(rows);assert.deepEqual(rows[0],prefix[0]);return original;},inspectSequence:()=>state,validateClaims:v=>v,identity:()=>true};
 return {events,policy,deps,originalCalls,state,original,event,terminal};
}
test('full original transcript remains UNKNOWN while distinct successor PASS is selected',()=>{const f=fixture(),result=inspectSuccessorHistory(f.events,f.deps,f.policy);assert.equal(result.original.result,null);assert.equal(result.original.retired,true);assert.equal(result.result.evidence.readCount,6);assert.equal(result.retired,true);assert.equal(f.originalCalls[0],f.events);});
test('exact terminal can precede mint but original no-terminal history is not treated as empty',()=>{const f=fixture();assert.equal(inspectSuccessorHistory(f.events.slice(0,2),f.deps,f.policy).intent,null);assert.throws(()=>inspectSuccessorHistory(f.events.slice(0,1),f.deps,f.policy));});
test('successor UNKNOWN remains nonreplayable and cannot acquire fabricated PASS',()=>{const f=fixture();const rows=f.events.slice(0,4);rows.push(f.event('retired',{outcome:'UNKNOWN'}));const result=inspectSuccessorHistory(rows,f.deps,f.policy);assert.equal(result.result,null);assert.equal(result.retired,true);rows.push(f.events[4]);assert.throws(()=>inspectSuccessorHistory(rows,f.deps,f.policy));});
test('rejects reordered, duplicate, unbound or altered terminal and successor events',()=>{
 const mutations=[r=>r[1].archiveProofDigest='bad',r=>r[1].originalReleasePrefixDigest='1'.repeat(64),r=>r.unshift({type:'extra'}),r=>r[2].schema=1,r=>r[2].attemptId='foreign',r=>r[2].configDigest='9'.repeat(64),r=>r[2].archiveProofDigest='9'.repeat(64),r=>r.splice(3,1),r=>r.splice(3,0,structuredClone(r[2])),r=>r.push(structuredClone(r[2])),r=>r[5].outcome='UNKNOWN',r=>r[4].evidence.mutationDelta=1,r=>r.splice(2,0,structuredClone(r[1])),r=>r.push({schema:2,type:'premerge_successor_future'})];
 for(const mutate of mutations){const f=fixture();mutate(f.events);assert.throws(()=>inspectSuccessorHistory(f.events,f.deps,f.policy));}
});
test('same task keys, identities, generations and strictly new post-expiry authority required',()=>{for(const mutate of [c=>c.permitId='old',c=>c.tokenDigest='a'.repeat(64),c=>c.issuedAt=900000,c=>c.epochRunId='foreign',c=>c.reads=[{idempotencyKey:'different'}],c=>c.apiGeneration='new',c=>c.principal='foreign']){const f=fixture();mutate(f.events[2].claims);f.events[2].claimsDigest=hash(f.events[2].claims);assert.throws(()=>inspectSuccessorHistory(f.events,f.deps,f.policy));}});
test('completed or wrong original history and stage fail closed',()=>{for(const change of [f=>f.original.result={},f=>f.original.retired=false,f=>f.state.nextOrdinal=14,f=>f.state.pending.stage='other',f=>f.state.context.operationId='foreign']){const f=fixture();change(f);assert.throws(()=>inspectSuccessorHistory(f.events,f.deps,f.policy));}});
const files={permit:'packages/zola-release/premerge-read-permit.js',commander:'packages/zola-release/commander.js',held:'packages/zola-release/production-held-operations.js',collector:'packages/zola-six-reads/collector-host.js'};
test('all exact source transforms parse, pin original bytes and retain ordinary parser',()=>{for(const [kind,file] of Object.entries(files)){const source=fs.readFileSync(new URL('../'+file,import.meta.url),'utf8');assert.equal(hash(source),SOURCE_HASHES[kind]);const transformed=transformSuccessorSource(kind,source);assert.equal(spawnSync(process.execPath,['--input-type=module','--check'],{input:transformed,encoding:'utf8'}).status,0);assert.throws(()=>transformSuccessorSource(kind,source+' '));if(kind==='permit'){assert.match(transformed,/inspectOriginalPremergeReadHistory\(events\)/);assert.match(transformed,/schema:2,type:'premerge_successor_reads_intent'/);assert.match(transformed,/prior\.result/);assert.match(transformed,/selectSuccessorReceipt\(config\)/);assert.doesNotMatch(transformed.slice(transformed.indexOf('export async function runPremergeReadPermit')),/'premerge_reads_/);}}});
test('loader only intercepts fixed canonical source or installed collector, no frozen source edits',async()=>{const source=fs.readFileSync(new URL('../'+files.permit,import.meta.url),'utf8'),next=async()=>({format:'module',source});assert.equal((await load('file://'+fixed.frozenRoot+'/'+files.permit,{},next)).source,source);assert.notEqual((await load('file://'+fixed.canonicalRoot+'/'+files.permit,{},next)).source,source);await assert.rejects(load('file://'+fixed.canonicalRoot+'/'+files.permit,{},async()=>({format:'commonjs',source})));});
