import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { DatabaseSync } from 'node:sqlite';
import { prepareDisposableDatabase } from './helpers/prepare-disposable-database.js';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'authz-provision-')); const fixture=JSON.parse(fs.readFileSync('tests/fixtures/authz-bootstrap.dev.json','utf8'));
const write=(name,value=fixture)=>{const p=path.join(root,`${name}.json`);fs.writeFileSync(p,JSON.stringify(value));return p;}; const db=(name)=>{const p=path.join(root,`${name}.sqlite`);prepareDisposableDatabase(p);return p;};
const cli=(args,env={})=>spawnSync(process.execPath,['scripts/provision-authz.js',...args],{cwd:process.cwd(),env:{...process.env,...env},encoding:'utf8'}); const count=(p,t)=>{const d=new DatabaseSync(p,{readOnly:true});try{return d.prepare(`SELECT count(*) n FROM ${t}`).get().n;}finally{d.close();}};
test('apply creates only configured principals and grants without session binding and is idempotent',()=>{const p=db('empty'),c=write('good');let r=cli(['--config',c,'--database',p,'--apply']);assert.equal(r.status,0,r.stderr);assert.equal(count(p,'auth_principals'),2);assert.equal(count(p,'auth_workspace_grants'),1);assert.equal(count(p,'sessions'),0);r=cli(['--config',c,'--database',p,'--apply']);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/"principals":0/);assert.equal(count(p,'auth_principals'),2);});
test('conflicts and missing superseded grants fail safely',()=>{const p=db('conflict'),c=write('conflict');assert.equal(cli(['--config',c,'--database',p,'--apply']).status,0);let changed=structuredClone(fixture);changed.principals[0].actor_id='different';let r=cli(['--config',write('principal-conflict',changed),'--database',p,'--apply']);assert.match(r.stderr,/AUTHZ_PRINCIPAL_CONFLICT/);changed=structuredClone(fixture);changed.workspace_grants[0].role='viewer';r=cli(['--config',write('grant-conflict',changed),'--database',p,'--apply']);assert.match(r.stderr,/AUTHZ_GRANT_CONFLICT/);changed=structuredClone(fixture);changed.workspace_grants[0].supersedes_grant_id='missing';r=cli(['--config',write('missing-parent',changed),'--database',p,'--apply']);assert.match(r.stderr,/AUTHZ_CONFIG_INVALID/);});
test('transaction rolls back a later conflict',()=>{const p=db('rollback'),c=structuredClone(fixture);c.principals.push({...fixture.principals[0],principal_id:'other',actor_id:'other'});const d=new DatabaseSync(p);d.prepare('INSERT INTO auth_principals VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('other','admin','wrong','bearer',null,'active',1,null,null,null,1,1);d.close();const r=cli(['--config',write('rollback',c),'--database',p,'--apply']);assert.match(r.stderr,/AUTHZ_PRINCIPAL_CONFLICT/);assert.equal(count(p,'auth_principals'),1);assert.equal(count(p,'auth_workspace_grants'),0);});
test('apply path and mode refusals plus dry modes make no writes and output is sanitized',()=>{const p=db('safe'),c=write('safe');assert.match(cli(['--config',c,'--apply']).stderr,/AUTHZ_DATABASE_REQUIRED/);assert.match(cli(['--config',c,'--database','relative.sqlite','--apply']).stderr,/AUTHZ_DATABASE_REFUSED/);assert.match(cli(['--config',c,'--database',p,'--apply'],{BLACKSPIRE_RUNTIME_MODE:'production'}).stderr,/AUTHZ_PROVISIONING_REFUSED/);const dir=path.join(root,'directory');fs.mkdirSync(dir);assert.match(cli(['--config',c,'--database',dir,'--apply']).stderr,/AUTHZ_DATABASE_REFUSED/);const link=path.join(root,'link.sqlite');fs.symlinkSync(p,link);assert.match(cli(['--config',c,'--database',link,'--apply']).stderr,/AUTHZ_DATABASE_REFUSED/);for(const name of ['shared','production']){const blocked=path.join(root,name);fs.mkdirSync(blocked);const blockedDb=path.join(blocked,'x.sqlite');fs.copyFileSync(p,blockedDb);assert.match(cli(['--config',c,'--database',blockedDb,'--apply']).stderr,/AUTHZ_DATABASE_REFUSED/);}const oversized=path.join(root,'oversized.json');fs.writeFileSync(oversized,' '.repeat(65537));assert.match(cli(['--config',oversized,'--validate-only']).stderr,/AUTHZ_CONFIG_INVALID/);for(const flag of ['--validate-only','--dry-run'])assert.equal(cli(['--config',c,flag]).status,0);assert.equal(count(p,'auth_principals'),0);const r=cli(['--config',c,'--database',p,'--apply']);assert.doesNotMatch(r.stdout,/fixture-admin|credential_reference|authz-provision/);});
