import test from 'node:test';
import assert from 'node:assert/strict';
import {renderOwnedBuyerLocations} from '../packages/zola-release/owned-buyer-nginx.js';
import {preparePublicCommandConfiguration,PUBLIC_COMMAND_MAINTENANCE,PUBLIC_COMMAND_PROXY,ensurePublicCommandRouting,restorePublicCommandRouting} from '../packages/zola-release/public-command-routing.js';
const before=`server {\n    listen 443 ssl;\n    server_name command.blackspirehelix.com;\n    ssl_certificate     /etc/letsencrypt/live/command.blackspirehelix.com/fullchain.pem;\n${renderOwnedBuyerLocations()}    location = /api/internal/capability-authority/consume { return 404; }\n${PUBLIC_COMMAND_MAINTENANCE}\n    error_page 503 @maintenance;\n    location @maintenance { return 503; }\n}\n`;
function fixture(){const records=new Map();let current=before,effects=0,reloads=0,held=true,stopped=true,invalid=false,lost=false;const binding={releaseSha:'a'.repeat(40),newMainSha:'b'.repeat(40),acceptedRecordDigest:'c'.repeat(64)};
 const host={authorize:async()=>binding,requireHeld:async()=>{assert(held);},requireStoppedHeld:async()=>{assert(held&&stopped);return binding;},read:n=>records.get(n),publish(n,v){if(records.has(n))assert.deepEqual(records.get(n),v);else records.set(n,structuredClone(v));},current:()=>current,replace(old,next){assert([old,next].includes(current));current=next;effects++;},validate:async()=>{if(invalid&&current!==before)throw Error('invalid');},reload:async()=>{reloads++;if(lost){lost=false;throw Error('lost reload acknowledgement');}},verify:async()=>{},verifyRestored:async()=>{assert.equal(current,before);}};
 return{host,records,binding,effects:()=>effects,reloads:()=>reloads,current:()=>current,setCurrent:v=>{current=v;},setHeld:v=>{held=v;},invalid:()=>{invalid=true;},loseReload:()=>{lost=true;}};}
test('public route changes only exact maintenance body preserving TLS, callback and eight scoped routes',()=>{const after=preparePublicCommandConfiguration(before);assert.equal(after.replace(PUBLIC_COMMAND_PROXY,PUBLIC_COMMAND_MAINTENANCE),before);assert(after.includes('proxy_set_header X-Forwarded-For $remote_addr;'));assert(after.includes('proxy_next_upstream off;'));assert.throws(()=>preparePublicCommandConfiguration(after));assert.throws(()=>preparePublicCommandConfiguration(before.replace(renderOwnedBuyerLocations(),'')));assert.throws(()=>preparePublicCommandConfiguration(before.replaceAll('command.blackspirehelix.com','foreign.invalid')));});
test('accepted HELD binding precedes effect and completed result observes without reload',async()=>{const f=fixture();await ensurePublicCommandRouting(f);assert(f.records.has('intent'));assert.equal(f.reloads(),1);await ensurePublicCommandRouting(f);assert.equal(f.reloads(),1);const blocked=fixture();blocked.setHeld(false);await assert.rejects(ensurePublicCommandRouting(blocked));assert.equal(blocked.effects(),0);assert.equal(blocked.records.size,0);});
test('unknown reload preserves exact candidate and reconciliation never overwrites foreign bytes',async()=>{const f=fixture();f.loseReload();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.current(),preparePublicCommandConfiguration(before));await ensurePublicCommandRouting(f);assert.equal(f.reloads(),2);f.setCurrent('foreign');await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.current(),'foreign');});
test('validation failure restores exact before bytes and cannot retry a rejected plan',async()=>{const f=fixture();f.invalid();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.current(),before);assert.equal(f.reloads(),0);const effects=f.effects();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.effects(),effects);});
test('explicit restoration requires stopped HELD and keeps other routes unchanged',async()=>{const f=fixture();await ensurePublicCommandRouting(f);await restorePublicCommandRouting(f);assert.equal(f.current(),before);await assert.rejects(ensurePublicCommandRouting(f));const wrong=fixture();await ensurePublicCommandRouting(wrong);wrong.setHeld(false);await assert.rejects(restorePublicCommandRouting(wrong));assert.equal(wrong.current(),preparePublicCommandConfiguration(before));});
