import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const js=fs.readFileSync(new URL('../apps/jarvis-pwa/public/jarvis.js',import.meta.url),'utf8');
function fixture(){const nodes=new Map();const element=()=>({value:'',textContent:'',children:[],append(...v){this.children.push(...v);},replaceChildren(...v){this.children=v;},addEventListener(){},reset(){},focus(){}});const node=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};node('personalFilter').value='all';
 const context={store:{authed:true,principalId:'p',view:'today'},activeWorkspaceId:()=> 'w',byId:node,el:(_tag,_class,text)=>({...element(),textContent:text}),window:{confirm:()=>true},crypto,Date,Intl,api:{request:async()=>({response:{ok:true},body:{items:[],today:{overdue:[],upcoming:[],unfinished:[]}}})}};
 vm.createContext(context);vm.runInContext(js.split('/* Everyday organizer:')[1].split('*/').slice(1).join('*/').split('/* End everyday organizer. */')[0]+'\nglobalThis.state=personalState;',context);return {context,node};}
test('late organizer response cannot repopulate the screen after logout',async()=>{const {context:h,node}=fixture();let finish;h.api.request=()=>new Promise(r=>{finish=r;});const pending=h.refreshPersonalView();h.store.authed=false;await h.refreshPersonalView();finish({response:{ok:true},body:{items:[{title:'private'}],today:{}}});await pending;assert.equal(h.state.rows.length,0);assert.equal(node('personalRows').children.length,0);});
test('unknown save reuses its request ID and blocks a different pending operation',async()=>{const {context:h}=fixture();await h.refreshPersonalView();const requests=[];let attempt=0;h.api.request=async(_url,options)=>{if(!options)return {response:{ok:true},body:{items:[],today:{overdue:[],upcoming:[],unfinished:[]}}};requests.push(JSON.parse(options.body));if(attempt++===0)throw Error('connection lost');return {response:{ok:true},body:{saved:true}};};
 const change={action:'create',item:{kind:'memory',title:'Coffee'}};await h.changePersonal(change);assert.ok(h.state.pending);await h.changePersonal({action:'create',item:{kind:'memory',title:'Different'}});assert.equal(requests.length,1);await h.changePersonal(change);assert.equal(requests[0].requestId,requests[1].requestId);assert.equal(requests[1].workspaceId,'w');assert.equal(h.state.pending,null);
});
test('voice organizer reads recognize everyday wording and never reinterpret a write as a read',()=>{
 const context={};vm.createContext(context);vm.runInContext(js.slice(js.indexOf('function personalReadKind('),js.indexOf('function voiceWorkspaceRequest(')),context);
 for(const [text,kind]of [['What reminders do I have?','reminder'],['Read my saved memories','memory'],['What is on my grocery list?','list'],['Which bills are due?','bill'],['When are my appointments?','appointment']])assert.equal(context.personalReadKind(text),kind);
 for(const text of ['Pay my bills','Add milk to my shopping list','Delete my saved memories','What is the status of our deals?'])assert.equal(context.personalReadKind(text),null);
});
