import fs from 'node:fs';
import {publishOwnedConfigurationBytes,readOwnedConfigurationBytes} from '../packages/zola-release/owned-buyer-configuration-host.js';
import {validatePublicCommandAdmission} from '../packages/zola-release/public-command-routing-host.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {renderOwnedBuyerLocations} from '../packages/zola-release/owned-buyer-nginx.js';
import {preparePublicCommandConfiguration,PUBLIC_COMMAND_MAINTENANCE,PUBLIC_COMMAND_PROXY,ensurePublicCommandRouting,restorePublicCommandRouting} from '../packages/zola-release/public-command-routing.js';
const before=`server {\n    listen 443 ssl;\n    server_name command.blackspirehelix.com;\n    ssl_certificate     /etc/letsencrypt/live/command.blackspirehelix.com/fullchain.pem;\n${renderOwnedBuyerLocations()}    location = /api/internal/capability-authority/consume { return 404; }\n${PUBLIC_COMMAND_MAINTENANCE}\n    error_page 503 @maintenance;\n    location @maintenance { return 503; }\n}\n`;
function fixture(){const records=new Map();let current=before,effects=0,reloads=0,held=true,stopped=true,invalid=false,lost=false;const binding={releaseSha:'a'.repeat(40),newMainSha:'b'.repeat(40),acceptedRecordDigest:'c'.repeat(64)};
 const host={authorize:async()=>binding,requireHeld:async()=>{assert(held);},requireStoppedHeld:async()=>{assert(held&&stopped);return binding;},read:n=>records.get(n),publish(n,v){if(records.has(n))assert.deepEqual(records.get(n),v);else records.set(n,structuredClone(v));},current:()=>current,replace(old,next){assert([old,next].includes(current));current=next;effects++;},validate:async()=>{if(invalid&&current!==before)throw Error('invalid');},reload:async()=>{reloads++;if(lost){lost=false;throw Error('lost reload acknowledgement');}},verify:async()=>{},verifyRestored:async()=>{assert.equal(current,before);}};
 return{host,records,binding,effects:()=>effects,reloads:()=>reloads,current:()=>current,setCurrent:v=>{current=v;},setHeld:v=>{held=v;},invalid:()=>{invalid=true;},loseReload:()=>{lost=true;}};}
test('public route changes only exact maintenance body preserving TLS, callback and eight scoped routes',()=>{const after=preparePublicCommandConfiguration(before);assert.equal(after.replace(PUBLIC_COMMAND_PROXY,PUBLIC_COMMAND_MAINTENANCE),before);assert(after.includes('proxy_set_header X-Forwarded-For $remote_addr;'));assert(after.includes('proxy_next_upstream off;'));assert.throws(()=>preparePublicCommandConfiguration(after));assert.throws(()=>preparePublicCommandConfiguration(before.replace(renderOwnedBuyerLocations(),'')));assert.throws(()=>preparePublicCommandConfiguration(before.replaceAll('command.blackspirehelix.com','foreign.invalid')));});
test('accepted HELD binding precedes effect and completed result observes without reload',async()=>{const f=fixture();await ensurePublicCommandRouting(f);assert(f.records.has('intent'));assert.equal(f.reloads(),1);await ensurePublicCommandRouting(f);assert.equal(f.reloads(),1);const blocked=fixture();blocked.setHeld(false);await assert.rejects(ensurePublicCommandRouting(blocked));assert.equal(blocked.effects(),0);assert.equal(blocked.records.size,0);});
test('unknown reload preserves exact candidate and reconciliation never overwrites foreign bytes',async()=>{const f=fixture();f.loseReload();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.current(),preparePublicCommandConfiguration(before));await ensurePublicCommandRouting(f);assert.equal(f.reloads(),2);f.setCurrent('foreign');await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.current(),'foreign');});
test('validation failure restores exact before bytes and cannot retry a rejected plan',async()=>{const f=fixture();f.invalid();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.current(),before);assert.equal(f.reloads(),0);const effects=f.effects();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.effects(),effects);});
test('explicit restoration requires stopped HELD and keeps other routes unchanged',async()=>{const f=fixture();await ensurePublicCommandRouting(f);await restorePublicCommandRouting(f);assert.equal(f.current(),before);await assert.rejects(ensurePublicCommandRouting(f));const wrong=fixture();await ensurePublicCommandRouting(wrong);wrong.setHeld(false);await assert.rejects(restorePublicCommandRouting(wrong));assert.equal(wrong.current(),preparePublicCommandConfiguration(before));});

test('retained result is republished to repair staged publication and directory synchronization',async()=>{const f=fixture();await ensurePublicCommandRouting(f);let repaired=0;const publish=f.host.publish;f.host.publish=(name,value)=>{if(name==='result')repaired++;publish(name,value);};await ensurePublicCommandRouting(f);assert.equal(repaired,1);assert.equal(f.reloads(),1);f.host.verify=async()=>{f.setCurrent('drift during asynchronous verification');};await assert.rejects(ensurePublicCommandRouting(f));assert.equal(repaired,1);});
test('retained restoration intent blocks normal publication even before bytes are restored',async()=>{const f=fixture();await ensurePublicCommandRouting(f);f.records.set('restore-intent',f.records.get('intent'));const effects=f.effects(),reloads=f.reloads();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.effects(),effects);assert.equal(f.reloads(),reloads);await restorePublicCommandRouting(f);assert.equal(f.current(),before);});

test('accepted HELD generation state allows exact bound pair and rejects mixed or drifted pairs',()=>{const record={epochRunId:'epoch',apiGeneration:'api',workerGeneration:'worker'},state={mode:'held',releaseSha:'main',runId:'epoch',apiGeneration:'api',workerGeneration:'worker'};assert(validatePublicCommandAdmission(state,record,'main',false));assert(validatePublicCommandAdmission({...state,apiGeneration:null,workerGeneration:null},record,'main',false));for(const change of [{apiGeneration:null},{workerGeneration:null},{apiGeneration:'changed'},{workerGeneration:'changed'},{runId:'wrong'},{releaseSha:'wrong'},{mode:'open'}])assert.throws(()=>validatePublicCommandAdmission({...state,...change},record,'main',false));assert(validatePublicCommandAdmission({...state,mode:'open'},record,'main',true));});

test('retained result without its exact preceding intent is refused without effects',async()=>{for(const bad of [null,{version:1,planDigest:'foreign'}]){const f=fixture();await ensurePublicCommandRouting(f);f.records.set('intent',bad);const effects=f.effects();await assert.rejects(ensurePublicCommandRouting(f));assert.equal(f.effects(),effects);}});

test('real protected staged result is promoted and retained final result is resynchronized',{skip:process.getuid()!==0},async t=>{const root=fs.mkdtempSync('/root/zola-routing-test-');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const f=fixture();await ensurePublicCommandRouting(f);const target=root+'/result.json',value=f.records.get('result');fs.writeFileSync(target+'.owned-buyer-stage',JSON.stringify(value)+'\n',{mode:0o600});const read=f.host.read,publish=f.host.publish;f.host.read=name=>name==='result'?JSON.parse(readOwnedConfigurationBytes(target)??readOwnedConfigurationBytes(target+'.owned-buyer-stage')):read(name);f.host.publish=(name,v)=>name==='result'?publishOwnedConfigurationBytes(target,null,JSON.stringify(v)+'\n'):publish(name,v);await ensurePublicCommandRouting(f);assert(fs.existsSync(target));assert(!fs.existsSync(target+'.owned-buyer-stage'));const original=fs.fsyncSync;let syncs=0;fs.fsyncSync=fd=>{syncs++;return original(fd);};try{await ensurePublicCommandRouting(f);}finally{fs.fsyncSync=original;}assert(syncs>=2);assert.equal(f.reloads(),1);});
