import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {hash} from '../packages/zola-release/commander-journal.js';
import {PARTIAL_RELEASE as P,validatePartialReleasePrefix} from '../packages/zola-release/partial-retirement-history.js';
import {partitionRetiredReleaseHistory} from '../packages/zola-release/retired-release-history.js';
import {inspectReleaseCommander} from '../packages/zola-release/commander.js';
import {RELEASE_STAGES,runReleaseSequence,inspectReleaseSequenceHistory} from '../packages/zola-release/commander-sequence.js';
import {inspectCandidateDeploymentHistory} from '../packages/zola-release/candidate-deployment.js';
import {inspectHeldWriterBindingHistory} from '../packages/zola-release/held-writer-binding.js';
import {inspectBuyerWriterActivationHistory} from '../packages/zola-release/buyer-writer-activation.js';
import {inspectCompletedHeldLifecycle} from '../packages/zola-release/held-lifecycle.js';
import {createOwnedN8nRetiredJournalView} from '../packages/zola-release/owned-n8n-retired-journal.js';
const original=JSON.parse(fs.readFileSync(new URL('./fixtures/zola-release/retired-release-2636.json',import.meta.url))),workflow=JSON.parse(fs.readFileSync(new URL('./fixtures/zola-release/retired-release-n8n-2636.json',import.meta.url)));
const successor='a'.repeat(40),newOp='11111111-1111-4111-8111-111111111111',runId='22222222-2222-4222-8222-222222222222';
function event(){const proof={version:1,runId:P.runId,currentSha:P.releaseSha,hostStopped:true,bindingAbsent:true,retainedEffects:true,n8nJournalDigest:P.n8nJournalDigest,stopPlanDigest:'a'.repeat(64),stopResultDigest:'b'.repeat(64),lineageDigest:'c'.repeat(64)};return {schema:5,type:'sequence_retired',operationId:P.operationId,releaseSha:P.releaseSha,attemptId:P.attemptId,ordinal:5,stage:'admission_lease',prefixDigest:P.prefixDigest,segmentDigest:P.segmentDigest,successorReleaseSha:successor,successorOperationId:newOp,backendProfile:'owned-postgres-v1',profileDigest:P.profileDigest,proof,proofDigest:hash(proof)};}
function fixture(){const events=[...structuredClone(original),event()],n8n=structuredClone(workflow);return {events,n8n,journal:{stream:name=>({events:()=>structuredClone(name==='release'?events:n8n),append:row=>(name==='release'?events:n8n).push(structuredClone(row))})}};}
const input={releaseSha:successor,previousMainSha:original[69].previousMainSha,recoverySha:original[69].recoverySha,protectedInputDigest:'d'.repeat(64),workspace:'zola-production',principal:'blackspire-release-root'};input.inputDigest=hash(input);
test('second exact retirement preserves first proof and every historical effect without executable old state',()=>{const f=fixture();assert(validatePartialReleasePrefix(original));assert.deepEqual(f.events.slice(0,116),original);const p=partitionRetiredReleaseHistory(f.events);assert.equal(p.current.length,0);assert.equal(p.prefix[68].schema,4);assert.equal(inspectReleaseSequenceHistory(f.events).started,false);assert.equal(inspectReleaseCommander(f.journal).mutationSent,true);assert.equal(inspectBuyerWriterActivationHistory(f.events).intent,null);assert.equal(inspectCandidateDeploymentHistory(f.events).plan,null);assert.equal(inspectHeldWriterBindingHistory(f.events).size,0);assert.throws(()=>inspectCompletedHeldLifecycle(f.events,P.releaseSha));});
test('altered earlier proof, second prefix, unauthorized third retirement and false containment all refuse',()=>{for(const change of [r=>r[0].releaseSha='b'.repeat(40),r=>r[68].proof.rolesAbsent=false,r=>r[115].reason='OTHER',r=>r[116].segmentDigest='f'.repeat(64),r=>{r[116].proof.hostStopped=false;r[116].proofDigest=hash(r[116].proof);},r=>r.push(structuredClone(r[116])),r=>r.splice(68,1),r=>r[116].profileDigest='f'.repeat(64),r=>r[116].successorOperationId=P.operationId]){const f=fixture();change(f.events);assert.throws(()=>inspectReleaseCommander(f.journal));}});
test('wrong successor operation refuses before any append or adapter effect',async()=>{for(const operationId of [undefined,P.operationId,'33333333-3333-4333-8333-333333333333']){const f=fixture();let effects=0;const adapters=Object.fromEntries(RELEASE_STAGES.map(stage=>[stage,{check:()=>{effects++;return{status:'BLOCKED_EXTERNAL'};},observe(){},execute(){},reconcile(){}}]));await runReleaseSequence({input,journal:f.journal,adapters,requestedOperationId:operationId});assert.equal(f.events.length,117);assert.equal(effects,0);}});
test('new candidate, activation, HOLD lifecycle and writer binding compose without reusing retired2636 records',async()=>{const f=fixture(),pass=()=>({status:'PASS',evidence:{modeled:true}});const adapters=Object.fromEntries(RELEASE_STAGES.map(stage=>[stage,{check:stage==='generation_revalidation'?()=>({status:'BLOCKED_EXTERNAL'}):pass,observe:pass,reconcile:pass,execute(call){
 if(stage==='candidate_six_reads'){f.events.push({schema:1,type:'candidate_six_reads_intent',attemptId:call.attemptId,releaseSha:successor},{schema:1,type:'candidate_six_reads_result',attemptId:call.attemptId,releaseSha:successor,status:'PASS',reportDigest:'e'.repeat(64)});}
 if(stage!=='admission_lease')return;
 const binding={releaseSha:successor,operationId:newOp,attemptId:call.attemptId,inputDigest:call.inputDigest,checkOutputDigest:call.checkOutputDigest,backendProfile:'owned-postgres-v1',profileDigest:P.profileDigest},bindingDigest=hash(binding);
 f.events.push({schema:1,type:'buyer_writer_activation_intent',binding,bindingDigest});for(const row of original.filter(r=>r.type==='buyer_writer_activation_result').slice(-6))f.events.push({...row,bindingDigest});
 const remap=v=>{if(Array.isArray(v))return v.map(remap);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,remap(x)]));return v===P.releaseSha?successor:v===P.operationId?newOp:v===P.runId?runId:v;};
 for(const row of original.filter(r=>['release_hold_intent','release_hold_result','release_lifecycle_intent','release_lifecycle_result'].includes(r.type)||r.type.startsWith('candidate_deployment_')))f.events.push(remap(row));
 const plan={...remap(original.find(r=>r.type==='held_writer_binding_intent').plan),attemptId:call.attemptId,inputDigest:call.inputDigest,checkOutputDigest:call.checkOutputDigest};
 f.events.push({schema:1,type:'held_writer_binding_intent',plan});for(const step of ['retire_commit','retire_binding','publish'])f.events.push({schema:1,type:'held_writer_binding_step_intent',plan,step},{schema:1,type:'held_writer_binding_step_result',plan,step});f.events.push({schema:1,type:'held_writer_binding_result',plan,bindingDigest:'e'.repeat(64),commitDigest:'f'.repeat(64)});
 }}]));
 const result=await runReleaseSequence({input,journal:f.journal,adapters,requestedOperationId:newOp});assert.equal(result.stage,'generation_revalidation');assert.equal(inspectReleaseCommander(f.journal).status,'OBSERVED');assert.equal(inspectCandidateDeploymentHistory(f.events).plan.releaseSha,successor);assert.equal(inspectHeldWriterBindingHistory(f.events).get('admission_lease').plan.operationId,newOp);assert.equal(inspectBuyerWriterActivationHistory(f.events).intent.binding.operationId,newOp);assert.equal(inspectCompletedHeldLifecycle(f.events,successor).result.runId,runId);assert.deepEqual(f.events.slice(0,116),original);
});
test('n8n view excludes only exact nine retained GET observations, never old mutations or changed baseline',()=>{const f=fixture(),release={schema:3,releaseSha:successor,operationId:newOp,backendProfile:'owned-postgres-v1',profileDigest:P.profileDigest,sourceSecurityConfigurationFile:`/var/lib/blackspire-operator/owned-source-security/${P.operationId}/configuration.json`,ownedMigrationConfigurationFile:`/var/lib/blackspire-operator/owned-buyer-migration/${P.operationId}/manifest.json`,successorLineageFile:`/var/lib/blackspire-operator/owned-migration-successors/${newOp}/plan.json`},baseline=workflow[0].state,plan={releaseSha:successor,namespace:workflow[0].namespace,baselineDigest:baseline.definitionDigest,baselineVersion:baseline.versionId};const view=createOwnedN8nRetiredJournalView({journal:f.journal,release,plan});assert.deepEqual(view.stream('n8n').events(),[]);assert.equal(f.n8n.length,9);f.n8n[8].type='intent';assert.throws(()=>view.stream('n8n').events());});
