import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareOwnedBuyerFrontend,publishOwnedBuyerApi,addOwnedBuyerMode} from '../packages/zola-release/owned-buyer-configuration.js';
const sha='a'.repeat(40),key=Buffer.alloc(32,1).toString('base64url'),consumer=Buffer.alloc(32,2).toString('base64url');
function fixture(){const records=new Map(),rows=[];let environment='SESSION_SECRET=preserved\nBLACKSPIRE_AUTHORITY_CONSUMER_TOKEN='+consumer+'\n',deal=null,calls=0,generated=0,failWrite=false,failDeal=false;
 const host={assertStopped:async()=>{},read:n=>records.get(n)??null,publish(n,v){if(records.has(n))assert.deepEqual(records.get(n),v);else records.set(n,structuredClone(v));},consumer:()=>consumer,token:()=> 'vercel-credential-distinct',apiEnvironment:()=>environment,receiver:()=>({schema:1,releaseSha:sha,frontendOrigin:'https://reviewed-preview.vercel.app',deploymentId:'dpl_reviewed'}),deal:()=>deal,replaceApi(before,after){assert.ok(environment===before||environment===after);environment=after;},publishDeal(v){if(failDeal){failDeal=false;throw Error('interrupted');}deal=structuredClone(v);},verifyIsolation:async()=>{}};
 const transport={observe:async()=>structuredClone(rows),async write(d,v,id){calls++;assert.equal(v,d.key.endsWith('KEY')?key:d.key.endsWith('MODE')?'owned-postgres-v1':'https://command.blackspirehelix.com');let r=id?rows.find(r=>r.id===id):null;if(!r){r={...d,id:'row'+rows.length,updatedAt:0};rows.push(r);}r.updatedAt++;if(failWrite){failWrite=false;throw Error('ambiguous');}}};
 return{host,transport,records,rows,generate:()=>{generated++;return key;},calls:()=>calls,generated:()=>generated,failWrite:()=>{failWrite=true;},failDeal:()=>{failDeal=true;},setEnvironment:v=>{environment=v;}};
}
test('six exact scoped frontend settings preserve key and require separate API deployment proof',async()=>{const f=fixture();const r=await prepareOwnedBuyerFrontend({releaseSha:sha},f);assert.equal(r.settings,6);assert.equal(r.deploymentAcceptance,false);assert.equal(f.host.deal(),null);assert.equal(f.generated(),1);await prepareOwnedBuyerFrontend({releaseSha:sha},f);assert.equal(f.calls(),6);assert.equal(f.generated(),1);
 await assert.rejects(publishOwnedBuyerApi({releaseSha:sha},{...f,verifyReceiver:async()=>{throw Error('wrong deployment');}}));assert.equal(f.host.deal(),null);assert.ok(!f.host.apiEnvironment().includes('BUYER_STORE_MODE='));
 await publishOwnedBuyerApi({releaseSha:sha},{...f,verifyReceiver:async target=>{assert.equal(target.origin,'https://reviewed-preview.vercel.app');assert.equal(target.releaseSha,sha);}});assert.equal(f.host.deal().key,key);assert.ok(f.host.apiEnvironment().endsWith('BUYER_STORE_MODE=owned-postgres-v1\n'));
});
test('ambiguous remote create reasserts retained key by exact identified row without duplicate',async()=>{const f=fixture();f.failWrite();await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},f));await prepareOwnedBuyerFrontend({releaseSha:sha},f);assert.equal(f.rows.length,6);assert.equal(f.calls(),7);assert.equal(f.generated(),1);});
test('unknown remote rows, purpose collision and completed-row drift refuse',async()=>{let f=fixture();f.rows.push({key:'BLACKSPIRE_BUYER_STORE_MODE'});await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},f));assert.equal(f.calls(),0);f=fixture();await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},{...f,generate:()=>consumer}));assert.equal(f.calls(),0);f=fixture();await prepareOwnedBuyerFrontend({releaseSha:sha},f);f.rows[0].updatedAt++;await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},f));assert.equal(f.calls(),6);});
test('API partial publication resumes exact retained bytes; foreign environment is never overwritten',async()=>{const f=fixture();await prepareOwnedBuyerFrontend({releaseSha:sha},f);f.failDeal();await assert.rejects(publishOwnedBuyerApi({releaseSha:sha},{...f,verifyReceiver:async()=>{}}));await publishOwnedBuyerApi({releaseSha:sha},{...f,verifyReceiver:async()=>{}});assert.equal(f.generated(),1);f.setEnvironment('FOREIGN=1\n');await assert.rejects(publishOwnedBuyerApi({releaseSha:sha},{...f,verifyReceiver:async()=>{}}));assert.equal(f.host.apiEnvironment(),'FOREIGN=1\n');});
test('mode update rejects duplicate, malformed or preexisting authority while preserving exact bytes',()=>{assert.throws(()=>addOwnedBuyerMode('BUYER_STORE_MODE=legacy\n'));assert.throws(()=>addOwnedBuyerMode('export BUYER_STORE_MODE=x\n'));assert.throws(()=>addOwnedBuyerMode('A=1\nA=2\n'));assert.equal(addOwnedBuyerMode('# retained\nBLACKSPIRE_AUTHORITY_CONSUMER_TOKEN=x\n'),'# retained\nBLACKSPIRE_AUTHORITY_CONSUMER_TOKEN=x\nBUYER_STORE_MODE=owned-postgres-v1\n');});

test('stale API consumer and ambiguous absent-row intent refuse without remote redispatch',async()=>{let f=fixture();f.setEnvironment('BLACKSPIRE_AUTHORITY_CONSUMER_TOKEN=stale\n');await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},f));assert.equal(f.calls(),0);f=fixture();f.failWrite();await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},f));f.rows.length=0;await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},f));assert.equal(f.calls(),1);f=fixture();await prepareOwnedBuyerFrontend({releaseSha:sha},f);f.setEnvironment('BLACKSPIRE_AUTHORITY_CONSUMER_TOKEN=stale\n');await assert.rejects(prepareOwnedBuyerFrontend({releaseSha:sha},f));assert.equal(f.calls(),6);});

test('Vercel transport scopes exact create and retained-ID patch; observation excludes values',async()=>{
 const {createOwnedBuyerVercelTransport,OWNED_BUYER_CONFIGURATION:C}=await import('../packages/zola-release/owned-buyer-configuration.js');const requests=[];
 const transport=createOwnedBuyerVercelTransport({token:()=> 'synthetic-transport-credential',fetchImpl:async(url,options)=>{requests.push({url,options});let result;if(options.method==='POST')result={created:{key:'BLACKSPIRE_BUYER_DEAL_CONTEXT_KEY',type:'sensitive'},failed:[]};else if(options.method==='PATCH')result={id:'owned_row',key:'BLACKSPIRE_BUYER_DEAL_CONTEXT_KEY',type:'sensitive'};else if(url.includes('/env?'))result={envs:[{id:'owned_row',key:'BLACKSPIRE_BUYER_DEAL_CONTEXT_KEY',type:'sensitive',target:['production'],updatedAt:1,value:'must-not-observe'}]};else result={id:C.project,accountId:C.team};return new Response(JSON.stringify(result));}});
 const descriptor={key:'BLACKSPIRE_BUYER_DEAL_CONTEXT_KEY',type:'sensitive',target:['preview'],gitBranch:C.branch,comment:'owned-fixture'};
 await transport.write(descriptor,key,null);await transport.write(descriptor,key,'owned_row');const rows=await transport.observe();assert.equal('value' in rows[0],false);assert.equal(requests[0].options.method,'POST');assert.equal(requests[0].url.includes('upsert'),false);assert.deepEqual(JSON.parse(requests[0].options.body),{...descriptor,value:key});assert.deepEqual(JSON.parse(requests[1].options.body),{value:key});for(const r of requests){assert.equal(r.options.redirect,'error');assert.ok(r.url.includes('teamId='+C.team));assert.ok(r.url.includes(C.project));}
});
