import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {register} from 'node:module';
import {OWNED_SEQUENCE as B,transformOwnedSequenceSource,assertOwnedSequenceState} from '../packages/zola-release/owned-sequence-overlay.js';
register(new URL('../packages/zola-release/owned-sequence-loader.js',import.meta.url));
const {hash}=await import('../packages/zola-release/commander-journal.js');
const {runReleaseSequence,inspectReleaseSequenceHistory,RELEASE_STAGES}=await import('../packages/zola-release/commander-sequence.js');
const {partitionRetiredReleaseHistory}=await import('../packages/zola-release/retired-release-history.js');
const {inspectReleaseCommander}=await import('../packages/zola-release/commander.js');
const prefix=JSON.parse(fs.readFileSync(new URL('./fixtures/zola-release/retired-release-2636.json',import.meta.url))),retired=JSON.parse(fs.readFileSync(new URL('./fixtures/zola-release/owned-successor-retirement-a8e.json',import.meta.url)));
function fixture(){const events=[...structuredClone(prefix),structuredClone(retired)],n8n=JSON.parse(fs.readFileSync(new URL('./fixtures/zola-release/retired-release-n8n-2636.json',import.meta.url)));return {events,journal:{stream:name=>({events:()=>structuredClone(name==='release'?events:n8n),append:r=>events.push(structuredClone(r))})}};}
function input(main=B.previousMainSha){const v={releaseSha:B.releaseSha,previousMainSha:main,recoverySha:'2c0b600c268faa0571f08322e16d7f81f37789be',protectedInputDigest:'a'.repeat(64),workspace:'zola-production',principal:'blackspire-release-root'};return {...v,inputDigest:hash(v)};}
const adapters=()=>Object.fromEntries(RELEASE_STAGES.map(s=>[s,{check:()=>({status:'BLOCKED_EXTERNAL'}),observe(){},execute(){throw Error('unexpected effect');},reconcile(){throw Error('unexpected replay');}}]));
test('exact native loader graph starts and rereads a8e/f3ac without changing retired bytes or registry',async()=>{const f=fixture(),before=JSON.stringify(f.events);const result=await runReleaseSequence({input:input(),journal:f.journal,adapters:adapters(),requestedOperationId:B.operationId});assert.equal(result.stage,'exact_sha_verification');assert.equal(f.events.length,119);assert.equal(JSON.stringify(f.events.slice(0,117)),before);assert.equal(partitionRetiredReleaseHistory(f.events).current.length,2);assert.equal(inspectReleaseSequenceHistory(f.events).context.previousMainSha,B.previousMainSha);assert.equal(inspectReleaseCommander(f.journal).status,'OBSERVED');const resumed=await runReleaseSequence({input:input(),journal:f.journal,adapters:adapters(),requestedOperationId:B.operationId});assert.equal(resumed.stage,'exact_sha_verification');assert.equal(f.events.filter(r=>r.type==='sequence_started'&&r.operationId===B.operationId).length,1);});
test('wrong new main, successor operation and retirement proof deny before fresh append',async()=>{for(const main of ['2775fd5043ad422418a4177f686671961e9a9738','b'.repeat(40)]){const f=fixture();await runReleaseSequence({input:input(main),journal:f.journal,adapters:adapters(),requestedOperationId:B.operationId});assert.equal(f.events.length,117);}for(const patch of [{successorOperationId:'11111111-1111-4111-8111-111111111111'},{proofDigest:'c'.repeat(64)}]){const f=fixture();Object.assign(f.events[116],patch);await runReleaseSequence({input:input(),journal:f.journal,adapters:adapters(),requestedOperationId:B.operationId});assert.equal(f.events.length,117);}});
test('source transformer refuses drift and nonallowlisted modules',()=>{for(const name of ['commander-sequence.js','retired-release-history.js']){const source=fs.readFileSync(new URL('../packages/zola-release/'+name,import.meta.url),'utf8');assert.notEqual(transformOwnedSequenceSource(name,source),source);assert.throws(()=>transformOwnedSequenceSource(name,source+'\n'));}assert.throws(()=>transformOwnedSequenceSource('commander-journal.js','anything'));});
test('outer operator fence requires exact schema-five retirement and original new input',()=>{const f=fixture(),state=inspectReleaseSequenceHistory(f.events),release={schema:3,...B};assert.equal(assertOwnedSequenceState(release,state),true);for(const patch of [{schema:2},{operationId:'11111111-1111-4111-8111-111111111111'},{previousMainSha:'2775fd5043ad422418a4177f686671961e9a9738'}])assert.throws(()=>assertOwnedSequenceState({...release,...patch},state));});

test('main fence uses native merge proof for retained result or pending lost acknowledgment',async()=>{
 const {verifyOwnedSequenceOperator}=await import('../packages/zola-release/owned-sequence-operator-fence.js');
 const f=fixture(),base=inspectReleaseSequenceHistory(f.events),release={schema:3,...B},ci={releaseSha:B.releaseSha,mainSha:B.previousMainSha,ciMergeSha:'d'.repeat(40),ciTreeSha:'e'.repeat(40)};
 let initial=0;verifyOwnedSequenceOperator(release,f.journal,{inspect:()=>base,observeMain:()=>{initial++;}});assert.equal(initial,1);
 for(const retained of [false,true]){const newMainSha='f'.repeat(40),state={...base,outputs:{ci_security:ci,...(retained?{expected_head_merge:{newMainSha}}:{})},pending:retained?null:{stage:'expected_head_merge'}};let verified=0;
  const dependencies={inspect:()=>state,observeMain:()=>{throw Error('old main fence called');},observeMerge:b=>{assert.equal(b.previousMainSha,B.previousMainSha);return {status:'MERGED_EXACT_HEAD',newMainSha};},verifyMerged:b=>{assert.equal(b.newMainSha,newMainSha);verified++;return {status:'MERGED_IDENTITY_VERIFIED'};}};
  verifyOwnedSequenceOperator(release,f.journal,dependencies);assert.equal(verified,1);
  assert.throws(()=>verifyOwnedSequenceOperator(release,f.journal,{...dependencies,verifyMerged:()=>({status:'REJECTED'})}));
  assert.throws(()=>verifyOwnedSequenceOperator(release,f.journal,{...dependencies,inspect:()=>({...state,outputs:{...state.outputs,ci_security:{...ci,mainSha:'a'.repeat(40)}}})}));
 }
});
