import test from 'node:test';import assert from 'node:assert/strict';
import {N8N_REASSERTION as B,n8nReassertionDigest,reassertOwnedN8nWriter,validateOwnedN8nReassertionProof} from '../packages/zola-release/owned-n8n-credential-reassertion.js';
import {observeOwnedN8nConsumerClosure,observeOwnedN8nContinuationClosure} from '../packages/zola-release/owned-n8n-consumer-closure.js';
const before={id:B.credentialId,name:'ZOLA Buyer writer',type:'httpHeaderAuth',isManaged:false,isGlobal:false,isResolvable:false,resolvableAllowFallback:false,resolverId:null,createdAt:'2026-09-01T00:00:00.000Z',updatedAt:'2026-09-07T00:00:00.000Z'},after={...before,updatedAt:'2026-09-21T00:00:00.000Z'};
function fixture(){const authority={operatorSha:B.originalOperatorSha,releaseSha:B.releaseSha,operationId:B.operationId,stageAttemptId:'11111111-1111-4111-8111-111111111111',sourceDigest:'a'.repeat(64),profileDigest:'b'.repeat(64),namespace:'fixed'},originalIntent={binding:{releaseSha:B.releaseSha,profileDigest:authority.profileDigest,sourceDigest:authority.sourceDigest,namespace:authority.namespace,credentialId:B.credentialId},before},input={authority,originalIntent,originalResult:null,source:{authority:{releaseSha:B.releaseSha,operationId:B.operationId},writerCredential:'z'.repeat(43)},operatorSha:'c'.repeat(40)},rows={},calls=[];let current=before;
 const store={value:n=>rows[n]??null,record:(n,v)=>{if(rows[n])assert.deepEqual(rows[n],v);rows[n]=structuredClone(v);}};
 const deps={store,fence:async()=>{},closure:async()=>({version:1,ownerCount:1,projectCount:1,workflowCount:8,credentialReferences:0,buyerInactive:true,executionsDrained:true,digest:'d'.repeat(64),ownerDigest:'e'.repeat(64),projectDigest:'f'.repeat(64),workflows:Array.from({length:8},(_,i)=>({id:'workflow'+i,versionId:'v'+i,active:false,definitionDigest:'a'.repeat(64)}))}),request:async(method,route,body)=>{calls.push(method);assert.equal(route,'/api/v1/credentials/'+B.credentialId);if(method==='PATCH'){assert.deepEqual(body,{data:{name:'x-buyer-writer-key',value:'z'.repeat(43),allowedHttpRequestDomains:'domains',allowedDomains:'jarvis.blackspirehelix.com'},isPartialData:false});current=after;}return {status:200,body:current};}};return {input,rows,calls,deps,setCurrent:v=>{current=v;}};}
test('one new acknowledged administrative replacement preserves original UNKNOWN and never redispatches',async()=>{const f=fixture(),old=JSON.stringify(f.input);const result=await reassertOwnedN8nWriter(f.input,f.deps);assert.equal(result.originalOutcome,'UNKNOWN');assert.equal(result.providerExtraEffects,'UNVERIFIED');assert.equal(JSON.stringify(f.input),old);assert.deepEqual(Object.keys(f.rows),['intent','http-ack','result']);assert.equal(JSON.stringify(f.rows).includes(f.input.source.writerCredential),false);assert.equal(validateOwnedN8nReassertionProof({...f.input,intent:f.rows.intent,httpAck:f.rows['http-ack'],result}).after.updatedAt,after.updatedAt);await reassertOwnedN8nWriter(f.input,f.deps);assert.equal(f.calls.filter(x=>x==='PATCH').length,1);});
test('transport unknown,403 and malformed200 each permanently forbid another dispatch',async()=>{for(const mode of ['unknown','403','malformed']){const f=fixture(),base=f.deps.request;f.deps.request=async(...args)=>{if(args[0]!=='PATCH')return base(...args);f.calls.push('PATCH');if(mode==='unknown')throw Error('lost');return {status:mode==='403'?403:200,body:{message:'denied'}};};await assert.rejects(reassertOwnedN8nWriter(f.input,f.deps));assert.equal(Boolean(f.rows['http-ack']),mode!=='unknown');await assert.rejects(reassertOwnedN8nWriter(f.input,f.deps));assert.equal(f.calls.filter(x=>x==='PATCH').length,1);assert.equal(f.rows.result,undefined);}});
test('durable200 acknowledgment survives postcheck failure and adopts without PATCH',async()=>{const f=fixture();f.deps.fence=async()=>{if(f.rows['http-ack'])throw Error('interrupted');};await assert.rejects(reassertOwnedN8nWriter(f.input,f.deps));assert.equal(f.rows['http-ack'].status,200);assert.equal(f.rows.result,undefined);f.deps.fence=async()=>{};const result=await reassertOwnedN8nWriter(f.input,f.deps);assert.equal(result.reasserted,true);assert.equal(f.calls.filter(x=>x==='PATCH').length,1);});
test('foreign binding/body, old result or changing consumer closure refuses',async()=>{for(const mutate of [f=>{f.input.originalResult={};},f=>{f.input.authority.operatorSha='e'.repeat(40);},f=>{f.input.originalIntent.binding.sourceDigest='e'.repeat(64);}]){const f=fixture();mutate(f);await assert.rejects(reassertOwnedN8nWriter(f.input,f.deps));assert.equal(f.calls.length,0);}const f=fixture();await reassertOwnedN8nWriter(f.input,f.deps);f.input.source.writerCredential='q'.repeat(43);await assert.rejects(reassertOwnedN8nWriter(f.input,f.deps));assert.equal(f.calls.filter(x=>x==='PATCH').length,1);const g=fixture(),closure=g.deps.closure;g.deps.closure=async()=>({...await closure(),digest:g.rows['http-ack']?'e'.repeat(64):'d'.repeat(64)});await assert.rejects(reassertOwnedN8nWriter(g.input,g.deps));assert.equal(g.rows.result,undefined);assert.equal(g.rows['http-ack'].status,200);});
function closureFixture(){const buyer='VvMHSIbycYCx4CZN',rows={users:[{id:'owner',role:'global:owner',isPending:false}],projects:[{id:'project',type:'personal',creatorId:'owner'}],workflows:Array.from({length:8},(_,i)=>({id:i?'other'+i:buyer,versionId:'version'+i,active:false,activeVersionId:null,nodes:[],connections:{},settings:{}})),executions:[]};let calls=0;return {rows,request:async(method,path)=>{assert.equal(method,'GET');calls++;const key=path.split('/')[3].split('?')[0];return {status:200,body:{data:structuredClone(rows[key]),nextCursor:null}};},count:()=>calls};}
test('two full owner/project/eight-workflow scans prove credential closure without exposing IDs',async()=>{const f=closureFixture(),r=await observeOwnedN8nConsumerClosure({request:f.request,tokenSubject:'owner'});assert.equal(r.credentialReferences,0);assert.equal(f.count(),8);assert.equal(JSON.stringify(r).includes('"owner"'),false);});
test('owner scope, hidden next page, another consumer and running execution reject',async()=>{for(const mutate of [f=>f.rows.users.push({id:'other',role:'global:owner',isPending:false}),f=>{f.rows.projects[0].creatorId='other';},f=>{f.rows.workflows[1].nodes=[{credentials:{httpHeaderAuth:{id:B.credentialId}}}];},f=>{f.rows.workflows[1].nodes=[{credentials:{httpHeaderAuth:{id:'={{expression}}'}}}];},f=>{f.rows.executions=[{id:'run',workflowId:'VvMHSIbycYCx4CZN',finished:false,status:'running'}];}]){const f=closureFixture();mutate(f);await assert.rejects(observeOwnedN8nConsumerClosure({request:f.request,tokenSubject:'owner'}));}const f=closureFixture();await assert.rejects(observeOwnedN8nConsumerClosure({tokenSubject:'owner',request:async(method,path)=>{const r=await f.request(method,path);if(path.includes('/users'))r.body.nextCursor='repeat';return r;}}));});

test('staged final result is promoted on read-only acknowledgment adoption',async()=>{const f=fixture();await reassertOwnedN8nWriter(f.input,f.deps);const promoted=[],record=f.deps.store.record;f.deps.store.record=(n,v)=>{promoted.push(n);record(n,v);};await reassertOwnedN8nWriter(f.input,f.deps);assert.deepEqual(promoted,['intent','http-ack','result']);assert.equal(f.calls.filter(x=>x==='PATCH').length,1);});
test('continuation permits only journal-bound Buyer change and preserves all other consumer definitions',async()=>{const f=closureFixture(),initialClosure=await observeOwnedN8nConsumerClosure({request:f.request,tokenSubject:'owner'}),baseline=initialClosure.workflows.find(w=>w.id==='VvMHSIbycYCx4CZN').definitionDigest,plan={baselineDigest:baseline,candidateDigest:'a'.repeat(64)};const args={request:f.request,tokenSubject:'owner',plan,events:[],initialClosure};assert.equal((await observeOwnedN8nContinuationClosure(args)).status,'OWNED_N8N_CONTINUATION_CLOSURE_VERIFIED');f.rows.workflows[1].versionId='changed';await assert.rejects(observeOwnedN8nContinuationClosure(args));f.rows.workflows[1].versionId='version1';f.rows.workflows[0].nodes=[{credentials:{httpHeaderAuth:{id:B.credentialId}}}];await assert.rejects(observeOwnedN8nContinuationClosure(args));});

test('candidate continuation requires native update then publish grammar before active state',async()=>{const f=closureFixture(),initialClosure=await observeOwnedN8nConsumerClosure({request:f.request,tokenSubject:'owner'}),buyer=f.rows.workflows[0],baseline=initialClosure.workflows.find(w=>w.id===buyer.id).definitionDigest;buyer.nodes=[{credentials:{httpHeaderAuth:{id:B.credentialId}}}];buyer.versionId='candidate-version';const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;const plan={baselineDigest:baseline,candidateDigest:n8nReassertionDigest(canonical({name:buyer.name,nodes:buyer.nodes,connections:buyer.connections,settings:buyer.settings}))},events=[{type:'intent',operation:'update'}],args={request:f.request,tokenSubject:'owner',plan,events,initialClosure};assert.equal((await observeOwnedN8nContinuationClosure(args)).status,'OWNED_N8N_CONTINUATION_CLOSURE_VERIFIED');buyer.active=true;await assert.rejects(observeOwnedN8nContinuationClosure(args));events.push({type:'confirmed',operation:'update',state:{versionId:buyer.versionId}},{type:'intent',operation:'publish'});assert.equal((await observeOwnedN8nContinuationClosure(args)).status,'OWNED_N8N_CONTINUATION_CLOSURE_VERIFIED');});
