/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppWarRoomRouteImport } from './routes/_app.war-room'
import { Route as AppTrackerRouteImport } from './routes/_app.tracker'
import { Route as AppSimulationsRouteImport } from './routes/_app.simulations'
import { Route as AppSharpRouteImport } from './routes/_app.sharp'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPropsRouteImport } from './routes/_app.props'
import { Route as AppPlayersRouteImport } from './routes/_app.players'
import { Route as AppMarketsRouteImport } from './routes/_app.markets'
import { Route as AppGamesRouteImport } from './routes/_app.games'
import { Route as AppEdgeRouteImport } from './routes/_app.edge'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppGamesIdRouteImport } from './routes/_app.games.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarRoomRoute = AppWarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackerRoute = AppTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsRoute = AppSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => AppRoute,
} as any)
const AppSharpRoute = AppSharpRouteImport.update({
  id: '/sharp',
  path: '/sharp',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPropsRoute = AppPropsRouteImport.update({
  id: '/props',
  path: '/props',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayersRoute = AppPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppEdgeRoute = AppEdgeRouteImport.update({
  id: '/edge',
  path: '/edge',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIdRoute = AppGamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/edge': typeof AppEdgeRoute
  '/games': typeof AppGamesRouteWithChildren
  '/markets': typeof AppMarketsRoute
  '/players': typeof AppPlayersRoute
  '/props': typeof AppPropsRoute
  '/settings': typeof AppSettingsRoute
  '/sharp': typeof AppSharpRoute
  '/simulations': typeof AppSimulationsRoute
  '/tracker': typeof AppTrackerRoute
  '/war-room': typeof AppWarRoomRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/games/$id': typeof AppGamesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/edge': typeof AppEdgeRoute
  '/games': typeof AppGamesRouteWithChildren
  '/markets': typeof AppMarketsRoute
  '/players': typeof AppPlayersRoute
  '/props': typeof AppPropsRoute
  '/settings': typeof AppSettingsRoute
  '/sharp': typeof AppSharpRoute
  '/simulations': typeof AppSimulationsRoute
  '/tracker': typeof AppTrackerRoute
  '/war-room': typeof AppWarRoomRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/games/$id': typeof AppGamesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/edge': typeof AppEdgeRoute
  '/_app/games': typeof AppGamesRouteWithChildren
  '/_app/markets': typeof AppMarketsRoute
  '/_app/players': typeof AppPlayersRoute
  '/_app/props': typeof AppPropsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sharp': typeof AppSharpRoute
  '/_app/simulations': typeof AppSimulationsRoute
  '/_app/tracker': typeof AppTrackerRoute
  '/_app/war-room': typeof AppWarRoomRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/games/$id': typeof AppGamesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/alerts'
    | '/dashboard'
    | '/edge'
    | '/games'
    | '/markets'
    | '/players'
    | '/props'
    | '/settings'
    | '/sharp'
    | '/simulations'
    | '/tracker'
    | '/war-room'
    | '/auth/callback'
    | '/games/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/admin'
    | '/ai'
    | '/alerts'
    | '/dashboard'
    | '/edge'
    | '/games'
    | '/markets'
    | '/players'
    | '/props'
    | '/settings'
    | '/sharp'
    | '/simulations'
    | '/tracker'
    | '/war-room'
    | '/auth/callback'
    | '/games/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/edge'
    | '/_app/games'
    | '/_app/markets'
    | '/_app/players'
    | '/_app/props'
    | '/_app/settings'
    | '/_app/sharp'
    | '/_app/simulations'
    | '/_app/tracker'
    | '/_app/war-room'
    | '/auth/callback'
    | '/_app/games/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/war-room': {
      id: '/_app/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof AppWarRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracker': {
      id: '/_app/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AppTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simulations': {
      id: '/_app/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof AppSimulationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sharp': {
      id: '/_app/sharp'
      path: '/sharp'
      fullPath: '/sharp'
      preLoaderRoute: typeof AppSharpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/props': {
      id: '/_app/props'
      path: '/props'
      fullPath: '/props'
      preLoaderRoute: typeof AppPropsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/players': {
      id: '/_app/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AppPlayersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games': {
      id: '/_app/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/edge': {
      id: '/_app/edge'
      path: '/edge'
      fullPath: '/edge'
      preLoaderRoute: typeof AppEdgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$id': {
      id: '/_app/games/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AppGamesIdRouteImport
      parentRoute: typeof AppGamesRoute
    }
  }
}

interface AppGamesRouteChildren {
  AppGamesIdRoute: typeof AppGamesIdRoute
}

const AppGamesRouteChildren: AppGamesRouteChildren = {
  AppGamesIdRoute: AppGamesIdRoute,
}

const AppGamesRouteWithChildren = AppGamesRoute._addFileChildren(
  AppGamesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEdgeRoute: typeof AppEdgeRoute
  AppGamesRoute: typeof AppGamesRouteWithChildren
  AppMarketsRoute: typeof AppMarketsRoute
  AppPlayersRoute: typeof AppPlayersRoute
  AppPropsRoute: typeof AppPropsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSharpRoute: typeof AppSharpRoute
  AppSimulationsRoute: typeof AppSimulationsRoute
  AppTrackerRoute: typeof AppTrackerRoute
  AppWarRoomRoute: typeof AppWarRoomRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEdgeRoute: AppEdgeRoute,
  AppGamesRoute: AppGamesRouteWithChildren,
  AppMarketsRoute: AppMarketsRoute,
  AppPlayersRoute: AppPlayersRoute,
  AppPropsRoute: AppPropsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSharpRoute: AppSharpRoute,
  AppSimulationsRoute: AppSimulationsRoute,
  AppTrackerRoute: AppTrackerRoute,
  AppWarRoomRoute: AppWarRoomRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
