import fs from 'node:fs';
import path from 'node:path';
import { DATA_DIR } from '../shared/config.js';
import { getTask, taskRecords, audit } from '../task-engine/tasks.js';
import { execSql, esc } from '../task-engine/db.js';
import { id, now } from '../shared/util.js';
import { redact } from '../shared/util.js';
const MAX = 1024 * 1024;
export function evidenceObject(taskId) { const task = getTask(taskId); if (!task) return null; const records = taskRecords(taskId); return { task: { id: task.id, request: task.request, status: task.status, workspace: task.workspace_id, plan: safeJson(task.plan), summary: safeJson(task.summary), evidence: safeJson(task.evidence) }, ...records }; }
export function exportEvidence(taskId, format = 'json') { const obj = evidenceObject(taskId); if (!obj) return null; const body = format === 'md' ? toMarkdown(obj) : JSON.stringify(obj, null, 2); const redacted = redact(body); if (Buffer.byteLength(redacted) > MAX) throw new Error('evidence export too large'); const dir = path.join(DATA_DIR, 'evidence'); fs.mkdirSync(dir, { recursive: true }); const file = path.join(dir, `${taskId}.${format === 'md' ? 'md' : 'json'}`); fs.writeFileSync(file, redacted); execSql(`INSERT INTO evidence_exports VALUES (${esc(id('export'))},${esc(taskId)},${esc(format)},${esc(file)},${Buffer.byteLength(redacted)},${esc(now())});`); audit(taskId, 'evidence', 'export.created', { format, size: Buffer.byteLength(redacted) }); return { path: file, size: Buffer.byteLength(redacted), content: redacted, contentType: format === 'md' ? 'text/markdown' : 'application/json', filename: path.basename(file) }; }
function safeJson(value) { try { return typeof value === 'string' ? JSON.parse(value) : value; } catch { return value; } }
function toMarkdown(o) { return `# Evidence ${o.task.id}\n\n## Task\n- Request: ${o.task.request}\n- Workspace: ${o.task.workspace}\n- Status: ${o.task.status}\n\n## Plan\n\`\`\`json\n${JSON.stringify(o.task.plan, null, 2)}\n\`\`\`\n\n## Subtasks\n${o.subtasks.map((s) => `- ${s.stage}: ${s.status}`).join('\n')}\n\n## Provider Attempts\n${o.providerAttempts.map((a) => `- ${a.provider}/${a.mode}: ${a.status}`).join('\n')}\n\n## Usage\n\`\`\`json\n${JSON.stringify(o.usage, null, 2)}\n\`\`\`\n\n## Approvals\n\`\`\`json\n${JSON.stringify(o.approvals, null, 2)}\n\`\`\`\n\n## Changed Files\n${o.changedFiles.map((f) => `- ${f.path} (${f.status})`).join('\n')}\n\n## Command Results\n${o.commands.map((c) => `- ${c.command}: ${c.ok ? 'ok' : 'failed'}`).join('\n')}\n\n## Logs\n${o.logs.map((l) => `- ${l.created_at} ${l.actor}.${l.action}`).join('\n')}\n\n## Final Evidence\n\`\`\`json\n${JSON.stringify(o.evidence, null, 2)}\n\`\`\`\n`; }
