WITH RECURSIVE closure(oid) AS (
 SELECT oid FROM pg_class WHERE relnamespace='public'::regnamespace AND relname IN ('BuyerProfile','BuyerReport','CleanSale','RawSale','SearchJob','exports')
 UNION SELECT CASE WHEN c.conrelid=x.oid THEN c.confrelid ELSE c.conrelid END FROM closure x JOIN pg_constraint c ON c.contype='f' AND (c.conrelid=x.oid OR c.confrelid=x.oid)
), tables AS (SELECT c.*,n.nspname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.oid IN (SELECT oid FROM closure))
SELECT jsonb_build_object(
 'version',1,'project','kchtrvfcixnimvxxctkj','serverVersion',current_setting('server_version_num'),
 'relations',(SELECT jsonb_agg(jsonb_build_object('schema',t.nspname,'name',t.relname,'kind',t.relkind,'owner',pg_get_userbyid(t.relowner),'rls',t.relrowsecurity,'forceRls',t.relforcerowsecurity,'persistence',t.relpersistence,'replicaIdentity',t.relreplident,'options',t.reloptions,
 'acl',t.relacl::text,'columns',(SELECT jsonb_agg(jsonb_build_object('name',a.attname,'position',a.attnum,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'generated',a.attgenerated,'identity',a.attidentity,'default',pg_get_expr(d.adbin,d.adrelid),'collation',CASE WHEN a.attcollation=0 THEN NULL ELSE a.attcollation::regcollation::text END,'acl',a.attacl::text) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=t.oid AND a.attnum>0 AND NOT a.attisdropped),
 'constraints',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',c.conname,'type',c.contype,'definition',pg_get_constraintdef(c.oid,true),'validated',c.convalidated,'deferrable',c.condeferrable,'initiallyDeferred',c.condeferred) ORDER BY c.conname),'[]'::jsonb) FROM pg_constraint c WHERE c.conrelid=t.oid),
 'indexes',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',i.indexrelid::regclass::text,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready,'primary',i.indisprimary,'unique',i.indisunique) ORDER BY i.indexrelid::regclass::text),'[]'::jsonb) FROM pg_index i WHERE i.indrelid=t.oid),
 'triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',g.tgname,'definition',pg_get_triggerdef(g.oid,true),'enabled',g.tgenabled) ORDER BY g.tgname),'[]'::jsonb) FROM pg_trigger g WHERE g.tgrelid=t.oid AND NOT g.tgisinternal),
 'policies',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',p.polname,'command',p.polcmd,'permissive',p.polpermissive,'roles',(SELECT jsonb_agg(CASE WHEN v=0 THEN 'PUBLIC' ELSE pg_get_userbyid(v) END ORDER BY v) FROM unnest(p.polroles) v),'using',pg_get_expr(p.polqual,p.polrelid),'check',pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polname),'[]'::jsonb) FROM pg_policy p WHERE p.polrelid=t.oid)
 ) ORDER BY t.nspname,t.relname) FROM tables t),
 'authUid',(SELECT jsonb_build_object('identity',p.oid::regprocedure::text,'owner',pg_get_userbyid(p.proowner),'language',l.lanname,'securityDefiner',p.prosecdef,'volatility',p.provolatile,'parallel',p.proparallel,'configuration',p.proconfig,'acl',p.proacl::text,'definition',pg_get_functiondef(p.oid)) FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid='auth.uid()'::regprocedure),
 'schemas',(SELECT jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) ORDER BY nspname) FROM pg_namespace WHERE nspname IN ('public','auth')),
 'defaultAcls',(SELECT coalesce(jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(defaclrole),'schema',CASE WHEN defaclnamespace=0 THEN NULL ELSE defaclnamespace::regnamespace::text END,'kind',defaclobjtype,'acl',defaclacl::text) ORDER BY defaclrole,defaclnamespace,defaclobjtype),'[]'::jsonb) FROM pg_default_acl WHERE defaclnamespace IN (0,'public'::regnamespace,'auth'::regnamespace))
) AS metadata
