const app=document.querySelector('#app');
const DEFAULTS={choices:2,countMax:5,speech:false,asl:true,reducedMotion:false,show:{abc:true,numbers:true,cars:true,match:true,communicate:true,day:true},favorites:['Help','More','Drink','Play'],routine:['Wake up','Brush teeth','Get dressed','Breakfast','Play & Learn','Outside time','Quiet time','Bed time'],stats:{match:0,count:0,abc:0,cars:0,hints:0,signViews:0,comm:0}};
let state=load();let current='home';let lastScreen='home';let selectedSign='Help';let routineIndex=0;let round=null;
const SIGNS=[['Help','🆘','Ask for help'],['More','➕','Ask for more'],['All done','✅','Finished'],['Eat','🍎','Food / eat'],['Drink','🥤','Drink'],['Bathroom','🚽','Bathroom'],['Mom','💗','Mom'],['Dad','💙','Dad'],['Brother','💚','Brother'],['Yes','👍','Yes'],['No','✋','No'],['Please','🙏','Please'],['Thank you','❤️','Thank you'],['Stop','🛑','Stop'],['Go','➡️','Go'],['Play','🎮','Play'],['Sleep','🌙','Sleep'],['Hurt','🩹','Hurt'],['Happy','😊','Happy'],['Sad','😢','Sad']];
const COMM=[['🤲','I want'],['✌️','I need'],['❤️','I feel'],['🍎','Food'],['🥤','Drink'],['🚽','Bathroom'],['🖐','Help'],['➕','More'],['🎮','Play'],['✅','All done'],['👍','Yes'],['✋','No']];
const LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
const CARS=[['🚗','Car'],['🚙','SUV'],['🛻','Truck'],['🚕','Taxi'],['🚓','Police car'],['🚒','Fire truck'],['🚑','Ambulance'],['🏎️','Race car']];
const SHAPES=[['●','Circle'],['■','Square'],['▲','Triangle'],['★','Star']];
function cloneDefaults(){return JSON.parse(JSON.stringify(DEFAULTS))}
function load(){try{const raw=localStorage.getItem('sarions-world-v1');if(!raw)return cloneDefaults();const x=JSON.parse(raw);return {...cloneDefaults(),...x,show:{...DEFAULTS.show,...(x.show||{})},stats:{...DEFAULTS.stats,...(x.stats||{})},favorites:Array.isArray(x.favorites)?x.favorites:DEFAULTS.favorites}}catch{return cloneDefaults()}}
function save(){try{localStorage.setItem('sarions-world-v1',JSON.stringify(state));return true}catch{return false}}
function speak(text){if(!state.speech||!('speechSynthesis'in window))return;const voices=speechSynthesis.getVoices().filter(v=>v.localService);if(!voices.length)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.voice=voices[0];speechSynthesis.speak(u)}
function nav(screen){lastScreen=current;current=screen;round=null;render()}
function header(title){return `<div class="screen-head"><button class="back" data-nav="home">← Home</button><h2>${title}</h2><div class="head-actions"><button class="back" data-nav="help">🖐 Help</button><button class="back" data-nav="break">☁ Break</button></div></div>`}
function family(){return `<section class="family-strip" aria-label="Family"><div class="person dad"><div class="avatar">D</div><div><strong>Dad</strong><span>Carlos · always there</span></div></div><div class="person mom"><div class="avatar">M</div><div><strong>Mom</strong><span>Porshe · caring & strong</span></div></div><div class="person caesar"><div class="avatar">C</div><div><strong>Caesar</strong><span>big brother</span></div></div><div class="person sarion"><div class="avatar">S</div><div><strong>Sarion</strong><span>little explorer</span></div></div></section>`}
function tile(cls,screen,icon,title,copy){return `<button class="tile ${cls}" data-nav="${screen}"><span class="icon">${icon}</span><h3>${title}</h3><p>${copy}</p></button>`}
function home(){return `<div class="topbar"><div class="brand"><div class="logo">S</div><div><h1>Sarion's World</h1><small>Explore · Learn · Play · Communicate · Grow</small></div></div></div>${family()}<section class="hero"><div class="hero-copy"><h2>Hi Sarion! 👋</h2><p>Choose what you want to explore.</p></div><div class="hero-badge">You are amazing ⭐</div></section><section class="tiles">${tile('learn','learn','📘','Learn','Letters, numbers, matching & more')}${tile('play','play','🎮','Play','Cars, matching and creative fun')}${state.show.communicate?tile('communicate','communicate','💬','Communicate','Pictures, words, speech and signs'):''}${state.asl?tile('sign','sign','🤟🏾','Sign & Talk','ASL, words and speech together'):''}${state.show.day?tile('day','day','☀️','My Day','See what comes next'):''}${tile('favorite','favorites','⭐','Favorites','Quick access to favorite words')}</section><div class="utility-row"><button class="utility" data-nav="help">🖐 I need help</button><button class="utility" data-nav="break">☁ Take a break</button><button class="utility" data-nav="grownups">⚙ For grown-ups</button></div>`}
function learn(){return `<main class="screen">${header('Learn')}<section class="tiles">${state.show.abc?tile('communicate','abc','🔤','ABC World','Letters and sounds'):''}${state.show.numbers?tile('day','numbers','🔢','Number Garage','Count with cars'):''}${state.show.cars?tile('play','cars','🚗','Car Match','Match the vehicles'):''}${state.show.match?tile('learn','match','🔷','Shape Match','Find the same shape'):''}<button class="tile play" data-action="coming"><span class="icon">🎨</span><h3>Colors</h3><p>Next module</p></button><button class="tile communicate" data-action="coming"><span class="icon">🙂</span><h3>Feelings</h3><p>Next module</p></button></section><p id="coming" class="feedback"></p></main>`}
function pickOptions(correct,pool){const others=pool.filter(x=>x!==correct).sort(()=>Math.random()-.5).slice(0,state.choices-1);return [correct,...others].sort(()=>Math.random()-.5)}
function abc(){if(!round){const letter=LETTERS[Math.floor(Math.random()*LETTERS.length)];round={kind:'abc',answer:letter,options:pickOptions(letter,LETTERS),done:false,feedback:''}}return lesson('ABC World',`Find the letter <strong>${round.answer}</strong>.`,`<div class="lesson-target letter-target">${round.answer}</div>`,round.options.map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join(''),'abc')}
function numbers(){if(!round){const n=1+Math.floor(Math.random()*state.countMax);const pool=Array.from({length:state.countMax},(_,i)=>i+1);round={kind:'count',answer:n,options:pickOptions(n,pool),done:false,feedback:''}}const objects=Array.from({length:round.answer},()=>'<span class="garage-car">🚗</span>').join('');return lesson('Number Garage','How many cars are in the garage?',`<div class="garage" aria-label="${round.answer} cars">${objects}</div>`,round.options.map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join(''),'count')}
function cars(){if(!round){const answer=CARS[Math.floor(Math.random()*CARS.length)];round={kind:'cars',answer:answer[1],icon:answer[0],options:pickOptions(answer,CARS).map(x=>x[1]),done:false,feedback:''}}return lesson('Car Match','Find the matching vehicle.',`<div class="lesson-target car-target">${round.icon}<span>${round.answer}</span></div>`,round.options.map(name=>{const car=CARS.find(x=>x[1]===name);return `<button class="choice vehicle-choice" data-answer="${name}">${car[0]}<span>${name}</span></button>`}).join(''),'cars')}
function match(){if(!round){const answer=SHAPES[Math.floor(Math.random()*SHAPES.length)];round={kind:'match',answer:answer[1],icon:answer[0],options:pickOptions(answer,SHAPES).map(x=>x[1]),done:false,feedback:''}}return lesson('Shape Match','Find the same shape.',`<div class="lesson-target">${round.icon}</div>`,round.options.map(name=>{const s=SHAPES.find(x=>x[1]===name);return `<button class="choice" data-answer="${name}">${s[0]}<span>${name}</span></button>`}).join(''),'match')}
function lesson(title,prompt,target,options,kind){return `<main class="screen">${header(title)}<section class="panel lesson-panel"><h2>${prompt}</h2>${target}<div class="choice-grid">${options}</div><p class="feedback">${round.feedback}</p><div class="action-row"><button class="secondary" data-action="hint">Show me</button>${round.done?'<button class="primary" data-action="next-round">Next</button>':''}<button class="secondary" data-nav="home">All done</button></div></section></main>`}
function play(){return `<main class="screen">${header('Play')}<section class="tiles">${tile('play','cars','🚗','Car Match','Match favorite vehicles')}${tile('learn','match','🧩','Matching','Shapes and visual matching')}<button class="tile communicate" data-action="coming"><span class="icon">🎵</span><h3>Music</h3><p>Coming next</p></button><button class="tile day" data-action="coming"><span class="icon">🖍️</span><h3>Drawing</h3><p>Coming next</p></button></section><p id="coming" class="feedback"></p></main>`}
function communicate(){return `<main class="screen">${header('Communicate')}<section class="panel"><p class="notice">Tap a card to show or say a message. This supports communication alongside Sarion's established AAC system.</p><div class="comm-grid">${COMM.map(([i,t])=>`<button class="comm" data-comm="${t}" data-say="${t}"><b>${i}</b>${t}</button>`).join('')}</div>${state.asl?'<div class="action-row"><button class="primary" data-nav="sign">🤟🏾 Learn matching signs</button></div>':''}</section></main>`}
function favorites(){const cards=COMM.filter(([,t])=>state.favorites.includes(t));return `<main class="screen">${header('Favorites')}<section class="panel"><h2>Quick words</h2><div class="comm-grid">${cards.map(([i,t])=>`<button class="comm" data-comm="${t}" data-say="${t}"><b>${i}</b>${t}</button>`).join('')}</div><p class="notice">Grown-ups can change these favorites in settings.</p></section></main>`}
function sign(){const item=SIGNS.find(x=>x[0]===selectedSign)||SIGNS[0];return `<main class="screen">${header('Sign & Talk')}<section class="panel"><p class="notice">ASL is a full communication lane. The app will only teach motion from verified sign media.</p><div class="sign-layout"><div class="sign-list">${SIGNS.map(([w,i])=>`<button class="comm ${w===selectedSign?'selected':''}" data-sign="${w}"><b>${i}</b>${w}</button>`).join('')}</div><div class="sign-detail"><div class="big">${item[1]}</div><h2>${item[0]}</h2><p>${item[2]}</p><div class="mode-row"><button class="primary" data-say="${item[0]}">🔊 Hear word</button><button class="secondary" data-action="watch-sign">👀 Watch</button><button class="secondary" data-action="copy-sign">🙌 Copy Me</button></div><div class="asl-pending"><strong>Verified ASL model pending</strong><p>No guessed hand pose will be shown as a sign. This slot is ready for reviewed video/animation media.</p></div></div></div></section></main>`}
function day(){return `<main class="screen">${header('My Day')}<section class="panel"><h2>Now and next</h2><div class="routine">${state.routine.map((x,i)=>`<div class="routine-item ${i<routineIndex?'done':''}"><span>${i===routineIndex?'👉 ':''}${x}</span><span>${i<routineIndex?'✓':i===routineIndex?'Now':'Next'}</span></div>`).join('')}</div><div class="action-row">${routineIndex<state.routine.length?'<button class="primary" data-action="routine-done">Done with this</button>':''}<button class="secondary" data-action="routine-reset">Start over</button></div></section></main>`}
function breakScreen(){return `<main class="screen">${header('Break')}<section class="panel break-card"><div class="big">☁️</div><h2>Take your time.</h2><p>No timer. No points. Return whenever you're ready.</p><div class="action-row centered"><button class="primary" data-action="return">Return</button><button class="secondary" data-nav="home">All done</button></div></section></main>`}
function help(){return `<main class="screen">${header('Help')}<section class="panel break-card"><div class="big">🖐</div><h2>I need help</h2><p>Show this screen to a grown-up.</p><div class="action-row centered"><button class="primary" data-action="return">Go back</button></div></section></main>`}
function grownups(){const favOptions=COMM.map(([,t])=>`<label class="check"><input type="checkbox" data-favorite="${t}" ${state.favorites.includes(t)?'checked':''}/> ${t}</label>`).join('');const visibility=Object.entries(state.show).map(([k,v])=>`<label class="check"><input type="checkbox" data-show="${k}" ${v?'checked':''}/> Show ${k}</label>`).join('');return `<main class="screen">${header('For grown-ups')}<section class="panel"><h2>Parent Mode</h2><p class="notice">Accidental-tap guard only. Settings and activity counts stay in this browser.</p><div class="settings-grid"><div class="setting"><label>Answer choices</label><select id="choices"><option value="2" ${state.choices===2?'selected':''}>2</option><option value="3" ${state.choices===3?'selected':''}>3</option></select></div><div class="setting"><label>Counting range</label><select id="countMax"><option value="3" ${state.countMax===3?'selected':''}>1–3</option><option value="5" ${state.countMax===5?'selected':''}>1–5</option></select></div><div class="setting"><label class="check"><input type="checkbox" id="speech" ${state.speech?'checked':''}/> Local tap-to-hear speech</label><label class="check"><input type="checkbox" id="asl" ${state.asl?'checked':''}/> Show Sign & Talk / ASL</label></div><div class="setting"><strong>Activity visibility</strong><div class="setting-grid-inline">${visibility}</div></div><div class="setting"><strong>Favorite communication cards</strong><div class="setting-grid-inline">${favOptions}</div></div><div class="setting"><strong>Local activity</strong><span>ABC: ${state.stats.abc}</span><span>Numbers: ${state.stats.count}</span><span>Car Match: ${state.stats.cars}</span><span>Shape Match: ${state.stats.match}</span><span>Communication taps: ${state.stats.comm}</span><span>Sign lessons opened: ${state.stats.signViews}</span><span>Hints: ${state.stats.hints}</span></div></div><div class="action-row"><button class="primary" data-action="save-settings">Save settings</button><button class="secondary" data-action="reset-data">Reset local data</button></div><p id="save-note" class="feedback"></p></section></main>`}
function render(){const screens={home,learn,play,communicate,favorites,sign,day,abc,numbers,cars,match,break:breakScreen,help,grownups};app.innerHTML=(screens[current]||home)();bind()}
function bind(){app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));app.querySelectorAll('[data-say]').forEach(b=>b.onclick=()=>speak(b.dataset.say));app.querySelectorAll('[data-comm]').forEach(b=>b.onclick=()=>{state.stats.comm++;save();speak(b.dataset.comm)});app.querySelectorAll('[data-sign]').forEach(b=>b.onclick=()=>{selectedSign=b.dataset.sign;state.stats.signViews++;save();render()});app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(round.done)return;const ans=String(b.dataset.answer);if(ans===String(round.answer)){round.done=true;round.feedback='Great job!';state.stats[round.kind]=(state.stats[round.kind]||0)+1;save();speak(String(round.answer))}else round.feedback='You can try another one.';render()});app.querySelector('[data-action="hint"]')?.addEventListener('click',()=>{if(!round.hint){round.hint=true;state.stats.hints++;save()}round.feedback=`Look for ${round.answer}.`;render()});app.querySelector('[data-action="next-round"]')?.addEventListener('click',()=>{round=null;render()});app.querySelectorAll('[data-action="coming"]').forEach(b=>b.onclick=()=>{const e=document.querySelector('#coming');if(e)e.textContent='That activity is coming next.'});app.querySelector('[data-action="watch-sign"]')?.addEventListener('click',()=>{document.querySelector('.asl-pending p').textContent='This spot is reserved for verified ASL media. No unverified movement will be taught.'});app.querySelector('[data-action="copy-sign"]')?.addEventListener('click',()=>{document.querySelector('.asl-pending p').textContent='Copy Me will activate after verified ASL media is installed. No camera scoring is used.'});app.querySelector('[data-action="routine-done"]')?.addEventListener('click',()=>{routineIndex=Math.min(state.routine.length,routineIndex+1);render()});app.querySelector('[data-action="routine-reset"]')?.addEventListener('click',()=>{routineIndex=0;render()});app.querySelector('[data-action="return"]')?.addEventListener('click',()=>{current=['break','help'].includes(lastScreen)?'home':lastScreen;render()});app.querySelector('[data-action="save-settings"]')?.addEventListener('click',()=>{state.choices=+document.querySelector('#choices').value;state.countMax=+document.querySelector('#countMax').value;state.speech=document.querySelector('#speech').checked;state.asl=document.querySelector('#asl').checked;document.querySelectorAll('[data-show]').forEach(x=>state.show[x.dataset.show]=x.checked);state.favorites=[...document.querySelectorAll('[data-favorite]:checked')].map(x=>x.dataset.favorite);const ok=save();document.querySelector('#save-note').textContent=ok?'Saved on this iPad/browser.':'Changes work now but could not be saved.'});app.querySelector('[data-action="reset-data"]')?.addEventListener('click',()=>{if(confirm("Reset Sarion's World local settings and activity counts?")){state=cloneDefaults();save();round=null;render()}})}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
render();