/var/log/blackspire-command/command.log {
  su blackspire blackspire
  daily
  rotate 14
  maxsize 50M
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
  create 0640 blackspire blackspire
}

/var/log/blackspire-command/worker.log {
  su blackspire blackspire
  daily
  rotate 14
  maxsize 50M
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
  create 0640 blackspire blackspire
}
