/var/log/blackspire-command/command.log {
  su blackspire-api blackspire
  daily
  rotate 14
  maxsize 50M
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
  create 0660 blackspire-api blackspire
}

/var/log/blackspire-command/worker.log {
  su blackspire-worker blackspire
  daily
  rotate 14
  maxsize 50M
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
  create 0660 blackspire-worker blackspire
}
