import type { SellerSourceType } from "@/lib/seller-engine";

export type SellerCountyStarterSource = {
  county: string;
  state: "NC";
  name: string;
  sourceType: SellerSourceType;
  sourceUrl: string;
  integrationType: "county_portal";
  notes: string;
};

export const SELLER_COUNTY_STARTER_SOURCES: SellerCountyStarterSource[] = [
  {
    county: "Mecklenburg",
    state: "NC",
    name: "Mecklenburg Open Mapping",
    sourceType: "gis_property_data",
    sourceUrl: "https://maps.mecklenburgcountync.gov/openmapping/",
    integrationType: "county_portal",
    notes: "Official Mecklenburg County open mapping and parcel access point.",
  },
  {
    county: "Mecklenburg",
    state: "NC",
    name: "Mecklenburg Tax Foreclosure Properties",
    sourceType: "foreclosure",
    sourceUrl: "https://tax.mecknc.gov/",
    integrationType: "county_portal",
    notes: "Official Mecklenburg tax office portal with delinquent property lists and tax foreclosure properties.",
  },
  {
    county: "Wake",
    state: "NC",
    name: "Wake County Open Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://data.wake.gov/",
    integrationType: "county_portal",
    notes: "Official Wake County open data portal for parcel and property research inputs.",
  },
  {
    county: "Wake",
    state: "NC",
    name: "Wake CRPI Foreclosure Notices",
    sourceType: "foreclosure",
    sourceUrl: "https://rodcrpi.wake.gov/bookshelp2/crpifeatures.html",
    integrationType: "county_portal",
    notes: "Official Wake Register of Deeds CRPI help page documenting foreclosure notice access.",
  },
  {
    county: "Forsyth",
    state: "NC",
    name: "Forsyth CAD Parcels",
    sourceType: "gis_property_data",
    sourceUrl: "https://maps.co.forsyth.nc.us/arcgis/rest/services/CAD/CAD_Parcels/MapServer",
    integrationType: "county_portal",
    notes: "Official Forsyth parcel MapServer service.",
  },
  {
    county: "Forsyth",
    state: "NC",
    name: "Forsyth Property Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.co.forsyth.nc.us/Tax/foreclosure.aspx",
    integrationType: "county_portal",
    notes: "Official Forsyth tax foreclosure sales page.",
  },
  {
    county: "Guilford",
    state: "NC",
    name: "Guilford GIS Online Services",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.guilfordcountync.gov/government/departments-and-agencies/information-technology/geographic-information-systems/gis-online-services",
    integrationType: "county_portal",
    notes: "Official Guilford GIS services index with parcel research and open data tools.",
  },
  {
    county: "Guilford",
    state: "NC",
    name: "Guilford Foreclosure Research Tool",
    sourceType: "foreclosure",
    sourceUrl: "https://www.guilfordcountync.gov/government/departments-and-agencies/information-technology/geographic-information-systems/gis-online-services",
    integrationType: "county_portal",
    notes: "Official Guilford GIS page linking the county foreclosure research tool.",
  },
  {
    county: "Cumberland",
    state: "NC",
    name: "Cumberland Real Estate GIS Mapping",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.cumberlandcountync.gov/departments/tax-group/tax/real-estate-gis-mapping",
    integrationType: "county_portal",
    notes: "Official Cumberland real estate and GIS mapping access point.",
  },
  {
    county: "Cumberland",
    state: "NC",
    name: "Cumberland Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.cumberlandcountync.gov/departments/tax-group/tax/tax-foreclosure-sales",
    integrationType: "county_portal",
    notes: "Official Cumberland tax foreclosure sales list.",
  },
  {
    county: "Cumberland",
    state: "NC",
    name: "Cumberland Delinquent Taxes",
    sourceType: "tax_delinquent",
    sourceUrl: "https://www.cumberlandcountync.gov/CustomContent/tax/delinquent_taxes/delinquent_taxes.aspx?TaxDelinquent_GVChangePage=91_20",
    integrationType: "county_portal",
    notes: "Official Cumberland delinquent tax advertisement page.",
  },
  // ── Triangle / Piedmont ──────────────────────────────────────────────────
  {
    county: "Durham",
    state: "NC",
    name: "Durham County GIS Parcel Viewer",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.dconc.gov/government/departments-f-z/tax-administration/real-estate-records",
    integrationType: "county_portal",
    notes: "Official Durham County tax administration page with parcel and real estate record access.",
  },
  {
    county: "Durham",
    state: "NC",
    name: "Durham County Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.dconc.gov/government/departments-f-z/tax-administration/tax-foreclosure-sales",
    integrationType: "county_portal",
    notes: "Official Durham County tax foreclosure sales listings.",
  },
  {
    county: "Johnston",
    state: "NC",
    name: "Johnston County GIS Portal",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.johnstonnc.com/main.cfm?action=Tax_List",
    integrationType: "county_portal",
    notes: "Official Johnston County property and parcel search.",
  },
  {
    county: "Johnston",
    state: "NC",
    name: "Johnston County Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.johnstonnc.com/main.cfm?action=Tax_Foreclosure",
    integrationType: "county_portal",
    notes: "Official Johnston County tax foreclosure listings.",
  },
  {
    county: "Chatham",
    state: "NC",
    name: "Chatham County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.chathamnc.org/government/departments-a-z/tax-office",
    integrationType: "county_portal",
    notes: "Official Chatham County tax office with parcel and real estate data.",
  },
  {
    county: "Harnett",
    state: "NC",
    name: "Harnett County Property Search",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.harnett.org/tax/",
    integrationType: "county_portal",
    notes: "Official Harnett County tax department and property records portal.",
  },
  // ── Charlotte metro ───────────────────────────────────────────────────────
  {
    county: "Cabarrus",
    state: "NC",
    name: "Cabarrus County GIS Parcel Search",
    sourceType: "gis_property_data",
    sourceUrl: "https://cabarruscounty.us/departments/tax-administration",
    integrationType: "county_portal",
    notes: "Official Cabarrus County tax administration and parcel search.",
  },
  {
    county: "Cabarrus",
    state: "NC",
    name: "Cabarrus County Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://cabarruscounty.us/departments/tax-administration/foreclosure-sales",
    integrationType: "county_portal",
    notes: "Official Cabarrus County tax foreclosure sales listings.",
  },
  {
    county: "Union",
    state: "NC",
    name: "Union County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.unioncountync.gov/government/departments/tax-administration",
    integrationType: "county_portal",
    notes: "Official Union County tax administration and property records.",
  },
  {
    county: "Union",
    state: "NC",
    name: "Union County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.unioncountync.gov/government/departments/tax-administration/tax-foreclosures",
    integrationType: "county_portal",
    notes: "Official Union County tax foreclosure listings.",
  },
  {
    county: "Iredell",
    state: "NC",
    name: "Iredell County GIS Parcel Viewer",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.co.iredell.nc.us/213/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Iredell County tax administration and parcel access.",
  },
  {
    county: "Gaston",
    state: "NC",
    name: "Gaston County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.gastongov.com/government/departments/tax_collector_tax_administration",
    integrationType: "county_portal",
    notes: "Official Gaston County tax and parcel administration portal.",
  },
  {
    county: "Gaston",
    state: "NC",
    name: "Gaston County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.gastongov.com/government/departments/tax_collector_tax_administration/tax_foreclosure",
    integrationType: "county_portal",
    notes: "Official Gaston County tax foreclosure listings.",
  },
  // ── Piedmont Triad ────────────────────────────────────────────────────────
  {
    county: "Alamance",
    state: "NC",
    name: "Alamance County Property Records",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.alamance-nc.com/taxadministration/",
    integrationType: "county_portal",
    notes: "Official Alamance County tax administration and parcel data.",
  },
  {
    county: "Randolph",
    state: "NC",
    name: "Randolph County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.randolphcountync.gov/Departments/Tax-Department",
    integrationType: "county_portal",
    notes: "Official Randolph County tax department and parcel access.",
  },
  {
    county: "Catawba",
    state: "NC",
    name: "Catawba County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.catawbacountync.gov/county-services/tax/",
    integrationType: "county_portal",
    notes: "Official Catawba County tax and parcel data portal.",
  },
  {
    county: "Catawba",
    state: "NC",
    name: "Catawba County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.catawbacountync.gov/county-services/tax/tax-foreclosures/",
    integrationType: "county_portal",
    notes: "Official Catawba County tax foreclosure sales listings.",
  },
  // ── Western NC / Mountains ────────────────────────────────────────────────
  {
    county: "Buncombe",
    state: "NC",
    name: "Buncombe County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.buncombecounty.org/governing/depts/tax/",
    integrationType: "county_portal",
    notes: "Official Buncombe County tax and real property records portal.",
  },
  {
    county: "Buncombe",
    state: "NC",
    name: "Buncombe County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.buncombecounty.org/governing/depts/tax/foreclosure.aspx",
    integrationType: "county_portal",
    notes: "Official Buncombe County tax foreclosure sales listings.",
  },
  {
    county: "Henderson",
    state: "NC",
    name: "Henderson County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://hendersoncountync.gov/tax",
    integrationType: "county_portal",
    notes: "Official Henderson County tax and parcel data portal.",
  },
  // ── Coastal / Cape Fear region ────────────────────────────────────────────
  {
    county: "New Hanover",
    state: "NC",
    name: "New Hanover County GIS Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.nhcgov.com/582/GIS-Data-Downloads",
    integrationType: "county_portal",
    notes: "Official New Hanover County GIS parcel data downloads.",
  },
  {
    county: "New Hanover",
    state: "NC",
    name: "New Hanover County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.nhcgov.com/167/Tax-Foreclosures",
    integrationType: "county_portal",
    notes: "Official New Hanover County tax foreclosure listings.",
  },
  {
    county: "Brunswick",
    state: "NC",
    name: "Brunswick County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.brunswickcountync.gov/tax/",
    integrationType: "county_portal",
    notes: "Official Brunswick County tax and parcel data portal.",
  },
  {
    county: "Onslow",
    state: "NC",
    name: "Onslow County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.onslowcountync.gov/276/Tax",
    integrationType: "county_portal",
    notes: "Official Onslow County tax and parcel records portal.",
  },
  // ── Eastern NC ────────────────────────────────────────────────────────────
  {
    county: "Pitt",
    state: "NC",
    name: "Pitt County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.pittcountync.gov/229/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Pitt County tax administration and parcel records.",
  },
  {
    county: "Pitt",
    state: "NC",
    name: "Pitt County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.pittcountync.gov/229/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Pitt County tax administration page listing foreclosure notices.",
  },
  {
    county: "Wayne",
    state: "NC",
    name: "Wayne County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.waynegov.com/219/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Wayne County tax administration and parcel records.",
  },
  {
    county: "Moore",
    state: "NC",
    name: "Moore County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.moorecountync.gov/index.php/tax-administration",
    integrationType: "county_portal",
    notes: "Official Moore County tax administration and parcel records portal.",
  },
];
