import type { SellerSourceType } from "@/lib/seller-engine";

export type SellerCountyStarterSource = {
  county: string;
  state: "NC";
  name: string;
  sourceType: SellerSourceType;
  sourceUrl: string;
  integrationType: "county_portal";
  notes: string;
};

export const SELLER_COUNTY_STARTER_SOURCES: SellerCountyStarterSource[] = [
  {
    county: "Mecklenburg",
    state: "NC",
    name: "Mecklenburg Open Mapping",
    sourceType: "gis_property_data",
    sourceUrl: "https://maps.mecklenburgcountync.gov/openmapping/",
    integrationType: "county_portal",
    notes: "Official Mecklenburg County open mapping and parcel access point.",
  },
  {
    county: "Mecklenburg",
    state: "NC",
    name: "Mecklenburg Tax Foreclosure Properties",
    sourceType: "foreclosure",
    sourceUrl: "https://tax.mecknc.gov/",
    integrationType: "county_portal",
    notes: "Official Mecklenburg tax office portal with delinquent property lists and tax foreclosure properties.",
  },
  {
    county: "Wake",
    state: "NC",
    name: "Wake County Open Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://data.wake.gov/",
    integrationType: "county_portal",
    notes: "Official Wake County open data portal for parcel and property research inputs.",
  },
  {
    county: "Wake",
    state: "NC",
    name: "Wake CRPI Foreclosure Notices",
    sourceType: "foreclosure",
    sourceUrl: "https://rodcrpi.wake.gov/bookshelp2/crpifeatures.html",
    integrationType: "county_portal",
    notes: "Official Wake Register of Deeds CRPI help page documenting foreclosure notice access.",
  },
  {
    county: "Forsyth",
    state: "NC",
    name: "Forsyth CAD Parcels",
    sourceType: "gis_property_data",
    sourceUrl: "https://maps.co.forsyth.nc.us/arcgis/rest/services/CAD/CAD_Parcels/MapServer",
    integrationType: "county_portal",
    notes: "Official Forsyth parcel MapServer service.",
  },
  {
    county: "Forsyth",
    state: "NC",
    name: "Forsyth Property Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.co.forsyth.nc.us/Tax/foreclosure.aspx",
    integrationType: "county_portal",
    notes: "Official Forsyth tax foreclosure sales page.",
  },
  {
    county: "Guilford",
    state: "NC",
    name: "Guilford GIS Online Services",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.guilfordcountync.gov/government/departments-and-agencies/information-technology/geographic-information-systems/gis-online-services",
    integrationType: "county_portal",
    notes: "Official Guilford GIS services index with parcel research and open data tools.",
  },
  {
    county: "Guilford",
    state: "NC",
    name: "Guilford Foreclosure Research Tool",
    sourceType: "foreclosure",
    sourceUrl: "https://www.guilfordcountync.gov/government/departments-and-agencies/information-technology/geographic-information-systems/gis-online-services",
    integrationType: "county_portal",
    notes: "Official Guilford GIS page linking the county foreclosure research tool.",
  },
  {
    county: "Cumberland",
    state: "NC",
    name: "Cumberland Real Estate GIS Mapping",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.cumberlandcountync.gov/departments/tax-group/tax/real-estate-gis-mapping",
    integrationType: "county_portal",
    notes: "Official Cumberland real estate and GIS mapping access point.",
  },
  {
    county: "Cumberland",
    state: "NC",
    name: "Cumberland Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.cumberlandcountync.gov/departments/tax-group/tax/tax-foreclosure-sales",
    integrationType: "county_portal",
    notes: "Official Cumberland tax foreclosure sales list.",
  },
  {
    county: "Cumberland",
    state: "NC",
    name: "Cumberland Delinquent Taxes",
    sourceType: "tax_delinquent",
    sourceUrl: "https://www.cumberlandcountync.gov/CustomContent/tax/delinquent_taxes/delinquent_taxes.aspx?TaxDelinquent_GVChangePage=91_20",
    integrationType: "county_portal",
    notes: "Official Cumberland delinquent tax advertisement page.",
  },
  // ── Triangle / Piedmont ──────────────────────────────────────────────────
  {
    county: "Durham",
    state: "NC",
    name: "Durham County GIS Parcel Viewer",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.dconc.gov/government/departments-f-z/tax-administration/real-estate-records",
    integrationType: "county_portal",
    notes: "Official Durham County tax administration page with parcel and real estate record access.",
  },
  {
    county: "Durham",
    state: "NC",
    name: "Durham County Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.dconc.gov/government/departments-f-z/tax-administration/tax-foreclosure-sales",
    integrationType: "county_portal",
    notes: "Official Durham County tax foreclosure sales listings.",
  },
  {
    county: "Johnston",
    state: "NC",
    name: "Johnston County GIS Portal",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.johnstonnc.com/main.cfm?action=Tax_List",
    integrationType: "county_portal",
    notes: "Official Johnston County property and parcel search.",
  },
  {
    county: "Johnston",
    state: "NC",
    name: "Johnston County Tax Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://www.johnstonnc.com/main.cfm?action=Tax_Foreclosure",
    integrationType: "county_portal",
    notes: "Official Johnston County tax foreclosure listings.",
  },
  {
    county: "Chatham",
    state: "NC",
    name: "Chatham County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.chathamnc.org/government/departments-a-z/tax-office",
    integrationType: "county_portal",
    notes: "Official Chatham County tax office with parcel and real estate data.",
  },
  {
    county: "Harnett",
    state: "NC",
    name: "Harnett County Property Search",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.harnett.org/tax/",
    integrationType: "county_portal",
    notes: "Official Harnett County tax department and property records portal.",
  },
  // ── Charlotte metro ───────────────────────────────────────────────────────
  {
    county: "Cabarrus",
    state: "NC",
    name: "Cabarrus County GIS Parcel Search",
    sourceType: "gis_property_data",
    sourceUrl: "https://cabarruscounty.us/departments/tax-administration",
    integrationType: "county_portal",
    notes: "Official Cabarrus County tax administration and parcel search.",
  },
  {
    county: "Cabarrus",
    state: "NC",
    name: "Cabarrus County Foreclosure Sales",
    sourceType: "foreclosure",
    sourceUrl: "https://cabarruscounty.us/departments/tax-administration/foreclosure-sales",
    integrationType: "county_portal",
    notes: "Official Cabarrus County tax foreclosure sales listings.",
  },
  {
    county: "Union",
    state: "NC",
    name: "Union County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.unioncountync.gov/government/departments/tax-administration",
    integrationType: "county_portal",
    notes: "Official Union County tax administration and property records.",
  },
  {
    county: "Union",
    state: "NC",
    name: "Union County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.unioncountync.gov/government/departments/tax-administration/tax-foreclosures",
    integrationType: "county_portal",
    notes: "Official Union County tax foreclosure listings.",
  },
  {
    county: "Iredell",
    state: "NC",
    name: "Iredell County GIS Parcel Viewer",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.co.iredell.nc.us/213/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Iredell County tax administration and parcel access.",
  },
  {
    county: "Gaston",
    state: "NC",
    name: "Gaston County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.gastongov.com/government/departments/tax_collector_tax_administration",
    integrationType: "county_portal",
    notes: "Official Gaston County tax and parcel administration portal.",
  },
  {
    county: "Gaston",
    state: "NC",
    name: "Gaston County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.gastongov.com/government/departments/tax_collector_tax_administration/tax_foreclosure",
    integrationType: "county_portal",
    notes: "Official Gaston County tax foreclosure listings.",
  },
  // ── Piedmont Triad ────────────────────────────────────────────────────────
  {
    county: "Alamance",
    state: "NC",
    name: "Alamance County Property Records",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.alamance-nc.com/taxadministration/",
    integrationType: "county_portal",
    notes: "Official Alamance County tax administration and parcel data.",
  },
  {
    county: "Randolph",
    state: "NC",
    name: "Randolph County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.randolphcountync.gov/Departments/Tax-Department",
    integrationType: "county_portal",
    notes: "Official Randolph County tax department and parcel access.",
  },
  {
    county: "Catawba",
    state: "NC",
    name: "Catawba County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.catawbacountync.gov/county-services/tax/",
    integrationType: "county_portal",
    notes: "Official Catawba County tax and parcel data portal.",
  },
  {
    county: "Catawba",
    state: "NC",
    name: "Catawba County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.catawbacountync.gov/county-services/tax/tax-foreclosures/",
    integrationType: "county_portal",
    notes: "Official Catawba County tax foreclosure sales listings.",
  },
  // ── Western NC / Mountains ────────────────────────────────────────────────
  {
    county: "Buncombe",
    state: "NC",
    name: "Buncombe County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.buncombecounty.org/governing/depts/tax/",
    integrationType: "county_portal",
    notes: "Official Buncombe County tax and real property records portal.",
  },
  {
    county: "Buncombe",
    state: "NC",
    name: "Buncombe County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.buncombecounty.org/governing/depts/tax/foreclosure.aspx",
    integrationType: "county_portal",
    notes: "Official Buncombe County tax foreclosure sales listings.",
  },
  {
    county: "Henderson",
    state: "NC",
    name: "Henderson County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://hendersoncountync.gov/tax",
    integrationType: "county_portal",
    notes: "Official Henderson County tax and parcel data portal.",
  },
  // ── Coastal / Cape Fear region ────────────────────────────────────────────
  {
    county: "New Hanover",
    state: "NC",
    name: "New Hanover County GIS Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.nhcgov.com/582/GIS-Data-Downloads",
    integrationType: "county_portal",
    notes: "Official New Hanover County GIS parcel data downloads.",
  },
  {
    county: "New Hanover",
    state: "NC",
    name: "New Hanover County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.nhcgov.com/167/Tax-Foreclosures",
    integrationType: "county_portal",
    notes: "Official New Hanover County tax foreclosure listings.",
  },
  {
    county: "Brunswick",
    state: "NC",
    name: "Brunswick County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.brunswickcountync.gov/tax/",
    integrationType: "county_portal",
    notes: "Official Brunswick County tax and parcel data portal.",
  },
  {
    county: "Onslow",
    state: "NC",
    name: "Onslow County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.onslowcountync.gov/276/Tax",
    integrationType: "county_portal",
    notes: "Official Onslow County tax and parcel records portal.",
  },
  // ── Eastern NC ────────────────────────────────────────────────────────────
  {
    county: "Pitt",
    state: "NC",
    name: "Pitt County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.pittcountync.gov/229/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Pitt County tax administration and parcel records.",
  },
  {
    county: "Pitt",
    state: "NC",
    name: "Pitt County Tax Foreclosure",
    sourceType: "foreclosure",
    sourceUrl: "https://www.pittcountync.gov/229/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Pitt County tax administration page listing foreclosure notices.",
  },
  {
    county: "Wayne",
    state: "NC",
    name: "Wayne County GIS Property Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.waynegov.com/219/Tax-Administration",
    integrationType: "county_portal",
    notes: "Official Wayne County tax administration and parcel records.",
  },
  {
    county: "Moore",
    state: "NC",
    name: "Moore County GIS Parcel Data",
    sourceType: "gis_property_data",
    sourceUrl: "https://www.moorecountync.gov/index.php/tax-administration",
    integrationType: "county_portal",
    notes: "Official Moore County tax administration and parcel records portal.",
  },
  // ── Western Mountains (wave 3) ──────────────────────────────────────────
  { county: "Haywood", state: "NC", name: "Haywood County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.haywoodnc.net/tax/", integrationType: "county_portal", notes: "Official Haywood County tax and parcel records portal." },
  { county: "Cherokee", state: "NC", name: "Cherokee County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.cherokeecountync.gov/tax/", integrationType: "county_portal", notes: "Official Cherokee County tax and parcel records portal." },
  { county: "Polk", state: "NC", name: "Polk County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.polknc.org/tax/", integrationType: "county_portal", notes: "Official Polk County tax and parcel records portal." },
  { county: "Rutherford", state: "NC", name: "Rutherford County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.rutherfordcountync.gov/tax/", integrationType: "county_portal", notes: "Official Rutherford County tax and parcel records portal." },
  { county: "McDowell", state: "NC", name: "McDowell County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.mcdowellgov.com/tax/", integrationType: "county_portal", notes: "Official McDowell County tax and parcel records portal." },
  { county: "Transylvania", state: "NC", name: "Transylvania County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.transylvaniacounty.org/departments/tax/", integrationType: "county_portal", notes: "Official Transylvania County tax and parcel records portal." },
  { county: "Yancey", state: "NC", name: "Yancey County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.yanceycountync.gov/tax/", integrationType: "county_portal", notes: "Official Yancey County tax and parcel records portal." },
  // ── Foothills / Piedmont (wave 3) ──────────────────────────────────────
  { county: "Cleveland", state: "NC", name: "Cleveland County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.clevelandcounty.com/tax/", integrationType: "county_portal", notes: "Official Cleveland County tax and parcel records portal." },
  { county: "Davie", state: "NC", name: "Davie County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.daviecountync.gov/tax/", integrationType: "county_portal", notes: "Official Davie County tax and parcel records portal." },
  { county: "Yadkin", state: "NC", name: "Yadkin County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.yadkincountync.gov/tax/", integrationType: "county_portal", notes: "Official Yadkin County tax and parcel records portal." },
  { county: "Montgomery", state: "NC", name: "Montgomery County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.montgomerycountync.com/tax/", integrationType: "county_portal", notes: "Official Montgomery County tax and parcel records portal." },
  // ── Coastal / Albemarle Sound (wave 3) ──────────────────────────────────
  { county: "Carteret", state: "NC", name: "Carteret County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.carteretcountygov.com/tax/", integrationType: "county_portal", notes: "Official Carteret County tax and parcel records portal." },
  { county: "Pamlico", state: "NC", name: "Pamlico County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.pamlicocounty.org/tax/", integrationType: "county_portal", notes: "Official Pamlico County tax and parcel records portal." },
  { county: "Chowan", state: "NC", name: "Chowan County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.chowancounty-nc.gov/tax/", integrationType: "county_portal", notes: "Official Chowan County tax and parcel records portal." },
  { county: "Pasquotank", state: "NC", name: "Pasquotank County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.pasquotankcounty.us/tax/", integrationType: "county_portal", notes: "Official Pasquotank County tax and parcel records portal." },
  { county: "Currituck", state: "NC", name: "Currituck County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.co.currituck.nc.us/tax-administration.cfm", integrationType: "county_portal", notes: "Official Currituck County tax and parcel records portal." },
  { county: "Dare", state: "NC", name: "Dare County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.darenc.gov/departments/tax/", integrationType: "county_portal", notes: "Official Dare County tax and parcel records portal." },
  // ── Southeast / Cape Fear inland (wave 3) ───────────────────────────────
  { county: "Bladen", state: "NC", name: "Bladen County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.bladencounty.org/tax/", integrationType: "county_portal", notes: "Official Bladen County tax and parcel records portal." },
  { county: "Columbus", state: "NC", name: "Columbus County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.columbuscounty.org/tax/", integrationType: "county_portal", notes: "Official Columbus County tax and parcel records portal." },
  // ── Piedmont / Eastern fringe (wave 3) ──────────────────────────────────
  { county: "Person", state: "NC", name: "Person County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.personcounty.net/tax/", integrationType: "county_portal", notes: "Official Person County tax and parcel records portal." },
  { county: "Lenoir", state: "NC", name: "Lenoir County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.lenoircountync.gov/tax/", integrationType: "county_portal", notes: "Official Lenoir County tax and parcel records portal." },
  { county: "Franklin", state: "NC", name: "Franklin County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.franklincountync.us/services/tax/", integrationType: "county_portal", notes: "Official Franklin County tax and parcel records portal." },
  // ── Southern NC / Sandhills (wave 3) ────────────────────────────────────
  { county: "Hoke", state: "NC", name: "Hoke County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.hokecounty.net/tax/", integrationType: "county_portal", notes: "Official Hoke County tax and parcel records portal." },
  // ── Far Western NC (wave 3) ─────────────────────────────────────────────
  { county: "Jackson", state: "NC", name: "Jackson County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.jacksonnc.org/tax/", integrationType: "county_portal", notes: "Official Jackson County tax and parcel records portal." },
  { county: "Macon", state: "NC", name: "Macon County GIS Property Data", sourceType: "gis_property_data", sourceUrl: "https://www.maconnc.org/tax/", integrationType: "county_portal", notes: "Official Macon County tax and parcel records portal." },
];
